package com.sd.app.bean.sfa;

// Generated Nov 22, 2014 1:19:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * FollowUps generated by hbm2java
 */
public class FollowUps implements java.io.Serializable {

	private FollowUpsId id;

	public FollowUps() {
	}

	public FollowUps(FollowUpsId id) {
		this.id = id;
	}

	public FollowUpsId getId() {
		return this.id;
	}

	public void setId(FollowUpsId id) {
		this.id = id;
	}

}
