package com.sd.app.bean.sfa;

// Generated Nov 22, 2014 1:19:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sfasummary generated by hbm2java
 */
public class Sfasummary implements java.io.Serializable {

	private SfasummaryId id;

	public Sfasummary() {
	}

	public Sfasummary(SfasummaryId id) {
		this.id = id;
	}

	public SfasummaryId getId() {
		return this.id;
	}

	public void setId(SfasummaryId id) {
		this.id = id;
	}

}
