package com.sd.app.bean.ratetables;

// Generated Nov 22, 2014 1:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExtraRtablesId generated by hbm2java
 */
public class ExtraRtablesId implements java.io.Serializable {

	private String exTable;
	private String master;
	private Integer code;
	private String strCode;
	private String name;
	private Float thick;
	private Float rangeFrom;
	private Float rangeTo;
	private Float rate;
	private String rateType;
	private Integer rtIdNo;

	public ExtraRtablesId() {
	}

	public ExtraRtablesId(String exTable, String master, Integer code, String strCode, String name, Float thick, Float rangeFrom, Float rangeTo,
			Float rate, String rateType, Integer rtIdNo) {
		this.exTable = exTable;
		this.master = master;
		this.code = code;
		this.strCode = strCode;
		this.name = name;
		this.thick = thick;
		this.rangeFrom = rangeFrom;
		this.rangeTo = rangeTo;
		this.rate = rate;
		this.rateType = rateType;
		this.rtIdNo = rtIdNo;
	}

	public String getExTable() {
		return this.exTable;
	}

	public void setExTable(String exTable) {
		this.exTable = exTable;
	}

	public String getMaster() {
		return this.master;
	}

	public void setMaster(String master) {
		this.master = master;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public String getStrCode() {
		return this.strCode;
	}

	public void setStrCode(String strCode) {
		this.strCode = strCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public Float getRangeFrom() {
		return this.rangeFrom;
	}

	public void setRangeFrom(Float rangeFrom) {
		this.rangeFrom = rangeFrom;
	}

	public Float getRangeTo() {
		return this.rangeTo;
	}

	public void setRangeTo(Float rangeTo) {
		this.rangeTo = rangeTo;
	}

	public Float getRate() {
		return this.rate;
	}

	public void setRate(Float rate) {
		this.rate = rate;
	}

	public String getRateType() {
		return this.rateType;
	}

	public void setRateType(String rateType) {
		this.rateType = rateType;
	}

	public Integer getRtIdNo() {
		return this.rtIdNo;
	}

	public void setRtIdNo(Integer rtIdNo) {
		this.rtIdNo = rtIdNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExtraRtablesId))
			return false;
		ExtraRtablesId castOther = (ExtraRtablesId) other;

		return ((this.getExTable() == castOther.getExTable()) || (this.getExTable() != null && castOther.getExTable() != null && this.getExTable()
				.equals(castOther.getExTable())))
				&& ((this.getMaster() == castOther.getMaster()) || (this.getMaster() != null && castOther.getMaster() != null && this.getMaster()
						.equals(castOther.getMaster())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null && this.getCode().equals(
						castOther.getCode())))
				&& ((this.getStrCode() == castOther.getStrCode()) || (this.getStrCode() != null && castOther.getStrCode() != null && this
						.getStrCode().equals(castOther.getStrCode())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(
						castOther.getName())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getRangeFrom() == castOther.getRangeFrom()) || (this.getRangeFrom() != null && castOther.getRangeFrom() != null && this
						.getRangeFrom().equals(castOther.getRangeFrom())))
				&& ((this.getRangeTo() == castOther.getRangeTo()) || (this.getRangeTo() != null && castOther.getRangeTo() != null && this
						.getRangeTo().equals(castOther.getRangeTo())))
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null && castOther.getRate() != null && this.getRate().equals(
						castOther.getRate())))
				&& ((this.getRateType() == castOther.getRateType()) || (this.getRateType() != null && castOther.getRateType() != null && this
						.getRateType().equals(castOther.getRateType())))
				&& ((this.getRtIdNo() == castOther.getRtIdNo()) || (this.getRtIdNo() != null && castOther.getRtIdNo() != null && this.getRtIdNo()
						.equals(castOther.getRtIdNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getExTable() == null ? 0 : this.getExTable().hashCode());
		result = 37 * result + (getMaster() == null ? 0 : this.getMaster().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getStrCode() == null ? 0 : this.getStrCode().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getRangeFrom() == null ? 0 : this.getRangeFrom().hashCode());
		result = 37 * result + (getRangeTo() == null ? 0 : this.getRangeTo().hashCode());
		result = 37 * result + (getRate() == null ? 0 : this.getRate().hashCode());
		result = 37 * result + (getRateType() == null ? 0 : this.getRateType().hashCode());
		result = 37 * result + (getRtIdNo() == null ? 0 : this.getRtIdNo().hashCode());
		return result;
	}

}
