package com.sd.app.bean.ratetables;

// Generated Nov 22, 2014 1:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * SizeTables generated by hbm2java
 */
public class SizeTables implements java.io.Serializable {

	private SizeTablesId id;

	public SizeTables() {
	}

	public SizeTables(SizeTablesId id) {
		this.id = id;
	}

	public SizeTablesId getId() {
		return this.id;
	}

	public void setId(SizeTablesId id) {
		this.id = id;
	}

}
