package com.sd.app.bean.ratetables;

// Generated Nov 22, 2014 1:15:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SqmRtables generated by hbm2java
 */
public class SqmRtables implements java.io.Serializable {

	private SqmRtablesId id;
	private String invoiceDetails;
	private String productionDetails;
	private Float rate;
	private Date entryDate;
	private Date modifyDate;
	private String itcode;
	private Integer rtIdNo;
	private String material;
	private Boolean addExcise;

	public SqmRtables() {
	}

	public SqmRtables(SqmRtablesId id) {
		this.id = id;
	}

	public SqmRtables(SqmRtablesId id, String invoiceDetails, String productionDetails, Float rate, Date entryDate, Date modifyDate, String itcode,
			Integer rtIdNo, String material, Boolean addExcise) {
		this.id = id;
		this.invoiceDetails = invoiceDetails;
		this.productionDetails = productionDetails;
		this.rate = rate;
		this.entryDate = entryDate;
		this.modifyDate = modifyDate;
		this.itcode = itcode;
		this.rtIdNo = rtIdNo;
		this.material = material;
		this.addExcise = addExcise;
	}

	public SqmRtablesId getId() {
		return this.id;
	}

	public void setId(SqmRtablesId id) {
		this.id = id;
	}

	public String getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(String invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

	public String getProductionDetails() {
		return this.productionDetails;
	}

	public void setProductionDetails(String productionDetails) {
		this.productionDetails = productionDetails;
	}

	public Float getRate() {
		return this.rate;
	}

	public void setRate(Float rate) {
		this.rate = rate;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getItcode() {
		return this.itcode;
	}

	public void setItcode(String itcode) {
		this.itcode = itcode;
	}

	public Integer getRtIdNo() {
		return this.rtIdNo;
	}

	public void setRtIdNo(Integer rtIdNo) {
		this.rtIdNo = rtIdNo;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public Boolean getAddExcise() {
		return this.addExcise;
	}

	public void setAddExcise(Boolean addExcise) {
		this.addExcise = addExcise;
	}

}
