package com.sd.app.bean.ratetables;

// Generated Nov 22, 2014 1:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * SqmRtablesId generated by hbm2java
 */
public class SqmRtablesId implements java.io.Serializable {

	private String rtable;
	private Float thick;
	private String icode;
	private String bend;
	private String tough;

	public SqmRtablesId() {
	}

	public SqmRtablesId(String rtable, Float thick, String icode, String bend, String tough) {
		this.rtable = rtable;
		this.thick = thick;
		this.icode = icode;
		this.bend = bend;
		this.tough = tough;
	}

	public String getRtable() {
		return this.rtable;
	}

	public void setRtable(String rtable) {
		this.rtable = rtable;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getBend() {
		return this.bend;
	}

	public void setBend(String bend) {
		this.bend = bend;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SqmRtablesId))
			return false;
		SqmRtablesId castOther = (SqmRtablesId) other;

		return ((this.getRtable() == castOther.getRtable()) || (this.getRtable() != null && castOther.getRtable() != null && this.getRtable().equals(
				castOther.getRtable())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getBend() == castOther.getBend()) || (this.getBend() != null && castOther.getBend() != null && this.getBend().equals(
						castOther.getBend())))
				&& ((this.getTough() == castOther.getTough()) || (this.getTough() != null && castOther.getTough() != null && this.getTough().equals(
						castOther.getTough())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRtable() == null ? 0 : this.getRtable().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getBend() == null ? 0 : this.getBend().hashCode());
		result = 37 * result + (getTough() == null ? 0 : this.getTough().hashCode());
		return result;
	}

}
