package com.sd.app.bean.ratetables;

// Generated Nov 22, 2014 1:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StandardItemsId generated by hbm2java
 */
public class StandardItemsId implements java.io.Serializable {

	private Integer idNo;
	private String icode;
	private Float thick;
	private String tough;
	private String bend;
	private String productionDetails;
	private String invoiceDetails;
	private Short width;
	private Short height;
	private Short taper;
	private String grinding;
	private Short frosting;
	private Short beveling;
	private Short printing;
	private Short oddShape;
	private Short holeType1;
	private Short holeNos1;
	private Short holeDia1;
	private Short holeType2;
	private Short holeNos2;
	private Short holeDia2;
	private Short cutOutType1;
	private Short cutOutNos1;
	private Short cutOutType2;
	private Short cutOutNos2;
	private String shape;
	private Short r1;
	private Short r2;
	private Short r3;
	private Short r4;
	private String itcode;
	private String type;
	private Boolean decorative;

	public StandardItemsId() {
	}

	public StandardItemsId(Integer idNo, String icode, Float thick, String tough, String bend, String productionDetails, String invoiceDetails,
			Short width, Short height, Short taper, String grinding, Short frosting, Short beveling, Short printing, Short oddShape, Short holeType1,
			Short holeNos1, Short holeDia1, Short holeType2, Short holeNos2, Short holeDia2, Short cutOutType1, Short cutOutNos1, Short cutOutType2,
			Short cutOutNos2, String shape, Short r1, Short r2, Short r3, Short r4, String itcode, String type, Boolean decorative) {
		this.idNo = idNo;
		this.icode = icode;
		this.thick = thick;
		this.tough = tough;
		this.bend = bend;
		this.productionDetails = productionDetails;
		this.invoiceDetails = invoiceDetails;
		this.width = width;
		this.height = height;
		this.taper = taper;
		this.grinding = grinding;
		this.frosting = frosting;
		this.beveling = beveling;
		this.printing = printing;
		this.oddShape = oddShape;
		this.holeType1 = holeType1;
		this.holeNos1 = holeNos1;
		this.holeDia1 = holeDia1;
		this.holeType2 = holeType2;
		this.holeNos2 = holeNos2;
		this.holeDia2 = holeDia2;
		this.cutOutType1 = cutOutType1;
		this.cutOutNos1 = cutOutNos1;
		this.cutOutType2 = cutOutType2;
		this.cutOutNos2 = cutOutNos2;
		this.shape = shape;
		this.r1 = r1;
		this.r2 = r2;
		this.r3 = r3;
		this.r4 = r4;
		this.itcode = itcode;
		this.type = type;
		this.decorative = decorative;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public String getBend() {
		return this.bend;
	}

	public void setBend(String bend) {
		this.bend = bend;
	}

	public String getProductionDetails() {
		return this.productionDetails;
	}

	public void setProductionDetails(String productionDetails) {
		this.productionDetails = productionDetails;
	}

	public String getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(String invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

	public Short getWidth() {
		return this.width;
	}

	public void setWidth(Short width) {
		this.width = width;
	}

	public Short getHeight() {
		return this.height;
	}

	public void setHeight(Short height) {
		this.height = height;
	}

	public Short getTaper() {
		return this.taper;
	}

	public void setTaper(Short taper) {
		this.taper = taper;
	}

	public String getGrinding() {
		return this.grinding;
	}

	public void setGrinding(String grinding) {
		this.grinding = grinding;
	}

	public Short getFrosting() {
		return this.frosting;
	}

	public void setFrosting(Short frosting) {
		this.frosting = frosting;
	}

	public Short getBeveling() {
		return this.beveling;
	}

	public void setBeveling(Short beveling) {
		this.beveling = beveling;
	}

	public Short getPrinting() {
		return this.printing;
	}

	public void setPrinting(Short printing) {
		this.printing = printing;
	}

	public Short getOddShape() {
		return this.oddShape;
	}

	public void setOddShape(Short oddShape) {
		this.oddShape = oddShape;
	}

	public Short getHoleType1() {
		return this.holeType1;
	}

	public void setHoleType1(Short holeType1) {
		this.holeType1 = holeType1;
	}

	public Short getHoleNos1() {
		return this.holeNos1;
	}

	public void setHoleNos1(Short holeNos1) {
		this.holeNos1 = holeNos1;
	}

	public Short getHoleDia1() {
		return this.holeDia1;
	}

	public void setHoleDia1(Short holeDia1) {
		this.holeDia1 = holeDia1;
	}

	public Short getHoleType2() {
		return this.holeType2;
	}

	public void setHoleType2(Short holeType2) {
		this.holeType2 = holeType2;
	}

	public Short getHoleNos2() {
		return this.holeNos2;
	}

	public void setHoleNos2(Short holeNos2) {
		this.holeNos2 = holeNos2;
	}

	public Short getHoleDia2() {
		return this.holeDia2;
	}

	public void setHoleDia2(Short holeDia2) {
		this.holeDia2 = holeDia2;
	}

	public Short getCutOutType1() {
		return this.cutOutType1;
	}

	public void setCutOutType1(Short cutOutType1) {
		this.cutOutType1 = cutOutType1;
	}

	public Short getCutOutNos1() {
		return this.cutOutNos1;
	}

	public void setCutOutNos1(Short cutOutNos1) {
		this.cutOutNos1 = cutOutNos1;
	}

	public Short getCutOutType2() {
		return this.cutOutType2;
	}

	public void setCutOutType2(Short cutOutType2) {
		this.cutOutType2 = cutOutType2;
	}

	public Short getCutOutNos2() {
		return this.cutOutNos2;
	}

	public void setCutOutNos2(Short cutOutNos2) {
		this.cutOutNos2 = cutOutNos2;
	}

	public String getShape() {
		return this.shape;
	}

	public void setShape(String shape) {
		this.shape = shape;
	}

	public Short getR1() {
		return this.r1;
	}

	public void setR1(Short r1) {
		this.r1 = r1;
	}

	public Short getR2() {
		return this.r2;
	}

	public void setR2(Short r2) {
		this.r2 = r2;
	}

	public Short getR3() {
		return this.r3;
	}

	public void setR3(Short r3) {
		this.r3 = r3;
	}

	public Short getR4() {
		return this.r4;
	}

	public void setR4(Short r4) {
		this.r4 = r4;
	}

	public String getItcode() {
		return this.itcode;
	}

	public void setItcode(String itcode) {
		this.itcode = itcode;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Boolean getDecorative() {
		return this.decorative;
	}

	public void setDecorative(Boolean decorative) {
		this.decorative = decorative;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StandardItemsId))
			return false;
		StandardItemsId castOther = (StandardItemsId) other;

		return ((this.getIdNo() == castOther.getIdNo()) || (this.getIdNo() != null && castOther.getIdNo() != null && this.getIdNo().equals(
				castOther.getIdNo())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getTough() == castOther.getTough()) || (this.getTough() != null && castOther.getTough() != null && this.getTough().equals(
						castOther.getTough())))
				&& ((this.getBend() == castOther.getBend()) || (this.getBend() != null && castOther.getBend() != null && this.getBend().equals(
						castOther.getBend())))
				&& ((this.getProductionDetails() == castOther.getProductionDetails()) || (this.getProductionDetails() != null
						&& castOther.getProductionDetails() != null && this.getProductionDetails().equals(castOther.getProductionDetails())))
				&& ((this.getInvoiceDetails() == castOther.getInvoiceDetails()) || (this.getInvoiceDetails() != null
						&& castOther.getInvoiceDetails() != null && this.getInvoiceDetails().equals(castOther.getInvoiceDetails())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getTaper() == castOther.getTaper()) || (this.getTaper() != null && castOther.getTaper() != null && this.getTaper().equals(
						castOther.getTaper())))
				&& ((this.getGrinding() == castOther.getGrinding()) || (this.getGrinding() != null && castOther.getGrinding() != null && this
						.getGrinding().equals(castOther.getGrinding())))
				&& ((this.getFrosting() == castOther.getFrosting()) || (this.getFrosting() != null && castOther.getFrosting() != null && this
						.getFrosting().equals(castOther.getFrosting())))
				&& ((this.getBeveling() == castOther.getBeveling()) || (this.getBeveling() != null && castOther.getBeveling() != null && this
						.getBeveling().equals(castOther.getBeveling())))
				&& ((this.getPrinting() == castOther.getPrinting()) || (this.getPrinting() != null && castOther.getPrinting() != null && this
						.getPrinting().equals(castOther.getPrinting())))
				&& ((this.getOddShape() == castOther.getOddShape()) || (this.getOddShape() != null && castOther.getOddShape() != null && this
						.getOddShape().equals(castOther.getOddShape())))
				&& ((this.getHoleType1() == castOther.getHoleType1()) || (this.getHoleType1() != null && castOther.getHoleType1() != null && this
						.getHoleType1().equals(castOther.getHoleType1())))
				&& ((this.getHoleNos1() == castOther.getHoleNos1()) || (this.getHoleNos1() != null && castOther.getHoleNos1() != null && this
						.getHoleNos1().equals(castOther.getHoleNos1())))
				&& ((this.getHoleDia1() == castOther.getHoleDia1()) || (this.getHoleDia1() != null && castOther.getHoleDia1() != null && this
						.getHoleDia1().equals(castOther.getHoleDia1())))
				&& ((this.getHoleType2() == castOther.getHoleType2()) || (this.getHoleType2() != null && castOther.getHoleType2() != null && this
						.getHoleType2().equals(castOther.getHoleType2())))
				&& ((this.getHoleNos2() == castOther.getHoleNos2()) || (this.getHoleNos2() != null && castOther.getHoleNos2() != null && this
						.getHoleNos2().equals(castOther.getHoleNos2())))
				&& ((this.getHoleDia2() == castOther.getHoleDia2()) || (this.getHoleDia2() != null && castOther.getHoleDia2() != null && this
						.getHoleDia2().equals(castOther.getHoleDia2())))
				&& ((this.getCutOutType1() == castOther.getCutOutType1()) || (this.getCutOutType1() != null && castOther.getCutOutType1() != null && this
						.getCutOutType1().equals(castOther.getCutOutType1())))
				&& ((this.getCutOutNos1() == castOther.getCutOutNos1()) || (this.getCutOutNos1() != null && castOther.getCutOutNos1() != null && this
						.getCutOutNos1().equals(castOther.getCutOutNos1())))
				&& ((this.getCutOutType2() == castOther.getCutOutType2()) || (this.getCutOutType2() != null && castOther.getCutOutType2() != null && this
						.getCutOutType2().equals(castOther.getCutOutType2())))
				&& ((this.getCutOutNos2() == castOther.getCutOutNos2()) || (this.getCutOutNos2() != null && castOther.getCutOutNos2() != null && this
						.getCutOutNos2().equals(castOther.getCutOutNos2())))
				&& ((this.getShape() == castOther.getShape()) || (this.getShape() != null && castOther.getShape() != null && this.getShape().equals(
						castOther.getShape())))
				&& ((this.getR1() == castOther.getR1()) || (this.getR1() != null && castOther.getR1() != null && this.getR1().equals(
						castOther.getR1())))
				&& ((this.getR2() == castOther.getR2()) || (this.getR2() != null && castOther.getR2() != null && this.getR2().equals(
						castOther.getR2())))
				&& ((this.getR3() == castOther.getR3()) || (this.getR3() != null && castOther.getR3() != null && this.getR3().equals(
						castOther.getR3())))
				&& ((this.getR4() == castOther.getR4()) || (this.getR4() != null && castOther.getR4() != null && this.getR4().equals(
						castOther.getR4())))
				&& ((this.getItcode() == castOther.getItcode()) || (this.getItcode() != null && castOther.getItcode() != null && this.getItcode()
						.equals(castOther.getItcode())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this.getType().equals(
						castOther.getType())))
				&& ((this.getDecorative() == castOther.getDecorative()) || (this.getDecorative() != null && castOther.getDecorative() != null && this
						.getDecorative().equals(castOther.getDecorative())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdNo() == null ? 0 : this.getIdNo().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getTough() == null ? 0 : this.getTough().hashCode());
		result = 37 * result + (getBend() == null ? 0 : this.getBend().hashCode());
		result = 37 * result + (getProductionDetails() == null ? 0 : this.getProductionDetails().hashCode());
		result = 37 * result + (getInvoiceDetails() == null ? 0 : this.getInvoiceDetails().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getTaper() == null ? 0 : this.getTaper().hashCode());
		result = 37 * result + (getGrinding() == null ? 0 : this.getGrinding().hashCode());
		result = 37 * result + (getFrosting() == null ? 0 : this.getFrosting().hashCode());
		result = 37 * result + (getBeveling() == null ? 0 : this.getBeveling().hashCode());
		result = 37 * result + (getPrinting() == null ? 0 : this.getPrinting().hashCode());
		result = 37 * result + (getOddShape() == null ? 0 : this.getOddShape().hashCode());
		result = 37 * result + (getHoleType1() == null ? 0 : this.getHoleType1().hashCode());
		result = 37 * result + (getHoleNos1() == null ? 0 : this.getHoleNos1().hashCode());
		result = 37 * result + (getHoleDia1() == null ? 0 : this.getHoleDia1().hashCode());
		result = 37 * result + (getHoleType2() == null ? 0 : this.getHoleType2().hashCode());
		result = 37 * result + (getHoleNos2() == null ? 0 : this.getHoleNos2().hashCode());
		result = 37 * result + (getHoleDia2() == null ? 0 : this.getHoleDia2().hashCode());
		result = 37 * result + (getCutOutType1() == null ? 0 : this.getCutOutType1().hashCode());
		result = 37 * result + (getCutOutNos1() == null ? 0 : this.getCutOutNos1().hashCode());
		result = 37 * result + (getCutOutType2() == null ? 0 : this.getCutOutType2().hashCode());
		result = 37 * result + (getCutOutNos2() == null ? 0 : this.getCutOutNos2().hashCode());
		result = 37 * result + (getShape() == null ? 0 : this.getShape().hashCode());
		result = 37 * result + (getR1() == null ? 0 : this.getR1().hashCode());
		result = 37 * result + (getR2() == null ? 0 : this.getR2().hashCode());
		result = 37 * result + (getR3() == null ? 0 : this.getR3().hashCode());
		result = 37 * result + (getR4() == null ? 0 : this.getR4().hashCode());
		result = 37 * result + (getItcode() == null ? 0 : this.getItcode().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getDecorative() == null ? 0 : this.getDecorative().hashCode());
		return result;
	}

}
