package com.sd.app.bean.ratetables;

// Generated Nov 22, 2014 1:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * StandardItems generated by hbm2java
 */
public class StandardItems implements java.io.Serializable {

	private StandardItemsId id;

	public StandardItems() {
	}

	public StandardItems(StandardItemsId id) {
		this.id = id;
	}

	public StandardItemsId getId() {
		return this.id;
	}

	public void setId(StandardItemsId id) {
		this.id = id;
	}

}
