package com.sd.app.bean.ratetables;

// Generated Nov 22, 2014 1:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * TransferRates generated by hbm2java
 */
public class TransferRates implements java.io.Serializable {

	private TransferRatesId id;

	public TransferRates() {
	}

	public TransferRates(TransferRatesId id) {
		this.id = id;
	}

	public TransferRatesId getId() {
		return this.id;
	}

	public void setId(TransferRatesId id) {
		this.id = id;
	}

}
