package com.sd.app.bean.proforma;

// Generated Nov 22, 2014 1:13:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * PinvDetails generated by hbm2java
 */
public class PinvDetails implements java.io.Serializable {

	private PinvDetailsId id;

	public PinvDetails() {
	}

	public PinvDetails(PinvDetailsId id) {
		this.id = id;
	}

	public PinvDetailsId getId() {
		return this.id;
	}

	public void setId(PinvDetailsId id) {
		this.id = id;
	}

}
