package com.sd.app.bean.orders;

// Generated Nov 22, 2014 1:10:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExportImportId generated by hbm2java
 */
public class ExportImportId implements java.io.Serializable {

	private String expImp;
	private Date sdate;
	private Date edate;
	private String time;
	private String dataType;

	public ExportImportId() {
	}

	public ExportImportId(String expImp, Date sdate, Date edate, String time, String dataType) {
		this.expImp = expImp;
		this.sdate = sdate;
		this.edate = edate;
		this.time = time;
		this.dataType = dataType;
	}

	public String getExpImp() {
		return this.expImp;
	}

	public void setExpImp(String expImp) {
		this.expImp = expImp;
	}

	public Date getSdate() {
		return this.sdate;
	}

	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	public Date getEdate() {
		return this.edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExportImportId))
			return false;
		ExportImportId castOther = (ExportImportId) other;

		return ((this.getExpImp() == castOther.getExpImp()) || (this.getExpImp() != null && castOther.getExpImp() != null && this.getExpImp().equals(
				castOther.getExpImp())))
				&& ((this.getSdate() == castOther.getSdate()) || (this.getSdate() != null && castOther.getSdate() != null && this.getSdate().equals(
						castOther.getSdate())))
				&& ((this.getEdate() == castOther.getEdate()) || (this.getEdate() != null && castOther.getEdate() != null && this.getEdate().equals(
						castOther.getEdate())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null && this.getTime().equals(
						castOther.getTime())))
				&& ((this.getDataType() == castOther.getDataType()) || (this.getDataType() != null && castOther.getDataType() != null && this
						.getDataType().equals(castOther.getDataType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getExpImp() == null ? 0 : this.getExpImp().hashCode());
		result = 37 * result + (getSdate() == null ? 0 : this.getSdate().hashCode());
		result = 37 * result + (getEdate() == null ? 0 : this.getEdate().hashCode());
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		result = 37 * result + (getDataType() == null ? 0 : this.getDataType().hashCode());
		return result;
	}

}
