package com.sd.app.bean.orders;

// Generated Nov 22, 2014 1:10:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderLamSizesId generated by hbm2java
 */
public class OrderLamSizesId implements java.io.Serializable {

	private Integer orderIdNo;
	private String orderNo;
	private Float width;
	private Short widths1;
	private Short widths2;
	private Float height;
	private Short heights1;
	private Short heights2;
	private Float taper;
	private Short tapers1;
	private Short tapers2;
	private Short pcs;
	private Short bpcs;
	private String remarks;
	private Short itNo;
	private String refNo;
	private String tsd;
	private Short cpcs;

	public OrderLamSizesId() {
	}

	public OrderLamSizesId(Integer orderIdNo, String orderNo, Float width, Short widths1, Short widths2, Float height, Short heights1,
			Short heights2, Float taper, Short tapers1, Short tapers2, Short pcs, Short bpcs, String remarks, Short itNo, String refNo, String tsd,
			Short cpcs) {
		this.orderIdNo = orderIdNo;
		this.orderNo = orderNo;
		this.width = width;
		this.widths1 = widths1;
		this.widths2 = widths2;
		this.height = height;
		this.heights1 = heights1;
		this.heights2 = heights2;
		this.taper = taper;
		this.tapers1 = tapers1;
		this.tapers2 = tapers2;
		this.pcs = pcs;
		this.bpcs = bpcs;
		this.remarks = remarks;
		this.itNo = itNo;
		this.refNo = refNo;
		this.tsd = tsd;
		this.cpcs = cpcs;
	}

	public Integer getOrderIdNo() {
		return this.orderIdNo;
	}

	public void setOrderIdNo(Integer orderIdNo) {
		this.orderIdNo = orderIdNo;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Float getWidth() {
		return this.width;
	}

	public void setWidth(Float width) {
		this.width = width;
	}

	public Short getWidths1() {
		return this.widths1;
	}

	public void setWidths1(Short widths1) {
		this.widths1 = widths1;
	}

	public Short getWidths2() {
		return this.widths2;
	}

	public void setWidths2(Short widths2) {
		this.widths2 = widths2;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Short getHeights1() {
		return this.heights1;
	}

	public void setHeights1(Short heights1) {
		this.heights1 = heights1;
	}

	public Short getHeights2() {
		return this.heights2;
	}

	public void setHeights2(Short heights2) {
		this.heights2 = heights2;
	}

	public Float getTaper() {
		return this.taper;
	}

	public void setTaper(Float taper) {
		this.taper = taper;
	}

	public Short getTapers1() {
		return this.tapers1;
	}

	public void setTapers1(Short tapers1) {
		this.tapers1 = tapers1;
	}

	public Short getTapers2() {
		return this.tapers2;
	}

	public void setTapers2(Short tapers2) {
		this.tapers2 = tapers2;
	}

	public Short getPcs() {
		return this.pcs;
	}

	public void setPcs(Short pcs) {
		this.pcs = pcs;
	}

	public Short getBpcs() {
		return this.bpcs;
	}

	public void setBpcs(Short bpcs) {
		this.bpcs = bpcs;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Short getItNo() {
		return this.itNo;
	}

	public void setItNo(Short itNo) {
		this.itNo = itNo;
	}

	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	public String getTsd() {
		return this.tsd;
	}

	public void setTsd(String tsd) {
		this.tsd = tsd;
	}

	public Short getCpcs() {
		return this.cpcs;
	}

	public void setCpcs(Short cpcs) {
		this.cpcs = cpcs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderLamSizesId))
			return false;
		OrderLamSizesId castOther = (OrderLamSizesId) other;

		return ((this.getOrderIdNo() == castOther.getOrderIdNo()) || (this.getOrderIdNo() != null && castOther.getOrderIdNo() != null && this
				.getOrderIdNo().equals(castOther.getOrderIdNo())))
				&& ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null && castOther.getOrderNo() != null && this
						.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getWidths1() == castOther.getWidths1()) || (this.getWidths1() != null && castOther.getWidths1() != null && this
						.getWidths1().equals(castOther.getWidths1())))
				&& ((this.getWidths2() == castOther.getWidths2()) || (this.getWidths2() != null && castOther.getWidths2() != null && this
						.getWidths2().equals(castOther.getWidths2())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getHeights1() == castOther.getHeights1()) || (this.getHeights1() != null && castOther.getHeights1() != null && this
						.getHeights1().equals(castOther.getHeights1())))
				&& ((this.getHeights2() == castOther.getHeights2()) || (this.getHeights2() != null && castOther.getHeights2() != null && this
						.getHeights2().equals(castOther.getHeights2())))
				&& ((this.getTaper() == castOther.getTaper()) || (this.getTaper() != null && castOther.getTaper() != null && this.getTaper().equals(
						castOther.getTaper())))
				&& ((this.getTapers1() == castOther.getTapers1()) || (this.getTapers1() != null && castOther.getTapers1() != null && this
						.getTapers1().equals(castOther.getTapers1())))
				&& ((this.getTapers2() == castOther.getTapers2()) || (this.getTapers2() != null && castOther.getTapers2() != null && this
						.getTapers2().equals(castOther.getTapers2())))
				&& ((this.getPcs() == castOther.getPcs()) || (this.getPcs() != null && castOther.getPcs() != null && this.getPcs().equals(
						castOther.getPcs())))
				&& ((this.getBpcs() == castOther.getBpcs()) || (this.getBpcs() != null && castOther.getBpcs() != null && this.getBpcs().equals(
						castOther.getBpcs())))
				&& ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null && castOther.getRemarks() != null && this
						.getRemarks().equals(castOther.getRemarks())))
				&& ((this.getItNo() == castOther.getItNo()) || (this.getItNo() != null && castOther.getItNo() != null && this.getItNo().equals(
						castOther.getItNo())))
				&& ((this.getRefNo() == castOther.getRefNo()) || (this.getRefNo() != null && castOther.getRefNo() != null && this.getRefNo().equals(
						castOther.getRefNo())))
				&& ((this.getTsd() == castOther.getTsd()) || (this.getTsd() != null && castOther.getTsd() != null && this.getTsd().equals(
						castOther.getTsd())))
				&& ((this.getCpcs() == castOther.getCpcs()) || (this.getCpcs() != null && castOther.getCpcs() != null && this.getCpcs().equals(
						castOther.getCpcs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderIdNo() == null ? 0 : this.getOrderIdNo().hashCode());
		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getWidths1() == null ? 0 : this.getWidths1().hashCode());
		result = 37 * result + (getWidths2() == null ? 0 : this.getWidths2().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getHeights1() == null ? 0 : this.getHeights1().hashCode());
		result = 37 * result + (getHeights2() == null ? 0 : this.getHeights2().hashCode());
		result = 37 * result + (getTaper() == null ? 0 : this.getTaper().hashCode());
		result = 37 * result + (getTapers1() == null ? 0 : this.getTapers1().hashCode());
		result = 37 * result + (getTapers2() == null ? 0 : this.getTapers2().hashCode());
		result = 37 * result + (getPcs() == null ? 0 : this.getPcs().hashCode());
		result = 37 * result + (getBpcs() == null ? 0 : this.getBpcs().hashCode());
		result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
		result = 37 * result + (getItNo() == null ? 0 : this.getItNo().hashCode());
		result = 37 * result + (getRefNo() == null ? 0 : this.getRefNo().hashCode());
		result = 37 * result + (getTsd() == null ? 0 : this.getTsd().hashCode());
		result = 37 * result + (getCpcs() == null ? 0 : this.getCpcs().hashCode());
		return result;
	}

}
