package com.sd.app.bean.orders;

// Generated Nov 22, 2014 1:10:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderLamSizes generated by hbm2java
 */
public class OrderLamSizes implements java.io.Serializable {

	private OrderLamSizesId id;

	public OrderLamSizes() {
	}

	public OrderLamSizes(OrderLamSizesId id) {
		this.id = id;
	}

	public OrderLamSizesId getId() {
		return this.id;
	}

	public void setId(OrderLamSizesId id) {
		this.id = id;
	}

}
