package com.sd.app.bean.orders;

// Generated Nov 22, 2014 1:10:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderLamMaster generated by hbm2java
 */
public class OrderLamMaster implements java.io.Serializable {

	private OrderLamMasterId id;

	public OrderLamMaster() {
	}

	public OrderLamMaster(OrderLamMasterId id) {
		this.id = id;
	}

	public OrderLamMasterId getId() {
		return this.id;
	}

	public void setId(OrderLamMasterId id) {
		this.id = id;
	}

}
