package com.sd.app.bean.orders;

// Generated Nov 22, 2014 1:10:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderSub generated by hbm2java
 */
public class OrderSub implements java.io.Serializable {

	private OrderSubId id;

	public OrderSub() {
	}

	public OrderSub(OrderSubId id) {
		this.id = id;
	}

	public OrderSubId getId() {
		return this.id;
	}

	public void setId(OrderSubId id) {
		this.id = id;
	}

}
