package com.sd.app.bean.optimization;

// Generated Nov 22, 2014 1:09:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * OptDetails generated by hbm2java
 */
public class OptDetails implements java.io.Serializable {

	private OptDetailsId id;

	public OptDetails() {
	}

	public OptDetails(OptDetailsId id) {
		this.id = id;
	}

	public OptDetailsId getId() {
		return this.id;
	}

	public void setId(OptDetailsId id) {
		this.id = id;
	}

}
