package com.sd.app.bean.optimization;

// Generated Nov 22, 2014 1:09:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * OptHead generated by hbm2java
 */
public class OptHead implements java.io.Serializable {

	private OptHeadId id;

	public OptHead() {
	}

	public OptHead(OptHeadId id) {
		this.id = id;
	}

	public OptHeadId getId() {
		return this.id;
	}

	public void setId(OptHeadId id) {
		this.id = id;
	}

}
