package com.sd.app.bean.samples;

// Generated Nov 22, 2014 1:18:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * IssueId generated by hbm2java
 */
public class IssueId implements java.io.Serializable {

	private String coCode;
	private Integer issueNo;
	private Date date;
	private Integer pcode;
	private String despAddress;
	private String city;
	private String state;
	private String pin;

	public IssueId() {
	}

	public IssueId(String coCode, Integer issueNo, Date date, Integer pcode, String despAddress, String city, String state, String pin) {
		this.coCode = coCode;
		this.issueNo = issueNo;
		this.date = date;
		this.pcode = pcode;
		this.despAddress = despAddress;
		this.city = city;
		this.state = state;
		this.pin = pin;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(Integer issueNo) {
		this.issueNo = issueNo;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public String getDespAddress() {
		return this.despAddress;
	}

	public void setDespAddress(String despAddress) {
		this.despAddress = despAddress;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IssueId))
			return false;
		IssueId castOther = (IssueId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getIssueNo() == castOther.getIssueNo()) || (this.getIssueNo() != null && castOther.getIssueNo() != null && this
						.getIssueNo().equals(castOther.getIssueNo())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(
						castOther.getDate())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getDespAddress() == castOther.getDespAddress()) || (this.getDespAddress() != null && castOther.getDespAddress() != null && this
						.getDespAddress().equals(castOther.getDespAddress())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null && this.getCity().equals(
						castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null && castOther.getState() != null && this.getState().equals(
						castOther.getState())))
				&& ((this.getPin() == castOther.getPin()) || (this.getPin() != null && castOther.getPin() != null && this.getPin().equals(
						castOther.getPin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getIssueNo() == null ? 0 : this.getIssueNo().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getDespAddress() == null ? 0 : this.getDespAddress().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getPin() == null ? 0 : this.getPin().hashCode());
		return result;
	}

}
