package com.sd.app.bean.samples;

// Generated Nov 22, 2014 1:18:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * Receipts generated by hbm2java
 */
public class Receipts implements java.io.Serializable {

	private ReceiptsId id;

	public Receipts() {
	}

	public Receipts(ReceiptsId id) {
		this.id = id;
	}

	public ReceiptsId getId() {
		return this.id;
	}

	public void setId(ReceiptsId id) {
		this.id = id;
	}

}
