package com.sd.app.bean.samples;

// Generated Nov 22, 2014 1:18:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * StockId generated by hbm2java
 */
public class StockId implements java.io.Serializable {

	private String coCode;
	private Float thick;
	private String icode;
	private String tough;
	private String flat;
	private String material;
	private String description;
	private Float width;
	private Float height;
	private Float pcs;
	private Double sqMtr;

	public StockId() {
	}

	public StockId(String coCode, Float thick, String icode, String tough, String flat, String material, String description, Float width,
			Float height, Float pcs, Double sqMtr) {
		this.coCode = coCode;
		this.thick = thick;
		this.icode = icode;
		this.tough = tough;
		this.flat = flat;
		this.material = material;
		this.description = description;
		this.width = width;
		this.height = height;
		this.pcs = pcs;
		this.sqMtr = sqMtr;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public String getFlat() {
		return this.flat;
	}

	public void setFlat(String flat) {
		this.flat = flat;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getWidth() {
		return this.width;
	}

	public void setWidth(Float width) {
		this.width = width;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getPcs() {
		return this.pcs;
	}

	public void setPcs(Float pcs) {
		this.pcs = pcs;
	}

	public Double getSqMtr() {
		return this.sqMtr;
	}

	public void setSqMtr(Double sqMtr) {
		this.sqMtr = sqMtr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockId))
			return false;
		StockId castOther = (StockId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getTough() == castOther.getTough()) || (this.getTough() != null && castOther.getTough() != null && this.getTough().equals(
						castOther.getTough())))
				&& ((this.getFlat() == castOther.getFlat()) || (this.getFlat() != null && castOther.getFlat() != null && this.getFlat().equals(
						castOther.getFlat())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null && castOther.getMaterial() != null && this
						.getMaterial().equals(castOther.getMaterial())))
				&& ((this.getDescription() == castOther.getDescription()) || (this.getDescription() != null && castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getPcs() == castOther.getPcs()) || (this.getPcs() != null && castOther.getPcs() != null && this.getPcs().equals(
						castOther.getPcs())))
				&& ((this.getSqMtr() == castOther.getSqMtr()) || (this.getSqMtr() != null && castOther.getSqMtr() != null && this.getSqMtr().equals(
						castOther.getSqMtr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getTough() == null ? 0 : this.getTough().hashCode());
		result = 37 * result + (getFlat() == null ? 0 : this.getFlat().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getPcs() == null ? 0 : this.getPcs().hashCode());
		result = 37 * result + (getSqMtr() == null ? 0 : this.getSqMtr().hashCode());
		return result;
	}

}
