package com.sd.app.bean.samples;

// Generated Nov 22, 2014 1:18:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private StockId id;

	public Stock() {
	}

	public Stock(StockId id) {
		this.id = id;
	}

	public StockId getId() {
		return this.id;
	}

	public void setId(StockId id) {
		this.id = id;
	}

}
