package com.sd.app.bean.invoice;

// Generated Nov 22, 2014 1:01:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvDetailsId generated by hbm2java
 */
public class InvDetailsId implements java.io.Serializable {

	private Integer idNo;
	private String coCode;
	private Integer invNo;
	private String orderNo;
	private String particulars;
	private String uom;
	private String icode;
	private Float thick;
	private String bend;
	private String tough;
	private Float width;
	private Float height;
	private Float actSqMs;
	private Float billWidth;
	private Float billHeight;
	private Float billSqMs;
	private Float rate;
	private Float amount;
	private Float totalAmount;
	private String rtable;
	private String stable;
	private String exTable;
	private String type;
	private String grinding;
	private Float grindingRate;
	private Float grindingAmount;
	private Float discPer;
	private Float discAmount;
	private Short holeType;
	private Short holeNos;
	private Short holeDia;
	private Float holeRate;
	private Float holeAmount;
	private Short cutOutType;
	private Float cutOutRate;
	private Float cutOutAmount;
	private Short frosting;
	private Float frostingRate;
	private Float frostingAmount;
	private Short beveling;
	private Float bevelingRate;
	private Float bevelingAmount;
	private Float largeSize;
	private Float largeSizeRate;
	private Float largeSizeAmount;
	private Short oddShape;
	private Float oddShapeRate;
	private Float oddShapeAmount;
	private Short printing;
	private Float printingRate;
	private Float printingAmount;
	private Float pcs;
	private Short cutoutNos;
	private String itCode;
	private Short itNo;
	private String refNo;
	private String taxInvoice;

	public InvDetailsId() {
	}

	public InvDetailsId(Integer idNo, String coCode, Integer invNo, String orderNo, String particulars, String uom, String icode, Float thick,
			String bend, String tough, Float width, Float height, Float actSqMs, Float billWidth, Float billHeight, Float billSqMs, Float rate,
			Float amount, Float totalAmount, String rtable, String stable, String exTable, String type, String grinding, Float grindingRate,
			Float grindingAmount, Float discPer, Float discAmount, Short holeType, Short holeNos, Short holeDia, Float holeRate, Float holeAmount,
			Short cutOutType, Float cutOutRate, Float cutOutAmount, Short frosting, Float frostingRate, Float frostingAmount, Short beveling,
			Float bevelingRate, Float bevelingAmount, Float largeSize, Float largeSizeRate, Float largeSizeAmount, Short oddShape,
			Float oddShapeRate, Float oddShapeAmount, Short printing, Float printingRate, Float printingAmount, Float pcs, Short cutoutNos,
			String itCode, Short itNo, String refNo, String taxInvoice) {
		this.idNo = idNo;
		this.coCode = coCode;
		this.invNo = invNo;
		this.orderNo = orderNo;
		this.particulars = particulars;
		this.uom = uom;
		this.icode = icode;
		this.thick = thick;
		this.bend = bend;
		this.tough = tough;
		this.width = width;
		this.height = height;
		this.actSqMs = actSqMs;
		this.billWidth = billWidth;
		this.billHeight = billHeight;
		this.billSqMs = billSqMs;
		this.rate = rate;
		this.amount = amount;
		this.totalAmount = totalAmount;
		this.rtable = rtable;
		this.stable = stable;
		this.exTable = exTable;
		this.type = type;
		this.grinding = grinding;
		this.grindingRate = grindingRate;
		this.grindingAmount = grindingAmount;
		this.discPer = discPer;
		this.discAmount = discAmount;
		this.holeType = holeType;
		this.holeNos = holeNos;
		this.holeDia = holeDia;
		this.holeRate = holeRate;
		this.holeAmount = holeAmount;
		this.cutOutType = cutOutType;
		this.cutOutRate = cutOutRate;
		this.cutOutAmount = cutOutAmount;
		this.frosting = frosting;
		this.frostingRate = frostingRate;
		this.frostingAmount = frostingAmount;
		this.beveling = beveling;
		this.bevelingRate = bevelingRate;
		this.bevelingAmount = bevelingAmount;
		this.largeSize = largeSize;
		this.largeSizeRate = largeSizeRate;
		this.largeSizeAmount = largeSizeAmount;
		this.oddShape = oddShape;
		this.oddShapeRate = oddShapeRate;
		this.oddShapeAmount = oddShapeAmount;
		this.printing = printing;
		this.printingRate = printingRate;
		this.printingAmount = printingAmount;
		this.pcs = pcs;
		this.cutoutNos = cutoutNos;
		this.itCode = itCode;
		this.itNo = itNo;
		this.refNo = refNo;
		this.taxInvoice = taxInvoice;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getInvNo() {
		return this.invNo;
	}

	public void setInvNo(Integer invNo) {
		this.invNo = invNo;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getBend() {
		return this.bend;
	}

	public void setBend(String bend) {
		this.bend = bend;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public Float getWidth() {
		return this.width;
	}

	public void setWidth(Float width) {
		this.width = width;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getActSqMs() {
		return this.actSqMs;
	}

	public void setActSqMs(Float actSqMs) {
		this.actSqMs = actSqMs;
	}

	public Float getBillWidth() {
		return this.billWidth;
	}

	public void setBillWidth(Float billWidth) {
		this.billWidth = billWidth;
	}

	public Float getBillHeight() {
		return this.billHeight;
	}

	public void setBillHeight(Float billHeight) {
		this.billHeight = billHeight;
	}

	public Float getBillSqMs() {
		return this.billSqMs;
	}

	public void setBillSqMs(Float billSqMs) {
		this.billSqMs = billSqMs;
	}

	public Float getRate() {
		return this.rate;
	}

	public void setRate(Float rate) {
		this.rate = rate;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Float getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(Float totalAmount) {
		this.totalAmount = totalAmount;
	}

	public String getRtable() {
		return this.rtable;
	}

	public void setRtable(String rtable) {
		this.rtable = rtable;
	}

	public String getStable() {
		return this.stable;
	}

	public void setStable(String stable) {
		this.stable = stable;
	}

	public String getExTable() {
		return this.exTable;
	}

	public void setExTable(String exTable) {
		this.exTable = exTable;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getGrinding() {
		return this.grinding;
	}

	public void setGrinding(String grinding) {
		this.grinding = grinding;
	}

	public Float getGrindingRate() {
		return this.grindingRate;
	}

	public void setGrindingRate(Float grindingRate) {
		this.grindingRate = grindingRate;
	}

	public Float getGrindingAmount() {
		return this.grindingAmount;
	}

	public void setGrindingAmount(Float grindingAmount) {
		this.grindingAmount = grindingAmount;
	}

	public Float getDiscPer() {
		return this.discPer;
	}

	public void setDiscPer(Float discPer) {
		this.discPer = discPer;
	}

	public Float getDiscAmount() {
		return this.discAmount;
	}

	public void setDiscAmount(Float discAmount) {
		this.discAmount = discAmount;
	}

	public Short getHoleType() {
		return this.holeType;
	}

	public void setHoleType(Short holeType) {
		this.holeType = holeType;
	}

	public Short getHoleNos() {
		return this.holeNos;
	}

	public void setHoleNos(Short holeNos) {
		this.holeNos = holeNos;
	}

	public Short getHoleDia() {
		return this.holeDia;
	}

	public void setHoleDia(Short holeDia) {
		this.holeDia = holeDia;
	}

	public Float getHoleRate() {
		return this.holeRate;
	}

	public void setHoleRate(Float holeRate) {
		this.holeRate = holeRate;
	}

	public Float getHoleAmount() {
		return this.holeAmount;
	}

	public void setHoleAmount(Float holeAmount) {
		this.holeAmount = holeAmount;
	}

	public Short getCutOutType() {
		return this.cutOutType;
	}

	public void setCutOutType(Short cutOutType) {
		this.cutOutType = cutOutType;
	}

	public Float getCutOutRate() {
		return this.cutOutRate;
	}

	public void setCutOutRate(Float cutOutRate) {
		this.cutOutRate = cutOutRate;
	}

	public Float getCutOutAmount() {
		return this.cutOutAmount;
	}

	public void setCutOutAmount(Float cutOutAmount) {
		this.cutOutAmount = cutOutAmount;
	}

	public Short getFrosting() {
		return this.frosting;
	}

	public void setFrosting(Short frosting) {
		this.frosting = frosting;
	}

	public Float getFrostingRate() {
		return this.frostingRate;
	}

	public void setFrostingRate(Float frostingRate) {
		this.frostingRate = frostingRate;
	}

	public Float getFrostingAmount() {
		return this.frostingAmount;
	}

	public void setFrostingAmount(Float frostingAmount) {
		this.frostingAmount = frostingAmount;
	}

	public Short getBeveling() {
		return this.beveling;
	}

	public void setBeveling(Short beveling) {
		this.beveling = beveling;
	}

	public Float getBevelingRate() {
		return this.bevelingRate;
	}

	public void setBevelingRate(Float bevelingRate) {
		this.bevelingRate = bevelingRate;
	}

	public Float getBevelingAmount() {
		return this.bevelingAmount;
	}

	public void setBevelingAmount(Float bevelingAmount) {
		this.bevelingAmount = bevelingAmount;
	}

	public Float getLargeSize() {
		return this.largeSize;
	}

	public void setLargeSize(Float largeSize) {
		this.largeSize = largeSize;
	}

	public Float getLargeSizeRate() {
		return this.largeSizeRate;
	}

	public void setLargeSizeRate(Float largeSizeRate) {
		this.largeSizeRate = largeSizeRate;
	}

	public Float getLargeSizeAmount() {
		return this.largeSizeAmount;
	}

	public void setLargeSizeAmount(Float largeSizeAmount) {
		this.largeSizeAmount = largeSizeAmount;
	}

	public Short getOddShape() {
		return this.oddShape;
	}

	public void setOddShape(Short oddShape) {
		this.oddShape = oddShape;
	}

	public Float getOddShapeRate() {
		return this.oddShapeRate;
	}

	public void setOddShapeRate(Float oddShapeRate) {
		this.oddShapeRate = oddShapeRate;
	}

	public Float getOddShapeAmount() {
		return this.oddShapeAmount;
	}

	public void setOddShapeAmount(Float oddShapeAmount) {
		this.oddShapeAmount = oddShapeAmount;
	}

	public Short getPrinting() {
		return this.printing;
	}

	public void setPrinting(Short printing) {
		this.printing = printing;
	}

	public Float getPrintingRate() {
		return this.printingRate;
	}

	public void setPrintingRate(Float printingRate) {
		this.printingRate = printingRate;
	}

	public Float getPrintingAmount() {
		return this.printingAmount;
	}

	public void setPrintingAmount(Float printingAmount) {
		this.printingAmount = printingAmount;
	}

	public Float getPcs() {
		return this.pcs;
	}

	public void setPcs(Float pcs) {
		this.pcs = pcs;
	}

	public Short getCutoutNos() {
		return this.cutoutNos;
	}

	public void setCutoutNos(Short cutoutNos) {
		this.cutoutNos = cutoutNos;
	}

	public String getItCode() {
		return this.itCode;
	}

	public void setItCode(String itCode) {
		this.itCode = itCode;
	}

	public Short getItNo() {
		return this.itNo;
	}

	public void setItNo(Short itNo) {
		this.itNo = itNo;
	}

	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	public String getTaxInvoice() {
		return this.taxInvoice;
	}

	public void setTaxInvoice(String taxInvoice) {
		this.taxInvoice = taxInvoice;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvDetailsId))
			return false;
		InvDetailsId castOther = (InvDetailsId) other;

		return ((this.getIdNo() == castOther.getIdNo()) || (this.getIdNo() != null && castOther.getIdNo() != null && this.getIdNo().equals(
				castOther.getIdNo())))
				&& ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode()
						.equals(castOther.getCoCode())))
				&& ((this.getInvNo() == castOther.getInvNo()) || (this.getInvNo() != null && castOther.getInvNo() != null && this.getInvNo().equals(
						castOther.getInvNo())))
				&& ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null && castOther.getOrderNo() != null && this
						.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getParticulars() == castOther.getParticulars()) || (this.getParticulars() != null && castOther.getParticulars() != null && this
						.getParticulars().equals(castOther.getParticulars())))
				&& ((this.getUom() == castOther.getUom()) || (this.getUom() != null && castOther.getUom() != null && this.getUom().equals(
						castOther.getUom())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getBend() == castOther.getBend()) || (this.getBend() != null && castOther.getBend() != null && this.getBend().equals(
						castOther.getBend())))
				&& ((this.getTough() == castOther.getTough()) || (this.getTough() != null && castOther.getTough() != null && this.getTough().equals(
						castOther.getTough())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getActSqMs() == castOther.getActSqMs()) || (this.getActSqMs() != null && castOther.getActSqMs() != null && this
						.getActSqMs().equals(castOther.getActSqMs())))
				&& ((this.getBillWidth() == castOther.getBillWidth()) || (this.getBillWidth() != null && castOther.getBillWidth() != null && this
						.getBillWidth().equals(castOther.getBillWidth())))
				&& ((this.getBillHeight() == castOther.getBillHeight()) || (this.getBillHeight() != null && castOther.getBillHeight() != null && this
						.getBillHeight().equals(castOther.getBillHeight())))
				&& ((this.getBillSqMs() == castOther.getBillSqMs()) || (this.getBillSqMs() != null && castOther.getBillSqMs() != null && this
						.getBillSqMs().equals(castOther.getBillSqMs())))
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null && castOther.getRate() != null && this.getRate().equals(
						castOther.getRate())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null && castOther.getAmount() != null && this.getAmount()
						.equals(castOther.getAmount())))
				&& ((this.getTotalAmount() == castOther.getTotalAmount()) || (this.getTotalAmount() != null && castOther.getTotalAmount() != null && this
						.getTotalAmount().equals(castOther.getTotalAmount())))
				&& ((this.getRtable() == castOther.getRtable()) || (this.getRtable() != null && castOther.getRtable() != null && this.getRtable()
						.equals(castOther.getRtable())))
				&& ((this.getStable() == castOther.getStable()) || (this.getStable() != null && castOther.getStable() != null && this.getStable()
						.equals(castOther.getStable())))
				&& ((this.getExTable() == castOther.getExTable()) || (this.getExTable() != null && castOther.getExTable() != null && this
						.getExTable().equals(castOther.getExTable())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this.getType().equals(
						castOther.getType())))
				&& ((this.getGrinding() == castOther.getGrinding()) || (this.getGrinding() != null && castOther.getGrinding() != null && this
						.getGrinding().equals(castOther.getGrinding())))
				&& ((this.getGrindingRate() == castOther.getGrindingRate()) || (this.getGrindingRate() != null && castOther.getGrindingRate() != null && this
						.getGrindingRate().equals(castOther.getGrindingRate())))
				&& ((this.getGrindingAmount() == castOther.getGrindingAmount()) || (this.getGrindingAmount() != null
						&& castOther.getGrindingAmount() != null && this.getGrindingAmount().equals(castOther.getGrindingAmount())))
				&& ((this.getDiscPer() == castOther.getDiscPer()) || (this.getDiscPer() != null && castOther.getDiscPer() != null && this
						.getDiscPer().equals(castOther.getDiscPer())))
				&& ((this.getDiscAmount() == castOther.getDiscAmount()) || (this.getDiscAmount() != null && castOther.getDiscAmount() != null && this
						.getDiscAmount().equals(castOther.getDiscAmount())))
				&& ((this.getHoleType() == castOther.getHoleType()) || (this.getHoleType() != null && castOther.getHoleType() != null && this
						.getHoleType().equals(castOther.getHoleType())))
				&& ((this.getHoleNos() == castOther.getHoleNos()) || (this.getHoleNos() != null && castOther.getHoleNos() != null && this
						.getHoleNos().equals(castOther.getHoleNos())))
				&& ((this.getHoleDia() == castOther.getHoleDia()) || (this.getHoleDia() != null && castOther.getHoleDia() != null && this
						.getHoleDia().equals(castOther.getHoleDia())))
				&& ((this.getHoleRate() == castOther.getHoleRate()) || (this.getHoleRate() != null && castOther.getHoleRate() != null && this
						.getHoleRate().equals(castOther.getHoleRate())))
				&& ((this.getHoleAmount() == castOther.getHoleAmount()) || (this.getHoleAmount() != null && castOther.getHoleAmount() != null && this
						.getHoleAmount().equals(castOther.getHoleAmount())))
				&& ((this.getCutOutType() == castOther.getCutOutType()) || (this.getCutOutType() != null && castOther.getCutOutType() != null && this
						.getCutOutType().equals(castOther.getCutOutType())))
				&& ((this.getCutOutRate() == castOther.getCutOutRate()) || (this.getCutOutRate() != null && castOther.getCutOutRate() != null && this
						.getCutOutRate().equals(castOther.getCutOutRate())))
				&& ((this.getCutOutAmount() == castOther.getCutOutAmount()) || (this.getCutOutAmount() != null && castOther.getCutOutAmount() != null && this
						.getCutOutAmount().equals(castOther.getCutOutAmount())))
				&& ((this.getFrosting() == castOther.getFrosting()) || (this.getFrosting() != null && castOther.getFrosting() != null && this
						.getFrosting().equals(castOther.getFrosting())))
				&& ((this.getFrostingRate() == castOther.getFrostingRate()) || (this.getFrostingRate() != null && castOther.getFrostingRate() != null && this
						.getFrostingRate().equals(castOther.getFrostingRate())))
				&& ((this.getFrostingAmount() == castOther.getFrostingAmount()) || (this.getFrostingAmount() != null
						&& castOther.getFrostingAmount() != null && this.getFrostingAmount().equals(castOther.getFrostingAmount())))
				&& ((this.getBeveling() == castOther.getBeveling()) || (this.getBeveling() != null && castOther.getBeveling() != null && this
						.getBeveling().equals(castOther.getBeveling())))
				&& ((this.getBevelingRate() == castOther.getBevelingRate()) || (this.getBevelingRate() != null && castOther.getBevelingRate() != null && this
						.getBevelingRate().equals(castOther.getBevelingRate())))
				&& ((this.getBevelingAmount() == castOther.getBevelingAmount()) || (this.getBevelingAmount() != null
						&& castOther.getBevelingAmount() != null && this.getBevelingAmount().equals(castOther.getBevelingAmount())))
				&& ((this.getLargeSize() == castOther.getLargeSize()) || (this.getLargeSize() != null && castOther.getLargeSize() != null && this
						.getLargeSize().equals(castOther.getLargeSize())))
				&& ((this.getLargeSizeRate() == castOther.getLargeSizeRate()) || (this.getLargeSizeRate() != null
						&& castOther.getLargeSizeRate() != null && this.getLargeSizeRate().equals(castOther.getLargeSizeRate())))
				&& ((this.getLargeSizeAmount() == castOther.getLargeSizeAmount()) || (this.getLargeSizeAmount() != null
						&& castOther.getLargeSizeAmount() != null && this.getLargeSizeAmount().equals(castOther.getLargeSizeAmount())))
				&& ((this.getOddShape() == castOther.getOddShape()) || (this.getOddShape() != null && castOther.getOddShape() != null && this
						.getOddShape().equals(castOther.getOddShape())))
				&& ((this.getOddShapeRate() == castOther.getOddShapeRate()) || (this.getOddShapeRate() != null && castOther.getOddShapeRate() != null && this
						.getOddShapeRate().equals(castOther.getOddShapeRate())))
				&& ((this.getOddShapeAmount() == castOther.getOddShapeAmount()) || (this.getOddShapeAmount() != null
						&& castOther.getOddShapeAmount() != null && this.getOddShapeAmount().equals(castOther.getOddShapeAmount())))
				&& ((this.getPrinting() == castOther.getPrinting()) || (this.getPrinting() != null && castOther.getPrinting() != null && this
						.getPrinting().equals(castOther.getPrinting())))
				&& ((this.getPrintingRate() == castOther.getPrintingRate()) || (this.getPrintingRate() != null && castOther.getPrintingRate() != null && this
						.getPrintingRate().equals(castOther.getPrintingRate())))
				&& ((this.getPrintingAmount() == castOther.getPrintingAmount()) || (this.getPrintingAmount() != null
						&& castOther.getPrintingAmount() != null && this.getPrintingAmount().equals(castOther.getPrintingAmount())))
				&& ((this.getPcs() == castOther.getPcs()) || (this.getPcs() != null && castOther.getPcs() != null && this.getPcs().equals(
						castOther.getPcs())))
				&& ((this.getCutoutNos() == castOther.getCutoutNos()) || (this.getCutoutNos() != null && castOther.getCutoutNos() != null && this
						.getCutoutNos().equals(castOther.getCutoutNos())))
				&& ((this.getItCode() == castOther.getItCode()) || (this.getItCode() != null && castOther.getItCode() != null && this.getItCode()
						.equals(castOther.getItCode())))
				&& ((this.getItNo() == castOther.getItNo()) || (this.getItNo() != null && castOther.getItNo() != null && this.getItNo().equals(
						castOther.getItNo())))
				&& ((this.getRefNo() == castOther.getRefNo()) || (this.getRefNo() != null && castOther.getRefNo() != null && this.getRefNo().equals(
						castOther.getRefNo())))
				&& ((this.getTaxInvoice() == castOther.getTaxInvoice()) || (this.getTaxInvoice() != null && castOther.getTaxInvoice() != null && this
						.getTaxInvoice().equals(castOther.getTaxInvoice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdNo() == null ? 0 : this.getIdNo().hashCode());
		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getInvNo() == null ? 0 : this.getInvNo().hashCode());
		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getParticulars() == null ? 0 : this.getParticulars().hashCode());
		result = 37 * result + (getUom() == null ? 0 : this.getUom().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getBend() == null ? 0 : this.getBend().hashCode());
		result = 37 * result + (getTough() == null ? 0 : this.getTough().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getActSqMs() == null ? 0 : this.getActSqMs().hashCode());
		result = 37 * result + (getBillWidth() == null ? 0 : this.getBillWidth().hashCode());
		result = 37 * result + (getBillHeight() == null ? 0 : this.getBillHeight().hashCode());
		result = 37 * result + (getBillSqMs() == null ? 0 : this.getBillSqMs().hashCode());
		result = 37 * result + (getRate() == null ? 0 : this.getRate().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getTotalAmount() == null ? 0 : this.getTotalAmount().hashCode());
		result = 37 * result + (getRtable() == null ? 0 : this.getRtable().hashCode());
		result = 37 * result + (getStable() == null ? 0 : this.getStable().hashCode());
		result = 37 * result + (getExTable() == null ? 0 : this.getExTable().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getGrinding() == null ? 0 : this.getGrinding().hashCode());
		result = 37 * result + (getGrindingRate() == null ? 0 : this.getGrindingRate().hashCode());
		result = 37 * result + (getGrindingAmount() == null ? 0 : this.getGrindingAmount().hashCode());
		result = 37 * result + (getDiscPer() == null ? 0 : this.getDiscPer().hashCode());
		result = 37 * result + (getDiscAmount() == null ? 0 : this.getDiscAmount().hashCode());
		result = 37 * result + (getHoleType() == null ? 0 : this.getHoleType().hashCode());
		result = 37 * result + (getHoleNos() == null ? 0 : this.getHoleNos().hashCode());
		result = 37 * result + (getHoleDia() == null ? 0 : this.getHoleDia().hashCode());
		result = 37 * result + (getHoleRate() == null ? 0 : this.getHoleRate().hashCode());
		result = 37 * result + (getHoleAmount() == null ? 0 : this.getHoleAmount().hashCode());
		result = 37 * result + (getCutOutType() == null ? 0 : this.getCutOutType().hashCode());
		result = 37 * result + (getCutOutRate() == null ? 0 : this.getCutOutRate().hashCode());
		result = 37 * result + (getCutOutAmount() == null ? 0 : this.getCutOutAmount().hashCode());
		result = 37 * result + (getFrosting() == null ? 0 : this.getFrosting().hashCode());
		result = 37 * result + (getFrostingRate() == null ? 0 : this.getFrostingRate().hashCode());
		result = 37 * result + (getFrostingAmount() == null ? 0 : this.getFrostingAmount().hashCode());
		result = 37 * result + (getBeveling() == null ? 0 : this.getBeveling().hashCode());
		result = 37 * result + (getBevelingRate() == null ? 0 : this.getBevelingRate().hashCode());
		result = 37 * result + (getBevelingAmount() == null ? 0 : this.getBevelingAmount().hashCode());
		result = 37 * result + (getLargeSize() == null ? 0 : this.getLargeSize().hashCode());
		result = 37 * result + (getLargeSizeRate() == null ? 0 : this.getLargeSizeRate().hashCode());
		result = 37 * result + (getLargeSizeAmount() == null ? 0 : this.getLargeSizeAmount().hashCode());
		result = 37 * result + (getOddShape() == null ? 0 : this.getOddShape().hashCode());
		result = 37 * result + (getOddShapeRate() == null ? 0 : this.getOddShapeRate().hashCode());
		result = 37 * result + (getOddShapeAmount() == null ? 0 : this.getOddShapeAmount().hashCode());
		result = 37 * result + (getPrinting() == null ? 0 : this.getPrinting().hashCode());
		result = 37 * result + (getPrintingRate() == null ? 0 : this.getPrintingRate().hashCode());
		result = 37 * result + (getPrintingAmount() == null ? 0 : this.getPrintingAmount().hashCode());
		result = 37 * result + (getPcs() == null ? 0 : this.getPcs().hashCode());
		result = 37 * result + (getCutoutNos() == null ? 0 : this.getCutoutNos().hashCode());
		result = 37 * result + (getItCode() == null ? 0 : this.getItCode().hashCode());
		result = 37 * result + (getItNo() == null ? 0 : this.getItNo().hashCode());
		result = 37 * result + (getRefNo() == null ? 0 : this.getRefNo().hashCode());
		result = 37 * result + (getTaxInvoice() == null ? 0 : this.getTaxInvoice().hashCode());
		return result;
	}

}
