package com.sd.app.bean.invoice;

// Generated Nov 22, 2014 1:01:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvMaster generated by hbm2java
 */
public class InvMaster implements java.io.Serializable {

	private InvMasterId id;

	public InvMaster() {
	}

	public InvMaster(InvMasterId id) {
		this.id = id;
	}

	public InvMasterId getId() {
		return this.id;
	}

	public void setId(InvMasterId id) {
		this.id = id;
	}

}
