package com.sd.app.bean.company;

// Generated Nov 22, 2014 12:49:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CompanyId generated by hbm2java
 */
public class CompanyId implements java.io.Serializable {

	private Integer compIdNo;
	private Integer pcode;
	private String initial;
	private String name;
	private Boolean customer;
	private Boolean supplier;
	private Boolean glassSupplier;
	private String class_;
	private String type;
	private String phonetype1;
	private String zone;
	private String phone1;
	private String phone2;
	private String phoneType2;
	private String phone3;
	private String phone4;
	private String phoneType3;
	private String phone5;
	private String phone6;
	private String phoneType4;
	private String email1;
	private String phoneType5;
	private String email2;
	private String phoneType6;
	private String webSite;
	private String address;
	private String city;
	private String state;
	private String pin;
	private String crAddress;
	private String crCity;
	private String crState;
	private String crPin;
	private String country;
	private String dealBy;
	private String sdealBy;
	private String staxForm;
	private String cstNo;
	private String lstNo;
	private String eccNo;
	private String exRegNo;
	private String location;
	private String fileName;
	private String acstatus;
	private Integer creditLimit;
	private Short creditDays;
	private Boolean active;
	private Boolean regular;
	private Boolean confidential;
	private Boolean insurance;
	private Boolean intimation;
	private Boolean showDiscount;
	private Boolean showExcise;
	private Date remDate;
	private String reminder;
	private String notes;
	private String supervisorNotes;
	private String productionNotes;
	private String documentationNotes;
	private String printOnInvoice;
	private Boolean groupCompany;
	private Integer gcode;
	private Integer spcode;
	private String designation;
	private Date entryDate;
	private Date modifyDate;
	private String freight;
	private String supNotes;
	private Date supRemDate;
	private String supReminder;
	private String supRemTime;
	private String remTime;
	private Boolean newLetter;
	private Boolean priceList;
	private Boolean diwaliGift;
	private Boolean greeting;
	private Boolean glassInfo;
	private Boolean introduction;
	private Boolean tag;
	private Boolean printTag;
	private Boolean roadPermit;
	private String entryBy;
	private String modifyBy;

	public CompanyId() {
	}

	public CompanyId(Integer compIdNo, Integer pcode, String initial, String name, Boolean customer, Boolean supplier, Boolean glassSupplier,
			String class_, String type, String phonetype1, String zone, String phone1, String phone2, String phoneType2, String phone3,
			String phone4, String phoneType3, String phone5, String phone6, String phoneType4, String email1, String phoneType5, String email2,
			String phoneType6, String webSite, String address, String city, String state, String pin, String crAddress, String crCity,
			String crState, String crPin, String country, String dealBy, String sdealBy, String staxForm, String cstNo, String lstNo, String eccNo,
			String exRegNo, String location, String fileName, String acstatus, Integer creditLimit, Short creditDays, Boolean active,
			Boolean regular, Boolean confidential, Boolean insurance, Boolean intimation, Boolean showDiscount, Boolean showExcise, Date remDate,
			String reminder, String notes, String supervisorNotes, String productionNotes, String documentationNotes, String printOnInvoice,
			Boolean groupCompany, Integer gcode, Integer spcode, String designation, Date entryDate, Date modifyDate, String freight,
			String supNotes, Date supRemDate, String supReminder, String supRemTime, String remTime, Boolean newLetter, Boolean priceList,
			Boolean diwaliGift, Boolean greeting, Boolean glassInfo, Boolean introduction, Boolean tag, Boolean printTag, Boolean roadPermit,
			String entryBy, String modifyBy) {
		this.compIdNo = compIdNo;
		this.pcode = pcode;
		this.initial = initial;
		this.name = name;
		this.customer = customer;
		this.supplier = supplier;
		this.glassSupplier = glassSupplier;
		this.class_ = class_;
		this.type = type;
		this.phonetype1 = phonetype1;
		this.zone = zone;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.phoneType2 = phoneType2;
		this.phone3 = phone3;
		this.phone4 = phone4;
		this.phoneType3 = phoneType3;
		this.phone5 = phone5;
		this.phone6 = phone6;
		this.phoneType4 = phoneType4;
		this.email1 = email1;
		this.phoneType5 = phoneType5;
		this.email2 = email2;
		this.phoneType6 = phoneType6;
		this.webSite = webSite;
		this.address = address;
		this.city = city;
		this.state = state;
		this.pin = pin;
		this.crAddress = crAddress;
		this.crCity = crCity;
		this.crState = crState;
		this.crPin = crPin;
		this.country = country;
		this.dealBy = dealBy;
		this.sdealBy = sdealBy;
		this.staxForm = staxForm;
		this.cstNo = cstNo;
		this.lstNo = lstNo;
		this.eccNo = eccNo;
		this.exRegNo = exRegNo;
		this.location = location;
		this.fileName = fileName;
		this.acstatus = acstatus;
		this.creditLimit = creditLimit;
		this.creditDays = creditDays;
		this.active = active;
		this.regular = regular;
		this.confidential = confidential;
		this.insurance = insurance;
		this.intimation = intimation;
		this.showDiscount = showDiscount;
		this.showExcise = showExcise;
		this.remDate = remDate;
		this.reminder = reminder;
		this.notes = notes;
		this.supervisorNotes = supervisorNotes;
		this.productionNotes = productionNotes;
		this.documentationNotes = documentationNotes;
		this.printOnInvoice = printOnInvoice;
		this.groupCompany = groupCompany;
		this.gcode = gcode;
		this.spcode = spcode;
		this.designation = designation;
		this.entryDate = entryDate;
		this.modifyDate = modifyDate;
		this.freight = freight;
		this.supNotes = supNotes;
		this.supRemDate = supRemDate;
		this.supReminder = supReminder;
		this.supRemTime = supRemTime;
		this.remTime = remTime;
		this.newLetter = newLetter;
		this.priceList = priceList;
		this.diwaliGift = diwaliGift;
		this.greeting = greeting;
		this.glassInfo = glassInfo;
		this.introduction = introduction;
		this.tag = tag;
		this.printTag = printTag;
		this.roadPermit = roadPermit;
		this.entryBy = entryBy;
		this.modifyBy = modifyBy;
	}

	public Integer getCompIdNo() {
		return this.compIdNo;
	}

	public void setCompIdNo(Integer compIdNo) {
		this.compIdNo = compIdNo;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public String getInitial() {
		return this.initial;
	}

	public void setInitial(String initial) {
		this.initial = initial;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getCustomer() {
		return this.customer;
	}

	public void setCustomer(Boolean customer) {
		this.customer = customer;
	}

	public Boolean getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Boolean supplier) {
		this.supplier = supplier;
	}

	public Boolean getGlassSupplier() {
		return this.glassSupplier;
	}

	public void setGlassSupplier(Boolean glassSupplier) {
		this.glassSupplier = glassSupplier;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPhonetype1() {
		return this.phonetype1;
	}

	public void setPhonetype1(String phonetype1) {
		this.phonetype1 = phonetype1;
	}

	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getPhoneType2() {
		return this.phoneType2;
	}

	public void setPhoneType2(String phoneType2) {
		this.phoneType2 = phoneType2;
	}

	public String getPhone3() {
		return this.phone3;
	}

	public void setPhone3(String phone3) {
		this.phone3 = phone3;
	}

	public String getPhone4() {
		return this.phone4;
	}

	public void setPhone4(String phone4) {
		this.phone4 = phone4;
	}

	public String getPhoneType3() {
		return this.phoneType3;
	}

	public void setPhoneType3(String phoneType3) {
		this.phoneType3 = phoneType3;
	}

	public String getPhone5() {
		return this.phone5;
	}

	public void setPhone5(String phone5) {
		this.phone5 = phone5;
	}

	public String getPhone6() {
		return this.phone6;
	}

	public void setPhone6(String phone6) {
		this.phone6 = phone6;
	}

	public String getPhoneType4() {
		return this.phoneType4;
	}

	public void setPhoneType4(String phoneType4) {
		this.phoneType4 = phoneType4;
	}

	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	public String getPhoneType5() {
		return this.phoneType5;
	}

	public void setPhoneType5(String phoneType5) {
		this.phoneType5 = phoneType5;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getPhoneType6() {
		return this.phoneType6;
	}

	public void setPhoneType6(String phoneType6) {
		this.phoneType6 = phoneType6;
	}

	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getCrAddress() {
		return this.crAddress;
	}

	public void setCrAddress(String crAddress) {
		this.crAddress = crAddress;
	}

	public String getCrCity() {
		return this.crCity;
	}

	public void setCrCity(String crCity) {
		this.crCity = crCity;
	}

	public String getCrState() {
		return this.crState;
	}

	public void setCrState(String crState) {
		this.crState = crState;
	}

	public String getCrPin() {
		return this.crPin;
	}

	public void setCrPin(String crPin) {
		this.crPin = crPin;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getDealBy() {
		return this.dealBy;
	}

	public void setDealBy(String dealBy) {
		this.dealBy = dealBy;
	}

	public String getSdealBy() {
		return this.sdealBy;
	}

	public void setSdealBy(String sdealBy) {
		this.sdealBy = sdealBy;
	}

	public String getStaxForm() {
		return this.staxForm;
	}

	public void setStaxForm(String staxForm) {
		this.staxForm = staxForm;
	}

	public String getCstNo() {
		return this.cstNo;
	}

	public void setCstNo(String cstNo) {
		this.cstNo = cstNo;
	}

	public String getLstNo() {
		return this.lstNo;
	}

	public void setLstNo(String lstNo) {
		this.lstNo = lstNo;
	}

	public String getEccNo() {
		return this.eccNo;
	}

	public void setEccNo(String eccNo) {
		this.eccNo = eccNo;
	}

	public String getExRegNo() {
		return this.exRegNo;
	}

	public void setExRegNo(String exRegNo) {
		this.exRegNo = exRegNo;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getAcstatus() {
		return this.acstatus;
	}

	public void setAcstatus(String acstatus) {
		this.acstatus = acstatus;
	}

	public Integer getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(Integer creditLimit) {
		this.creditLimit = creditLimit;
	}

	public Short getCreditDays() {
		return this.creditDays;
	}

	public void setCreditDays(Short creditDays) {
		this.creditDays = creditDays;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Boolean getRegular() {
		return this.regular;
	}

	public void setRegular(Boolean regular) {
		this.regular = regular;
	}

	public Boolean getConfidential() {
		return this.confidential;
	}

	public void setConfidential(Boolean confidential) {
		this.confidential = confidential;
	}

	public Boolean getInsurance() {
		return this.insurance;
	}

	public void setInsurance(Boolean insurance) {
		this.insurance = insurance;
	}

	public Boolean getIntimation() {
		return this.intimation;
	}

	public void setIntimation(Boolean intimation) {
		this.intimation = intimation;
	}

	public Boolean getShowDiscount() {
		return this.showDiscount;
	}

	public void setShowDiscount(Boolean showDiscount) {
		this.showDiscount = showDiscount;
	}

	public Boolean getShowExcise() {
		return this.showExcise;
	}

	public void setShowExcise(Boolean showExcise) {
		this.showExcise = showExcise;
	}

	public Date getRemDate() {
		return this.remDate;
	}

	public void setRemDate(Date remDate) {
		this.remDate = remDate;
	}

	public String getReminder() {
		return this.reminder;
	}

	public void setReminder(String reminder) {
		this.reminder = reminder;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getSupervisorNotes() {
		return this.supervisorNotes;
	}

	public void setSupervisorNotes(String supervisorNotes) {
		this.supervisorNotes = supervisorNotes;
	}

	public String getProductionNotes() {
		return this.productionNotes;
	}

	public void setProductionNotes(String productionNotes) {
		this.productionNotes = productionNotes;
	}

	public String getDocumentationNotes() {
		return this.documentationNotes;
	}

	public void setDocumentationNotes(String documentationNotes) {
		this.documentationNotes = documentationNotes;
	}

	public String getPrintOnInvoice() {
		return this.printOnInvoice;
	}

	public void setPrintOnInvoice(String printOnInvoice) {
		this.printOnInvoice = printOnInvoice;
	}

	public Boolean getGroupCompany() {
		return this.groupCompany;
	}

	public void setGroupCompany(Boolean groupCompany) {
		this.groupCompany = groupCompany;
	}

	public Integer getGcode() {
		return this.gcode;
	}

	public void setGcode(Integer gcode) {
		this.gcode = gcode;
	}

	public Integer getSpcode() {
		return this.spcode;
	}

	public void setSpcode(Integer spcode) {
		this.spcode = spcode;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getFreight() {
		return this.freight;
	}

	public void setFreight(String freight) {
		this.freight = freight;
	}

	public String getSupNotes() {
		return this.supNotes;
	}

	public void setSupNotes(String supNotes) {
		this.supNotes = supNotes;
	}

	public Date getSupRemDate() {
		return this.supRemDate;
	}

	public void setSupRemDate(Date supRemDate) {
		this.supRemDate = supRemDate;
	}

	public String getSupReminder() {
		return this.supReminder;
	}

	public void setSupReminder(String supReminder) {
		this.supReminder = supReminder;
	}

	public String getSupRemTime() {
		return this.supRemTime;
	}

	public void setSupRemTime(String supRemTime) {
		this.supRemTime = supRemTime;
	}

	public String getRemTime() {
		return this.remTime;
	}

	public void setRemTime(String remTime) {
		this.remTime = remTime;
	}

	public Boolean getNewLetter() {
		return this.newLetter;
	}

	public void setNewLetter(Boolean newLetter) {
		this.newLetter = newLetter;
	}

	public Boolean getPriceList() {
		return this.priceList;
	}

	public void setPriceList(Boolean priceList) {
		this.priceList = priceList;
	}

	public Boolean getDiwaliGift() {
		return this.diwaliGift;
	}

	public void setDiwaliGift(Boolean diwaliGift) {
		this.diwaliGift = diwaliGift;
	}

	public Boolean getGreeting() {
		return this.greeting;
	}

	public void setGreeting(Boolean greeting) {
		this.greeting = greeting;
	}

	public Boolean getGlassInfo() {
		return this.glassInfo;
	}

	public void setGlassInfo(Boolean glassInfo) {
		this.glassInfo = glassInfo;
	}

	public Boolean getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(Boolean introduction) {
		this.introduction = introduction;
	}

	public Boolean getTag() {
		return this.tag;
	}

	public void setTag(Boolean tag) {
		this.tag = tag;
	}

	public Boolean getPrintTag() {
		return this.printTag;
	}

	public void setPrintTag(Boolean printTag) {
		this.printTag = printTag;
	}

	public Boolean getRoadPermit() {
		return this.roadPermit;
	}

	public void setRoadPermit(Boolean roadPermit) {
		this.roadPermit = roadPermit;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompanyId))
			return false;
		CompanyId castOther = (CompanyId) other;

		return ((this.getCompIdNo() == castOther.getCompIdNo()) || (this.getCompIdNo() != null && castOther.getCompIdNo() != null && this
				.getCompIdNo().equals(castOther.getCompIdNo())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getInitial() == castOther.getInitial()) || (this.getInitial() != null && castOther.getInitial() != null && this
						.getInitial().equals(castOther.getInitial())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(
						castOther.getName())))
				&& ((this.getCustomer() == castOther.getCustomer()) || (this.getCustomer() != null && castOther.getCustomer() != null && this
						.getCustomer().equals(castOther.getCustomer())))
				&& ((this.getSupplier() == castOther.getSupplier()) || (this.getSupplier() != null && castOther.getSupplier() != null && this
						.getSupplier().equals(castOther.getSupplier())))
				&& ((this.getGlassSupplier() == castOther.getGlassSupplier()) || (this.getGlassSupplier() != null
						&& castOther.getGlassSupplier() != null && this.getGlassSupplier().equals(castOther.getGlassSupplier())))
				&& ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null && castOther.getClass_() != null && this.getClass_()
						.equals(castOther.getClass_())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this.getType().equals(
						castOther.getType())))
				&& ((this.getPhonetype1() == castOther.getPhonetype1()) || (this.getPhonetype1() != null && castOther.getPhonetype1() != null && this
						.getPhonetype1().equals(castOther.getPhonetype1())))
				&& ((this.getZone() == castOther.getZone()) || (this.getZone() != null && castOther.getZone() != null && this.getZone().equals(
						castOther.getZone())))
				&& ((this.getPhone1() == castOther.getPhone1()) || (this.getPhone1() != null && castOther.getPhone1() != null && this.getPhone1()
						.equals(castOther.getPhone1())))
				&& ((this.getPhone2() == castOther.getPhone2()) || (this.getPhone2() != null && castOther.getPhone2() != null && this.getPhone2()
						.equals(castOther.getPhone2())))
				&& ((this.getPhoneType2() == castOther.getPhoneType2()) || (this.getPhoneType2() != null && castOther.getPhoneType2() != null && this
						.getPhoneType2().equals(castOther.getPhoneType2())))
				&& ((this.getPhone3() == castOther.getPhone3()) || (this.getPhone3() != null && castOther.getPhone3() != null && this.getPhone3()
						.equals(castOther.getPhone3())))
				&& ((this.getPhone4() == castOther.getPhone4()) || (this.getPhone4() != null && castOther.getPhone4() != null && this.getPhone4()
						.equals(castOther.getPhone4())))
				&& ((this.getPhoneType3() == castOther.getPhoneType3()) || (this.getPhoneType3() != null && castOther.getPhoneType3() != null && this
						.getPhoneType3().equals(castOther.getPhoneType3())))
				&& ((this.getPhone5() == castOther.getPhone5()) || (this.getPhone5() != null && castOther.getPhone5() != null && this.getPhone5()
						.equals(castOther.getPhone5())))
				&& ((this.getPhone6() == castOther.getPhone6()) || (this.getPhone6() != null && castOther.getPhone6() != null && this.getPhone6()
						.equals(castOther.getPhone6())))
				&& ((this.getPhoneType4() == castOther.getPhoneType4()) || (this.getPhoneType4() != null && castOther.getPhoneType4() != null && this
						.getPhoneType4().equals(castOther.getPhoneType4())))
				&& ((this.getEmail1() == castOther.getEmail1()) || (this.getEmail1() != null && castOther.getEmail1() != null && this.getEmail1()
						.equals(castOther.getEmail1())))
				&& ((this.getPhoneType5() == castOther.getPhoneType5()) || (this.getPhoneType5() != null && castOther.getPhoneType5() != null && this
						.getPhoneType5().equals(castOther.getPhoneType5())))
				&& ((this.getEmail2() == castOther.getEmail2()) || (this.getEmail2() != null && castOther.getEmail2() != null && this.getEmail2()
						.equals(castOther.getEmail2())))
				&& ((this.getPhoneType6() == castOther.getPhoneType6()) || (this.getPhoneType6() != null && castOther.getPhoneType6() != null && this
						.getPhoneType6().equals(castOther.getPhoneType6())))
				&& ((this.getWebSite() == castOther.getWebSite()) || (this.getWebSite() != null && castOther.getWebSite() != null && this
						.getWebSite().equals(castOther.getWebSite())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null && castOther.getAddress() != null && this
						.getAddress().equals(castOther.getAddress())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null && this.getCity().equals(
						castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null && castOther.getState() != null && this.getState().equals(
						castOther.getState())))
				&& ((this.getPin() == castOther.getPin()) || (this.getPin() != null && castOther.getPin() != null && this.getPin().equals(
						castOther.getPin())))
				&& ((this.getCrAddress() == castOther.getCrAddress()) || (this.getCrAddress() != null && castOther.getCrAddress() != null && this
						.getCrAddress().equals(castOther.getCrAddress())))
				&& ((this.getCrCity() == castOther.getCrCity()) || (this.getCrCity() != null && castOther.getCrCity() != null && this.getCrCity()
						.equals(castOther.getCrCity())))
				&& ((this.getCrState() == castOther.getCrState()) || (this.getCrState() != null && castOther.getCrState() != null && this
						.getCrState().equals(castOther.getCrState())))
				&& ((this.getCrPin() == castOther.getCrPin()) || (this.getCrPin() != null && castOther.getCrPin() != null && this.getCrPin().equals(
						castOther.getCrPin())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getDealBy() == castOther.getDealBy()) || (this.getDealBy() != null && castOther.getDealBy() != null && this.getDealBy()
						.equals(castOther.getDealBy())))
				&& ((this.getSdealBy() == castOther.getSdealBy()) || (this.getSdealBy() != null && castOther.getSdealBy() != null && this
						.getSdealBy().equals(castOther.getSdealBy())))
				&& ((this.getStaxForm() == castOther.getStaxForm()) || (this.getStaxForm() != null && castOther.getStaxForm() != null && this
						.getStaxForm().equals(castOther.getStaxForm())))
				&& ((this.getCstNo() == castOther.getCstNo()) || (this.getCstNo() != null && castOther.getCstNo() != null && this.getCstNo().equals(
						castOther.getCstNo())))
				&& ((this.getLstNo() == castOther.getLstNo()) || (this.getLstNo() != null && castOther.getLstNo() != null && this.getLstNo().equals(
						castOther.getLstNo())))
				&& ((this.getEccNo() == castOther.getEccNo()) || (this.getEccNo() != null && castOther.getEccNo() != null && this.getEccNo().equals(
						castOther.getEccNo())))
				&& ((this.getExRegNo() == castOther.getExRegNo()) || (this.getExRegNo() != null && castOther.getExRegNo() != null && this
						.getExRegNo().equals(castOther.getExRegNo())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null && castOther.getLocation() != null && this
						.getLocation().equals(castOther.getLocation())))
				&& ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null && castOther.getFileName() != null && this
						.getFileName().equals(castOther.getFileName())))
				&& ((this.getAcstatus() == castOther.getAcstatus()) || (this.getAcstatus() != null && castOther.getAcstatus() != null && this
						.getAcstatus().equals(castOther.getAcstatus())))
				&& ((this.getCreditLimit() == castOther.getCreditLimit()) || (this.getCreditLimit() != null && castOther.getCreditLimit() != null && this
						.getCreditLimit().equals(castOther.getCreditLimit())))
				&& ((this.getCreditDays() == castOther.getCreditDays()) || (this.getCreditDays() != null && castOther.getCreditDays() != null && this
						.getCreditDays().equals(castOther.getCreditDays())))
				&& ((this.getActive() == castOther.getActive()) || (this.getActive() != null && castOther.getActive() != null && this.getActive()
						.equals(castOther.getActive())))
				&& ((this.getRegular() == castOther.getRegular()) || (this.getRegular() != null && castOther.getRegular() != null && this
						.getRegular().equals(castOther.getRegular())))
				&& ((this.getConfidential() == castOther.getConfidential()) || (this.getConfidential() != null && castOther.getConfidential() != null && this
						.getConfidential().equals(castOther.getConfidential())))
				&& ((this.getInsurance() == castOther.getInsurance()) || (this.getInsurance() != null && castOther.getInsurance() != null && this
						.getInsurance().equals(castOther.getInsurance())))
				&& ((this.getIntimation() == castOther.getIntimation()) || (this.getIntimation() != null && castOther.getIntimation() != null && this
						.getIntimation().equals(castOther.getIntimation())))
				&& ((this.getShowDiscount() == castOther.getShowDiscount()) || (this.getShowDiscount() != null && castOther.getShowDiscount() != null && this
						.getShowDiscount().equals(castOther.getShowDiscount())))
				&& ((this.getShowExcise() == castOther.getShowExcise()) || (this.getShowExcise() != null && castOther.getShowExcise() != null && this
						.getShowExcise().equals(castOther.getShowExcise())))
				&& ((this.getRemDate() == castOther.getRemDate()) || (this.getRemDate() != null && castOther.getRemDate() != null && this
						.getRemDate().equals(castOther.getRemDate())))
				&& ((this.getReminder() == castOther.getReminder()) || (this.getReminder() != null && castOther.getReminder() != null && this
						.getReminder().equals(castOther.getReminder())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null && castOther.getNotes() != null && this.getNotes().equals(
						castOther.getNotes())))
				&& ((this.getSupervisorNotes() == castOther.getSupervisorNotes()) || (this.getSupervisorNotes() != null
						&& castOther.getSupervisorNotes() != null && this.getSupervisorNotes().equals(castOther.getSupervisorNotes())))
				&& ((this.getProductionNotes() == castOther.getProductionNotes()) || (this.getProductionNotes() != null
						&& castOther.getProductionNotes() != null && this.getProductionNotes().equals(castOther.getProductionNotes())))
				&& ((this.getDocumentationNotes() == castOther.getDocumentationNotes()) || (this.getDocumentationNotes() != null
						&& castOther.getDocumentationNotes() != null && this.getDocumentationNotes().equals(castOther.getDocumentationNotes())))
				&& ((this.getPrintOnInvoice() == castOther.getPrintOnInvoice()) || (this.getPrintOnInvoice() != null
						&& castOther.getPrintOnInvoice() != null && this.getPrintOnInvoice().equals(castOther.getPrintOnInvoice())))
				&& ((this.getGroupCompany() == castOther.getGroupCompany()) || (this.getGroupCompany() != null && castOther.getGroupCompany() != null && this
						.getGroupCompany().equals(castOther.getGroupCompany())))
				&& ((this.getGcode() == castOther.getGcode()) || (this.getGcode() != null && castOther.getGcode() != null && this.getGcode().equals(
						castOther.getGcode())))
				&& ((this.getSpcode() == castOther.getSpcode()) || (this.getSpcode() != null && castOther.getSpcode() != null && this.getSpcode()
						.equals(castOther.getSpcode())))
				&& ((this.getDesignation() == castOther.getDesignation()) || (this.getDesignation() != null && castOther.getDesignation() != null && this
						.getDesignation().equals(castOther.getDesignation())))
				&& ((this.getEntryDate() == castOther.getEntryDate()) || (this.getEntryDate() != null && castOther.getEntryDate() != null && this
						.getEntryDate().equals(castOther.getEntryDate())))
				&& ((this.getModifyDate() == castOther.getModifyDate()) || (this.getModifyDate() != null && castOther.getModifyDate() != null && this
						.getModifyDate().equals(castOther.getModifyDate())))
				&& ((this.getFreight() == castOther.getFreight()) || (this.getFreight() != null && castOther.getFreight() != null && this
						.getFreight().equals(castOther.getFreight())))
				&& ((this.getSupNotes() == castOther.getSupNotes()) || (this.getSupNotes() != null && castOther.getSupNotes() != null && this
						.getSupNotes().equals(castOther.getSupNotes())))
				&& ((this.getSupRemDate() == castOther.getSupRemDate()) || (this.getSupRemDate() != null && castOther.getSupRemDate() != null && this
						.getSupRemDate().equals(castOther.getSupRemDate())))
				&& ((this.getSupReminder() == castOther.getSupReminder()) || (this.getSupReminder() != null && castOther.getSupReminder() != null && this
						.getSupReminder().equals(castOther.getSupReminder())))
				&& ((this.getSupRemTime() == castOther.getSupRemTime()) || (this.getSupRemTime() != null && castOther.getSupRemTime() != null && this
						.getSupRemTime().equals(castOther.getSupRemTime())))
				&& ((this.getRemTime() == castOther.getRemTime()) || (this.getRemTime() != null && castOther.getRemTime() != null && this
						.getRemTime().equals(castOther.getRemTime())))
				&& ((this.getNewLetter() == castOther.getNewLetter()) || (this.getNewLetter() != null && castOther.getNewLetter() != null && this
						.getNewLetter().equals(castOther.getNewLetter())))
				&& ((this.getPriceList() == castOther.getPriceList()) || (this.getPriceList() != null && castOther.getPriceList() != null && this
						.getPriceList().equals(castOther.getPriceList())))
				&& ((this.getDiwaliGift() == castOther.getDiwaliGift()) || (this.getDiwaliGift() != null && castOther.getDiwaliGift() != null && this
						.getDiwaliGift().equals(castOther.getDiwaliGift())))
				&& ((this.getGreeting() == castOther.getGreeting()) || (this.getGreeting() != null && castOther.getGreeting() != null && this
						.getGreeting().equals(castOther.getGreeting())))
				&& ((this.getGlassInfo() == castOther.getGlassInfo()) || (this.getGlassInfo() != null && castOther.getGlassInfo() != null && this
						.getGlassInfo().equals(castOther.getGlassInfo())))
				&& ((this.getIntroduction() == castOther.getIntroduction()) || (this.getIntroduction() != null && castOther.getIntroduction() != null && this
						.getIntroduction().equals(castOther.getIntroduction())))
				&& ((this.getTag() == castOther.getTag()) || (this.getTag() != null && castOther.getTag() != null && this.getTag().equals(
						castOther.getTag())))
				&& ((this.getPrintTag() == castOther.getPrintTag()) || (this.getPrintTag() != null && castOther.getPrintTag() != null && this
						.getPrintTag().equals(castOther.getPrintTag())))
				&& ((this.getRoadPermit() == castOther.getRoadPermit()) || (this.getRoadPermit() != null && castOther.getRoadPermit() != null && this
						.getRoadPermit().equals(castOther.getRoadPermit())))
				&& ((this.getEntryBy() == castOther.getEntryBy()) || (this.getEntryBy() != null && castOther.getEntryBy() != null && this
						.getEntryBy().equals(castOther.getEntryBy())))
				&& ((this.getModifyBy() == castOther.getModifyBy()) || (this.getModifyBy() != null && castOther.getModifyBy() != null && this
						.getModifyBy().equals(castOther.getModifyBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompIdNo() == null ? 0 : this.getCompIdNo().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getInitial() == null ? 0 : this.getInitial().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getCustomer() == null ? 0 : this.getCustomer().hashCode());
		result = 37 * result + (getSupplier() == null ? 0 : this.getSupplier().hashCode());
		result = 37 * result + (getGlassSupplier() == null ? 0 : this.getGlassSupplier().hashCode());
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getPhonetype1() == null ? 0 : this.getPhonetype1().hashCode());
		result = 37 * result + (getZone() == null ? 0 : this.getZone().hashCode());
		result = 37 * result + (getPhone1() == null ? 0 : this.getPhone1().hashCode());
		result = 37 * result + (getPhone2() == null ? 0 : this.getPhone2().hashCode());
		result = 37 * result + (getPhoneType2() == null ? 0 : this.getPhoneType2().hashCode());
		result = 37 * result + (getPhone3() == null ? 0 : this.getPhone3().hashCode());
		result = 37 * result + (getPhone4() == null ? 0 : this.getPhone4().hashCode());
		result = 37 * result + (getPhoneType3() == null ? 0 : this.getPhoneType3().hashCode());
		result = 37 * result + (getPhone5() == null ? 0 : this.getPhone5().hashCode());
		result = 37 * result + (getPhone6() == null ? 0 : this.getPhone6().hashCode());
		result = 37 * result + (getPhoneType4() == null ? 0 : this.getPhoneType4().hashCode());
		result = 37 * result + (getEmail1() == null ? 0 : this.getEmail1().hashCode());
		result = 37 * result + (getPhoneType5() == null ? 0 : this.getPhoneType5().hashCode());
		result = 37 * result + (getEmail2() == null ? 0 : this.getEmail2().hashCode());
		result = 37 * result + (getPhoneType6() == null ? 0 : this.getPhoneType6().hashCode());
		result = 37 * result + (getWebSite() == null ? 0 : this.getWebSite().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getPin() == null ? 0 : this.getPin().hashCode());
		result = 37 * result + (getCrAddress() == null ? 0 : this.getCrAddress().hashCode());
		result = 37 * result + (getCrCity() == null ? 0 : this.getCrCity().hashCode());
		result = 37 * result + (getCrState() == null ? 0 : this.getCrState().hashCode());
		result = 37 * result + (getCrPin() == null ? 0 : this.getCrPin().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getDealBy() == null ? 0 : this.getDealBy().hashCode());
		result = 37 * result + (getSdealBy() == null ? 0 : this.getSdealBy().hashCode());
		result = 37 * result + (getStaxForm() == null ? 0 : this.getStaxForm().hashCode());
		result = 37 * result + (getCstNo() == null ? 0 : this.getCstNo().hashCode());
		result = 37 * result + (getLstNo() == null ? 0 : this.getLstNo().hashCode());
		result = 37 * result + (getEccNo() == null ? 0 : this.getEccNo().hashCode());
		result = 37 * result + (getExRegNo() == null ? 0 : this.getExRegNo().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result + (getAcstatus() == null ? 0 : this.getAcstatus().hashCode());
		result = 37 * result + (getCreditLimit() == null ? 0 : this.getCreditLimit().hashCode());
		result = 37 * result + (getCreditDays() == null ? 0 : this.getCreditDays().hashCode());
		result = 37 * result + (getActive() == null ? 0 : this.getActive().hashCode());
		result = 37 * result + (getRegular() == null ? 0 : this.getRegular().hashCode());
		result = 37 * result + (getConfidential() == null ? 0 : this.getConfidential().hashCode());
		result = 37 * result + (getInsurance() == null ? 0 : this.getInsurance().hashCode());
		result = 37 * result + (getIntimation() == null ? 0 : this.getIntimation().hashCode());
		result = 37 * result + (getShowDiscount() == null ? 0 : this.getShowDiscount().hashCode());
		result = 37 * result + (getShowExcise() == null ? 0 : this.getShowExcise().hashCode());
		result = 37 * result + (getRemDate() == null ? 0 : this.getRemDate().hashCode());
		result = 37 * result + (getReminder() == null ? 0 : this.getReminder().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result + (getSupervisorNotes() == null ? 0 : this.getSupervisorNotes().hashCode());
		result = 37 * result + (getProductionNotes() == null ? 0 : this.getProductionNotes().hashCode());
		result = 37 * result + (getDocumentationNotes() == null ? 0 : this.getDocumentationNotes().hashCode());
		result = 37 * result + (getPrintOnInvoice() == null ? 0 : this.getPrintOnInvoice().hashCode());
		result = 37 * result + (getGroupCompany() == null ? 0 : this.getGroupCompany().hashCode());
		result = 37 * result + (getGcode() == null ? 0 : this.getGcode().hashCode());
		result = 37 * result + (getSpcode() == null ? 0 : this.getSpcode().hashCode());
		result = 37 * result + (getDesignation() == null ? 0 : this.getDesignation().hashCode());
		result = 37 * result + (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		result = 37 * result + (getModifyDate() == null ? 0 : this.getModifyDate().hashCode());
		result = 37 * result + (getFreight() == null ? 0 : this.getFreight().hashCode());
		result = 37 * result + (getSupNotes() == null ? 0 : this.getSupNotes().hashCode());
		result = 37 * result + (getSupRemDate() == null ? 0 : this.getSupRemDate().hashCode());
		result = 37 * result + (getSupReminder() == null ? 0 : this.getSupReminder().hashCode());
		result = 37 * result + (getSupRemTime() == null ? 0 : this.getSupRemTime().hashCode());
		result = 37 * result + (getRemTime() == null ? 0 : this.getRemTime().hashCode());
		result = 37 * result + (getNewLetter() == null ? 0 : this.getNewLetter().hashCode());
		result = 37 * result + (getPriceList() == null ? 0 : this.getPriceList().hashCode());
		result = 37 * result + (getDiwaliGift() == null ? 0 : this.getDiwaliGift().hashCode());
		result = 37 * result + (getGreeting() == null ? 0 : this.getGreeting().hashCode());
		result = 37 * result + (getGlassInfo() == null ? 0 : this.getGlassInfo().hashCode());
		result = 37 * result + (getIntroduction() == null ? 0 : this.getIntroduction().hashCode());
		result = 37 * result + (getTag() == null ? 0 : this.getTag().hashCode());
		result = 37 * result + (getPrintTag() == null ? 0 : this.getPrintTag().hashCode());
		result = 37 * result + (getRoadPermit() == null ? 0 : this.getRoadPermit().hashCode());
		result = 37 * result + (getEntryBy() == null ? 0 : this.getEntryBy().hashCode());
		result = 37 * result + (getModifyBy() == null ? 0 : this.getModifyBy().hashCode());
		return result;
	}

}
