package com.sd.app.bean.company;

// Generated Nov 22, 2014 12:49:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompanyTables generated by hbm2java
 */
public class CompanyTables implements java.io.Serializable {

	private CompanyTablesId id;

	public CompanyTables() {
	}

	public CompanyTables(CompanyTablesId id) {
		this.id = id;
	}

	public CompanyTablesId getId() {
		return this.id;
	}

	public void setId(CompanyTablesId id) {
		this.id = id;
	}

}
