package com.sd.app.bean.rawstock;

// Generated Nov 22, 2014 1:16:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * JobWorkIssue generated by hbm2java
 */
public class JobWorkIssue implements java.io.Serializable {

	private JobWorkIssueId id;

	public JobWorkIssue() {
	}

	public JobWorkIssue(JobWorkIssueId id) {
		this.id = id;
	}

	public JobWorkIssueId getId() {
		return this.id;
	}

	public void setId(JobWorkIssueId id) {
		this.id = id;
	}

}
