package com.sd.app.bean.rawstock;

// Generated Nov 22, 2014 1:16:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JobWorkIssueId generated by hbm2java
 */
public class JobWorkIssueId implements java.io.Serializable {

	private String coCode;
	private Integer issueNo;
	private Date issueDate;
	private Float thick;
	private String icode;
	private Short width;
	private Short height;
	private Short sheets;
	private String issueTo;
	private Integer jobIdNo;
	private String remarks;
	private Short damaged;
	private Short reserved;
	private Date entryDate;
	private Date entryTime;
	private Integer pcode;
	private Integer stockIdNo;
	private Integer issueIdNo;
	private Integer controlBy;
	private Integer issueBy;

	public JobWorkIssueId() {
	}

	public JobWorkIssueId(String coCode, Integer issueNo, Date issueDate, Float thick, String icode, Short width, Short height, Short sheets,
			String issueTo, Integer jobIdNo, String remarks, Short damaged, Short reserved, Date entryDate, Date entryTime, Integer pcode,
			Integer stockIdNo, Integer issueIdNo, Integer controlBy, Integer issueBy) {
		this.coCode = coCode;
		this.issueNo = issueNo;
		this.issueDate = issueDate;
		this.thick = thick;
		this.icode = icode;
		this.width = width;
		this.height = height;
		this.sheets = sheets;
		this.issueTo = issueTo;
		this.jobIdNo = jobIdNo;
		this.remarks = remarks;
		this.damaged = damaged;
		this.reserved = reserved;
		this.entryDate = entryDate;
		this.entryTime = entryTime;
		this.pcode = pcode;
		this.stockIdNo = stockIdNo;
		this.issueIdNo = issueIdNo;
		this.controlBy = controlBy;
		this.issueBy = issueBy;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(Integer issueNo) {
		this.issueNo = issueNo;
	}

	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public Short getWidth() {
		return this.width;
	}

	public void setWidth(Short width) {
		this.width = width;
	}

	public Short getHeight() {
		return this.height;
	}

	public void setHeight(Short height) {
		this.height = height;
	}

	public Short getSheets() {
		return this.sheets;
	}

	public void setSheets(Short sheets) {
		this.sheets = sheets;
	}

	public String getIssueTo() {
		return this.issueTo;
	}

	public void setIssueTo(String issueTo) {
		this.issueTo = issueTo;
	}

	public Integer getJobIdNo() {
		return this.jobIdNo;
	}

	public void setJobIdNo(Integer jobIdNo) {
		this.jobIdNo = jobIdNo;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Short getDamaged() {
		return this.damaged;
	}

	public void setDamaged(Short damaged) {
		this.damaged = damaged;
	}

	public Short getReserved() {
		return this.reserved;
	}

	public void setReserved(Short reserved) {
		this.reserved = reserved;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public Integer getStockIdNo() {
		return this.stockIdNo;
	}

	public void setStockIdNo(Integer stockIdNo) {
		this.stockIdNo = stockIdNo;
	}

	public Integer getIssueIdNo() {
		return this.issueIdNo;
	}

	public void setIssueIdNo(Integer issueIdNo) {
		this.issueIdNo = issueIdNo;
	}

	public Integer getControlBy() {
		return this.controlBy;
	}

	public void setControlBy(Integer controlBy) {
		this.controlBy = controlBy;
	}

	public Integer getIssueBy() {
		return this.issueBy;
	}

	public void setIssueBy(Integer issueBy) {
		this.issueBy = issueBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobWorkIssueId))
			return false;
		JobWorkIssueId castOther = (JobWorkIssueId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getIssueNo() == castOther.getIssueNo()) || (this.getIssueNo() != null && castOther.getIssueNo() != null && this
						.getIssueNo().equals(castOther.getIssueNo())))
				&& ((this.getIssueDate() == castOther.getIssueDate()) || (this.getIssueDate() != null && castOther.getIssueDate() != null && this
						.getIssueDate().equals(castOther.getIssueDate())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getSheets() == castOther.getSheets()) || (this.getSheets() != null && castOther.getSheets() != null && this.getSheets()
						.equals(castOther.getSheets())))
				&& ((this.getIssueTo() == castOther.getIssueTo()) || (this.getIssueTo() != null && castOther.getIssueTo() != null && this
						.getIssueTo().equals(castOther.getIssueTo())))
				&& ((this.getJobIdNo() == castOther.getJobIdNo()) || (this.getJobIdNo() != null && castOther.getJobIdNo() != null && this
						.getJobIdNo().equals(castOther.getJobIdNo())))
				&& ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null && castOther.getRemarks() != null && this
						.getRemarks().equals(castOther.getRemarks())))
				&& ((this.getDamaged() == castOther.getDamaged()) || (this.getDamaged() != null && castOther.getDamaged() != null && this
						.getDamaged().equals(castOther.getDamaged())))
				&& ((this.getReserved() == castOther.getReserved()) || (this.getReserved() != null && castOther.getReserved() != null && this
						.getReserved().equals(castOther.getReserved())))
				&& ((this.getEntryDate() == castOther.getEntryDate()) || (this.getEntryDate() != null && castOther.getEntryDate() != null && this
						.getEntryDate().equals(castOther.getEntryDate())))
				&& ((this.getEntryTime() == castOther.getEntryTime()) || (this.getEntryTime() != null && castOther.getEntryTime() != null && this
						.getEntryTime().equals(castOther.getEntryTime())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getStockIdNo() == castOther.getStockIdNo()) || (this.getStockIdNo() != null && castOther.getStockIdNo() != null && this
						.getStockIdNo().equals(castOther.getStockIdNo())))
				&& ((this.getIssueIdNo() == castOther.getIssueIdNo()) || (this.getIssueIdNo() != null && castOther.getIssueIdNo() != null && this
						.getIssueIdNo().equals(castOther.getIssueIdNo())))
				&& ((this.getControlBy() == castOther.getControlBy()) || (this.getControlBy() != null && castOther.getControlBy() != null && this
						.getControlBy().equals(castOther.getControlBy())))
				&& ((this.getIssueBy() == castOther.getIssueBy()) || (this.getIssueBy() != null && castOther.getIssueBy() != null && this
						.getIssueBy().equals(castOther.getIssueBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getIssueNo() == null ? 0 : this.getIssueNo().hashCode());
		result = 37 * result + (getIssueDate() == null ? 0 : this.getIssueDate().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getSheets() == null ? 0 : this.getSheets().hashCode());
		result = 37 * result + (getIssueTo() == null ? 0 : this.getIssueTo().hashCode());
		result = 37 * result + (getJobIdNo() == null ? 0 : this.getJobIdNo().hashCode());
		result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
		result = 37 * result + (getDamaged() == null ? 0 : this.getDamaged().hashCode());
		result = 37 * result + (getReserved() == null ? 0 : this.getReserved().hashCode());
		result = 37 * result + (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		result = 37 * result + (getEntryTime() == null ? 0 : this.getEntryTime().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getStockIdNo() == null ? 0 : this.getStockIdNo().hashCode());
		result = 37 * result + (getIssueIdNo() == null ? 0 : this.getIssueIdNo().hashCode());
		result = 37 * result + (getControlBy() == null ? 0 : this.getControlBy().hashCode());
		result = 37 * result + (getIssueBy() == null ? 0 : this.getIssueBy().hashCode());
		return result;
	}

}
