package com.sd.app.bean.rawstock;

// Generated Nov 22, 2014 1:16:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * JobWorkReceipts generated by hbm2java
 */
public class JobWorkReceipts implements java.io.Serializable {

	private JobWorkReceiptsId id;

	public JobWorkReceipts() {
	}

	public JobWorkReceipts(JobWorkReceiptsId id) {
		this.id = id;
	}

	public JobWorkReceiptsId getId() {
		return this.id;
	}

	public void setId(JobWorkReceiptsId id) {
		this.id = id;
	}

}
