package com.sd.app.bean.rawstock;

// Generated Nov 22, 2014 1:16:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * RawIssue generated by hbm2java
 */
public class RawIssue implements java.io.Serializable {

	private RawIssueId id;

	public RawIssue() {
	}

	public RawIssue(RawIssueId id) {
		this.id = id;
	}

	public RawIssueId getId() {
		return this.id;
	}

	public void setId(RawIssueId id) {
		this.id = id;
	}

}
