package com.sd.app.bean.rawstock;

// Generated Nov 22, 2014 1:16:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * RawReserved generated by hbm2java
 */
public class RawReserved implements java.io.Serializable {

	private RawReservedId id;

	public RawReserved() {
	}

	public RawReserved(RawReservedId id) {
		this.id = id;
	}

	public RawReservedId getId() {
		return this.id;
	}

	public void setId(RawReservedId id) {
		this.id = id;
	}

}
