package com.sd.app.bean.rawstock;

// Generated Nov 22, 2014 1:16:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RvmasterGlassId generated by hbm2java
 */
public class RvmasterGlassId implements java.io.Serializable {

	private String coCode;
	private Short rvNo;
	private Date rvDate;
	private Integer pcode;
	private String vehNo;
	private String grNo;
	private String transport;
	private String billNo;
	private Date billDate;
	private Float basicAmt;
	private Float staxAmt;
	private Float insurAmt;
	private Float excAmt;
	private Float freiamt;
	private Float discPer;
	private Float discAmt;
	private Float othAdd;
	private Float othDed;
	private Float recAmt;
	private Float paidAmt;
	private String chqNo;
	private Date chqDate;
	private Float thDiscPer;
	private Float billAmt;
	private String notes;
	private Boolean final_;
	private Integer prepBy;
	private Float ecessAmt;
	private String form31no;
	private Float serTaxOnFreight;
	private Float ecessOnSerTax;

	public RvmasterGlassId() {
	}

	public RvmasterGlassId(String coCode, Short rvNo, Date rvDate, Integer pcode, String vehNo, String grNo, String transport, String billNo,
			Date billDate, Float basicAmt, Float staxAmt, Float insurAmt, Float excAmt, Float freiamt, Float discPer, Float discAmt, Float othAdd,
			Float othDed, Float recAmt, Float paidAmt, String chqNo, Date chqDate, Float thDiscPer, Float billAmt, String notes, Boolean final_,
			Integer prepBy, Float ecessAmt, String form31no, Float serTaxOnFreight, Float ecessOnSerTax) {
		this.coCode = coCode;
		this.rvNo = rvNo;
		this.rvDate = rvDate;
		this.pcode = pcode;
		this.vehNo = vehNo;
		this.grNo = grNo;
		this.transport = transport;
		this.billNo = billNo;
		this.billDate = billDate;
		this.basicAmt = basicAmt;
		this.staxAmt = staxAmt;
		this.insurAmt = insurAmt;
		this.excAmt = excAmt;
		this.freiamt = freiamt;
		this.discPer = discPer;
		this.discAmt = discAmt;
		this.othAdd = othAdd;
		this.othDed = othDed;
		this.recAmt = recAmt;
		this.paidAmt = paidAmt;
		this.chqNo = chqNo;
		this.chqDate = chqDate;
		this.thDiscPer = thDiscPer;
		this.billAmt = billAmt;
		this.notes = notes;
		this.final_ = final_;
		this.prepBy = prepBy;
		this.ecessAmt = ecessAmt;
		this.form31no = form31no;
		this.serTaxOnFreight = serTaxOnFreight;
		this.ecessOnSerTax = ecessOnSerTax;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Short getRvNo() {
		return this.rvNo;
	}

	public void setRvNo(Short rvNo) {
		this.rvNo = rvNo;
	}

	public Date getRvDate() {
		return this.rvDate;
	}

	public void setRvDate(Date rvDate) {
		this.rvDate = rvDate;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public String getVehNo() {
		return this.vehNo;
	}

	public void setVehNo(String vehNo) {
		this.vehNo = vehNo;
	}

	public String getGrNo() {
		return this.grNo;
	}

	public void setGrNo(String grNo) {
		this.grNo = grNo;
	}

	public String getTransport() {
		return this.transport;
	}

	public void setTransport(String transport) {
		this.transport = transport;
	}

	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	public Float getBasicAmt() {
		return this.basicAmt;
	}

	public void setBasicAmt(Float basicAmt) {
		this.basicAmt = basicAmt;
	}

	public Float getStaxAmt() {
		return this.staxAmt;
	}

	public void setStaxAmt(Float staxAmt) {
		this.staxAmt = staxAmt;
	}

	public Float getInsurAmt() {
		return this.insurAmt;
	}

	public void setInsurAmt(Float insurAmt) {
		this.insurAmt = insurAmt;
	}

	public Float getExcAmt() {
		return this.excAmt;
	}

	public void setExcAmt(Float excAmt) {
		this.excAmt = excAmt;
	}

	public Float getFreiamt() {
		return this.freiamt;
	}

	public void setFreiamt(Float freiamt) {
		this.freiamt = freiamt;
	}

	public Float getDiscPer() {
		return this.discPer;
	}

	public void setDiscPer(Float discPer) {
		this.discPer = discPer;
	}

	public Float getDiscAmt() {
		return this.discAmt;
	}

	public void setDiscAmt(Float discAmt) {
		this.discAmt = discAmt;
	}

	public Float getOthAdd() {
		return this.othAdd;
	}

	public void setOthAdd(Float othAdd) {
		this.othAdd = othAdd;
	}

	public Float getOthDed() {
		return this.othDed;
	}

	public void setOthDed(Float othDed) {
		this.othDed = othDed;
	}

	public Float getRecAmt() {
		return this.recAmt;
	}

	public void setRecAmt(Float recAmt) {
		this.recAmt = recAmt;
	}

	public Float getPaidAmt() {
		return this.paidAmt;
	}

	public void setPaidAmt(Float paidAmt) {
		this.paidAmt = paidAmt;
	}

	public String getChqNo() {
		return this.chqNo;
	}

	public void setChqNo(String chqNo) {
		this.chqNo = chqNo;
	}

	public Date getChqDate() {
		return this.chqDate;
	}

	public void setChqDate(Date chqDate) {
		this.chqDate = chqDate;
	}

	public Float getThDiscPer() {
		return this.thDiscPer;
	}

	public void setThDiscPer(Float thDiscPer) {
		this.thDiscPer = thDiscPer;
	}

	public Float getBillAmt() {
		return this.billAmt;
	}

	public void setBillAmt(Float billAmt) {
		this.billAmt = billAmt;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Boolean getFinal_() {
		return this.final_;
	}

	public void setFinal_(Boolean final_) {
		this.final_ = final_;
	}

	public Integer getPrepBy() {
		return this.prepBy;
	}

	public void setPrepBy(Integer prepBy) {
		this.prepBy = prepBy;
	}

	public Float getEcessAmt() {
		return this.ecessAmt;
	}

	public void setEcessAmt(Float ecessAmt) {
		this.ecessAmt = ecessAmt;
	}

	public String getForm31no() {
		return this.form31no;
	}

	public void setForm31no(String form31no) {
		this.form31no = form31no;
	}

	public Float getSerTaxOnFreight() {
		return this.serTaxOnFreight;
	}

	public void setSerTaxOnFreight(Float serTaxOnFreight) {
		this.serTaxOnFreight = serTaxOnFreight;
	}

	public Float getEcessOnSerTax() {
		return this.ecessOnSerTax;
	}

	public void setEcessOnSerTax(Float ecessOnSerTax) {
		this.ecessOnSerTax = ecessOnSerTax;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RvmasterGlassId))
			return false;
		RvmasterGlassId castOther = (RvmasterGlassId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getRvNo() == castOther.getRvNo()) || (this.getRvNo() != null && castOther.getRvNo() != null && this.getRvNo().equals(
						castOther.getRvNo())))
				&& ((this.getRvDate() == castOther.getRvDate()) || (this.getRvDate() != null && castOther.getRvDate() != null && this.getRvDate()
						.equals(castOther.getRvDate())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getVehNo() == castOther.getVehNo()) || (this.getVehNo() != null && castOther.getVehNo() != null && this.getVehNo().equals(
						castOther.getVehNo())))
				&& ((this.getGrNo() == castOther.getGrNo()) || (this.getGrNo() != null && castOther.getGrNo() != null && this.getGrNo().equals(
						castOther.getGrNo())))
				&& ((this.getTransport() == castOther.getTransport()) || (this.getTransport() != null && castOther.getTransport() != null && this
						.getTransport().equals(castOther.getTransport())))
				&& ((this.getBillNo() == castOther.getBillNo()) || (this.getBillNo() != null && castOther.getBillNo() != null && this.getBillNo()
						.equals(castOther.getBillNo())))
				&& ((this.getBillDate() == castOther.getBillDate()) || (this.getBillDate() != null && castOther.getBillDate() != null && this
						.getBillDate().equals(castOther.getBillDate())))
				&& ((this.getBasicAmt() == castOther.getBasicAmt()) || (this.getBasicAmt() != null && castOther.getBasicAmt() != null && this
						.getBasicAmt().equals(castOther.getBasicAmt())))
				&& ((this.getStaxAmt() == castOther.getStaxAmt()) || (this.getStaxAmt() != null && castOther.getStaxAmt() != null && this
						.getStaxAmt().equals(castOther.getStaxAmt())))
				&& ((this.getInsurAmt() == castOther.getInsurAmt()) || (this.getInsurAmt() != null && castOther.getInsurAmt() != null && this
						.getInsurAmt().equals(castOther.getInsurAmt())))
				&& ((this.getExcAmt() == castOther.getExcAmt()) || (this.getExcAmt() != null && castOther.getExcAmt() != null && this.getExcAmt()
						.equals(castOther.getExcAmt())))
				&& ((this.getFreiamt() == castOther.getFreiamt()) || (this.getFreiamt() != null && castOther.getFreiamt() != null && this
						.getFreiamt().equals(castOther.getFreiamt())))
				&& ((this.getDiscPer() == castOther.getDiscPer()) || (this.getDiscPer() != null && castOther.getDiscPer() != null && this
						.getDiscPer().equals(castOther.getDiscPer())))
				&& ((this.getDiscAmt() == castOther.getDiscAmt()) || (this.getDiscAmt() != null && castOther.getDiscAmt() != null && this
						.getDiscAmt().equals(castOther.getDiscAmt())))
				&& ((this.getOthAdd() == castOther.getOthAdd()) || (this.getOthAdd() != null && castOther.getOthAdd() != null && this.getOthAdd()
						.equals(castOther.getOthAdd())))
				&& ((this.getOthDed() == castOther.getOthDed()) || (this.getOthDed() != null && castOther.getOthDed() != null && this.getOthDed()
						.equals(castOther.getOthDed())))
				&& ((this.getRecAmt() == castOther.getRecAmt()) || (this.getRecAmt() != null && castOther.getRecAmt() != null && this.getRecAmt()
						.equals(castOther.getRecAmt())))
				&& ((this.getPaidAmt() == castOther.getPaidAmt()) || (this.getPaidAmt() != null && castOther.getPaidAmt() != null && this
						.getPaidAmt().equals(castOther.getPaidAmt())))
				&& ((this.getChqNo() == castOther.getChqNo()) || (this.getChqNo() != null && castOther.getChqNo() != null && this.getChqNo().equals(
						castOther.getChqNo())))
				&& ((this.getChqDate() == castOther.getChqDate()) || (this.getChqDate() != null && castOther.getChqDate() != null && this
						.getChqDate().equals(castOther.getChqDate())))
				&& ((this.getThDiscPer() == castOther.getThDiscPer()) || (this.getThDiscPer() != null && castOther.getThDiscPer() != null && this
						.getThDiscPer().equals(castOther.getThDiscPer())))
				&& ((this.getBillAmt() == castOther.getBillAmt()) || (this.getBillAmt() != null && castOther.getBillAmt() != null && this
						.getBillAmt().equals(castOther.getBillAmt())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null && castOther.getNotes() != null && this.getNotes().equals(
						castOther.getNotes())))
				&& ((this.getFinal_() == castOther.getFinal_()) || (this.getFinal_() != null && castOther.getFinal_() != null && this.getFinal_()
						.equals(castOther.getFinal_())))
				&& ((this.getPrepBy() == castOther.getPrepBy()) || (this.getPrepBy() != null && castOther.getPrepBy() != null && this.getPrepBy()
						.equals(castOther.getPrepBy())))
				&& ((this.getEcessAmt() == castOther.getEcessAmt()) || (this.getEcessAmt() != null && castOther.getEcessAmt() != null && this
						.getEcessAmt().equals(castOther.getEcessAmt())))
				&& ((this.getForm31no() == castOther.getForm31no()) || (this.getForm31no() != null && castOther.getForm31no() != null && this
						.getForm31no().equals(castOther.getForm31no())))
				&& ((this.getSerTaxOnFreight() == castOther.getSerTaxOnFreight()) || (this.getSerTaxOnFreight() != null
						&& castOther.getSerTaxOnFreight() != null && this.getSerTaxOnFreight().equals(castOther.getSerTaxOnFreight())))
				&& ((this.getEcessOnSerTax() == castOther.getEcessOnSerTax()) || (this.getEcessOnSerTax() != null
						&& castOther.getEcessOnSerTax() != null && this.getEcessOnSerTax().equals(castOther.getEcessOnSerTax())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getRvNo() == null ? 0 : this.getRvNo().hashCode());
		result = 37 * result + (getRvDate() == null ? 0 : this.getRvDate().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getVehNo() == null ? 0 : this.getVehNo().hashCode());
		result = 37 * result + (getGrNo() == null ? 0 : this.getGrNo().hashCode());
		result = 37 * result + (getTransport() == null ? 0 : this.getTransport().hashCode());
		result = 37 * result + (getBillNo() == null ? 0 : this.getBillNo().hashCode());
		result = 37 * result + (getBillDate() == null ? 0 : this.getBillDate().hashCode());
		result = 37 * result + (getBasicAmt() == null ? 0 : this.getBasicAmt().hashCode());
		result = 37 * result + (getStaxAmt() == null ? 0 : this.getStaxAmt().hashCode());
		result = 37 * result + (getInsurAmt() == null ? 0 : this.getInsurAmt().hashCode());
		result = 37 * result + (getExcAmt() == null ? 0 : this.getExcAmt().hashCode());
		result = 37 * result + (getFreiamt() == null ? 0 : this.getFreiamt().hashCode());
		result = 37 * result + (getDiscPer() == null ? 0 : this.getDiscPer().hashCode());
		result = 37 * result + (getDiscAmt() == null ? 0 : this.getDiscAmt().hashCode());
		result = 37 * result + (getOthAdd() == null ? 0 : this.getOthAdd().hashCode());
		result = 37 * result + (getOthDed() == null ? 0 : this.getOthDed().hashCode());
		result = 37 * result + (getRecAmt() == null ? 0 : this.getRecAmt().hashCode());
		result = 37 * result + (getPaidAmt() == null ? 0 : this.getPaidAmt().hashCode());
		result = 37 * result + (getChqNo() == null ? 0 : this.getChqNo().hashCode());
		result = 37 * result + (getChqDate() == null ? 0 : this.getChqDate().hashCode());
		result = 37 * result + (getThDiscPer() == null ? 0 : this.getThDiscPer().hashCode());
		result = 37 * result + (getBillAmt() == null ? 0 : this.getBillAmt().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result + (getFinal_() == null ? 0 : this.getFinal_().hashCode());
		result = 37 * result + (getPrepBy() == null ? 0 : this.getPrepBy().hashCode());
		result = 37 * result + (getEcessAmt() == null ? 0 : this.getEcessAmt().hashCode());
		result = 37 * result + (getForm31no() == null ? 0 : this.getForm31no().hashCode());
		result = 37 * result + (getSerTaxOnFreight() == null ? 0 : this.getSerTaxOnFreight().hashCode());
		result = 37 * result + (getEcessOnSerTax() == null ? 0 : this.getEcessOnSerTax().hashCode());
		return result;
	}

}
