package com.sd.app.bean.misreport;

// Generated Nov 22, 2014 1:06:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * RawMaterialSummary generated by hbm2java
 */
public class RawMaterialSummary implements java.io.Serializable {

	private RawMaterialSummaryId id;

	public RawMaterialSummary() {
	}

	public RawMaterialSummary(RawMaterialSummaryId id) {
		this.id = id;
	}

	public RawMaterialSummaryId getId() {
		return this.id;
	}

	public void setId(RawMaterialSummaryId id) {
		this.id = id;
	}

}
