package com.sd.app.bean.quotation;

// Generated Nov 22, 2014 1:14:29 PM by Hibernate Tools 3.4.0.CR1

/**
 * PinvMaster generated by hbm2java
 */
public class PinvMaster implements java.io.Serializable {

	private PinvMasterId id;

	public PinvMaster() {
	}

	public PinvMaster(PinvMasterId id) {
		this.id = id;
	}

	public PinvMasterId getId() {
		return this.id;
	}

	public void setId(PinvMasterId id) {
		this.id = id;
	}

}
