package com.sd.app.bean.quotation;

// Generated Nov 22, 2014 1:14:29 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlamDetails generated by hbm2java
 */
public class PlamDetails implements java.io.Serializable {

	private PlamDetailsId id;

	public PlamDetails() {
	}

	public PlamDetails(PlamDetailsId id) {
		this.id = id;
	}

	public PlamDetailsId getId() {
		return this.id;
	}

	public void setId(PlamDetailsId id) {
		this.id = id;
	}

}
