package com.sd.app.bean.wipfile;

// Generated Nov 22, 2014 1:20:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MachineOutPutId generated by hbm2java
 */
public class MachineOutPutId implements java.io.Serializable {

	private Date date;
	private Short machineCode;

	public MachineOutPutId() {
	}

	public MachineOutPutId(Date date, Short machineCode) {
		this.date = date;
		this.machineCode = machineCode;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Short getMachineCode() {
		return this.machineCode;
	}

	public void setMachineCode(Short machineCode) {
		this.machineCode = machineCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MachineOutPutId))
			return false;
		MachineOutPutId castOther = (MachineOutPutId) other;

		return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(
				castOther.getDate())))
				&& ((this.getMachineCode() == castOther.getMachineCode()) || (this.getMachineCode() != null && castOther.getMachineCode() != null && this
						.getMachineCode().equals(castOther.getMachineCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getMachineCode() == null ? 0 : this.getMachineCode().hashCode());
		return result;
	}

}
