package com.sd.app.bean.wipfile;

// Generated Nov 22, 2014 1:20:46 PM by Hibernate Tools 3.4.0.CR1

/**
 * MisReport generated by hbm2java
 */
public class MisReport implements java.io.Serializable {

	private MisReportId id;

	public MisReport() {
	}

	public MisReport(MisReportId id) {
		this.id = id;
	}

	public MisReportId getId() {
		return this.id;
	}

	public void setId(MisReportId id) {
		this.id = id;
	}

}
