package com.sd.app.bean.wipfile;

// Generated Nov 22, 2014 1:20:46 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReWorkOrders generated by hbm2java
 */
public class ReWorkOrders implements java.io.Serializable {

	private ReWorkOrdersId id;

	public ReWorkOrders() {
	}

	public ReWorkOrders(ReWorkOrdersId id) {
		this.id = id;
	}

	public ReWorkOrdersId getId() {
		return this.id;
	}

	public void setId(ReWorkOrdersId id) {
		this.id = id;
	}

}
