package com.sd.app.bean.wipfile;

// Generated Nov 22, 2014 1:20:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ToughPlantId generated by hbm2java
 */
public class ToughPlantId implements java.io.Serializable {

	private Date entryDate;
	private String switchOn;
	private String tempAt;
	private String temp;
	private String prodStartAt;
	private String holdUpFrom1;
	private String holdUpTo1;
	private String holdUpReason1;
	private String holdupFrom2;
	private String holdUpTo2;
	private String holdUpReason2;
	private Short totHrs;
	private Short prodHrs;
	private Short nonProdHrs;
	private Short totMin;
	private Short prodMin;
	private Short nonProdMin;
	private Float dieselused;
	private Float balDiesel;
	private String shift;

	public ToughPlantId() {
	}

	public ToughPlantId(Date entryDate, String switchOn, String tempAt, String temp, String prodStartAt, String holdUpFrom1, String holdUpTo1,
			String holdUpReason1, String holdupFrom2, String holdUpTo2, String holdUpReason2, Short totHrs, Short prodHrs, Short nonProdHrs,
			Short totMin, Short prodMin, Short nonProdMin, Float dieselused, Float balDiesel, String shift) {
		this.entryDate = entryDate;
		this.switchOn = switchOn;
		this.tempAt = tempAt;
		this.temp = temp;
		this.prodStartAt = prodStartAt;
		this.holdUpFrom1 = holdUpFrom1;
		this.holdUpTo1 = holdUpTo1;
		this.holdUpReason1 = holdUpReason1;
		this.holdupFrom2 = holdupFrom2;
		this.holdUpTo2 = holdUpTo2;
		this.holdUpReason2 = holdUpReason2;
		this.totHrs = totHrs;
		this.prodHrs = prodHrs;
		this.nonProdHrs = nonProdHrs;
		this.totMin = totMin;
		this.prodMin = prodMin;
		this.nonProdMin = nonProdMin;
		this.dieselused = dieselused;
		this.balDiesel = balDiesel;
		this.shift = shift;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public String getSwitchOn() {
		return this.switchOn;
	}

	public void setSwitchOn(String switchOn) {
		this.switchOn = switchOn;
	}

	public String getTempAt() {
		return this.tempAt;
	}

	public void setTempAt(String tempAt) {
		this.tempAt = tempAt;
	}

	public String getTemp() {
		return this.temp;
	}

	public void setTemp(String temp) {
		this.temp = temp;
	}

	public String getProdStartAt() {
		return this.prodStartAt;
	}

	public void setProdStartAt(String prodStartAt) {
		this.prodStartAt = prodStartAt;
	}

	public String getHoldUpFrom1() {
		return this.holdUpFrom1;
	}

	public void setHoldUpFrom1(String holdUpFrom1) {
		this.holdUpFrom1 = holdUpFrom1;
	}

	public String getHoldUpTo1() {
		return this.holdUpTo1;
	}

	public void setHoldUpTo1(String holdUpTo1) {
		this.holdUpTo1 = holdUpTo1;
	}

	public String getHoldUpReason1() {
		return this.holdUpReason1;
	}

	public void setHoldUpReason1(String holdUpReason1) {
		this.holdUpReason1 = holdUpReason1;
	}

	public String getHoldupFrom2() {
		return this.holdupFrom2;
	}

	public void setHoldupFrom2(String holdupFrom2) {
		this.holdupFrom2 = holdupFrom2;
	}

	public String getHoldUpTo2() {
		return this.holdUpTo2;
	}

	public void setHoldUpTo2(String holdUpTo2) {
		this.holdUpTo2 = holdUpTo2;
	}

	public String getHoldUpReason2() {
		return this.holdUpReason2;
	}

	public void setHoldUpReason2(String holdUpReason2) {
		this.holdUpReason2 = holdUpReason2;
	}

	public Short getTotHrs() {
		return this.totHrs;
	}

	public void setTotHrs(Short totHrs) {
		this.totHrs = totHrs;
	}

	public Short getProdHrs() {
		return this.prodHrs;
	}

	public void setProdHrs(Short prodHrs) {
		this.prodHrs = prodHrs;
	}

	public Short getNonProdHrs() {
		return this.nonProdHrs;
	}

	public void setNonProdHrs(Short nonProdHrs) {
		this.nonProdHrs = nonProdHrs;
	}

	public Short getTotMin() {
		return this.totMin;
	}

	public void setTotMin(Short totMin) {
		this.totMin = totMin;
	}

	public Short getProdMin() {
		return this.prodMin;
	}

	public void setProdMin(Short prodMin) {
		this.prodMin = prodMin;
	}

	public Short getNonProdMin() {
		return this.nonProdMin;
	}

	public void setNonProdMin(Short nonProdMin) {
		this.nonProdMin = nonProdMin;
	}

	public Float getDieselused() {
		return this.dieselused;
	}

	public void setDieselused(Float dieselused) {
		this.dieselused = dieselused;
	}

	public Float getBalDiesel() {
		return this.balDiesel;
	}

	public void setBalDiesel(Float balDiesel) {
		this.balDiesel = balDiesel;
	}

	public String getShift() {
		return this.shift;
	}

	public void setShift(String shift) {
		this.shift = shift;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ToughPlantId))
			return false;
		ToughPlantId castOther = (ToughPlantId) other;

		return ((this.getEntryDate() == castOther.getEntryDate()) || (this.getEntryDate() != null && castOther.getEntryDate() != null && this
				.getEntryDate().equals(castOther.getEntryDate())))
				&& ((this.getSwitchOn() == castOther.getSwitchOn()) || (this.getSwitchOn() != null && castOther.getSwitchOn() != null && this
						.getSwitchOn().equals(castOther.getSwitchOn())))
				&& ((this.getTempAt() == castOther.getTempAt()) || (this.getTempAt() != null && castOther.getTempAt() != null && this.getTempAt()
						.equals(castOther.getTempAt())))
				&& ((this.getTemp() == castOther.getTemp()) || (this.getTemp() != null && castOther.getTemp() != null && this.getTemp().equals(
						castOther.getTemp())))
				&& ((this.getProdStartAt() == castOther.getProdStartAt()) || (this.getProdStartAt() != null && castOther.getProdStartAt() != null && this
						.getProdStartAt().equals(castOther.getProdStartAt())))
				&& ((this.getHoldUpFrom1() == castOther.getHoldUpFrom1()) || (this.getHoldUpFrom1() != null && castOther.getHoldUpFrom1() != null && this
						.getHoldUpFrom1().equals(castOther.getHoldUpFrom1())))
				&& ((this.getHoldUpTo1() == castOther.getHoldUpTo1()) || (this.getHoldUpTo1() != null && castOther.getHoldUpTo1() != null && this
						.getHoldUpTo1().equals(castOther.getHoldUpTo1())))
				&& ((this.getHoldUpReason1() == castOther.getHoldUpReason1()) || (this.getHoldUpReason1() != null
						&& castOther.getHoldUpReason1() != null && this.getHoldUpReason1().equals(castOther.getHoldUpReason1())))
				&& ((this.getHoldupFrom2() == castOther.getHoldupFrom2()) || (this.getHoldupFrom2() != null && castOther.getHoldupFrom2() != null && this
						.getHoldupFrom2().equals(castOther.getHoldupFrom2())))
				&& ((this.getHoldUpTo2() == castOther.getHoldUpTo2()) || (this.getHoldUpTo2() != null && castOther.getHoldUpTo2() != null && this
						.getHoldUpTo2().equals(castOther.getHoldUpTo2())))
				&& ((this.getHoldUpReason2() == castOther.getHoldUpReason2()) || (this.getHoldUpReason2() != null
						&& castOther.getHoldUpReason2() != null && this.getHoldUpReason2().equals(castOther.getHoldUpReason2())))
				&& ((this.getTotHrs() == castOther.getTotHrs()) || (this.getTotHrs() != null && castOther.getTotHrs() != null && this.getTotHrs()
						.equals(castOther.getTotHrs())))
				&& ((this.getProdHrs() == castOther.getProdHrs()) || (this.getProdHrs() != null && castOther.getProdHrs() != null && this
						.getProdHrs().equals(castOther.getProdHrs())))
				&& ((this.getNonProdHrs() == castOther.getNonProdHrs()) || (this.getNonProdHrs() != null && castOther.getNonProdHrs() != null && this
						.getNonProdHrs().equals(castOther.getNonProdHrs())))
				&& ((this.getTotMin() == castOther.getTotMin()) || (this.getTotMin() != null && castOther.getTotMin() != null && this.getTotMin()
						.equals(castOther.getTotMin())))
				&& ((this.getProdMin() == castOther.getProdMin()) || (this.getProdMin() != null && castOther.getProdMin() != null && this
						.getProdMin().equals(castOther.getProdMin())))
				&& ((this.getNonProdMin() == castOther.getNonProdMin()) || (this.getNonProdMin() != null && castOther.getNonProdMin() != null && this
						.getNonProdMin().equals(castOther.getNonProdMin())))
				&& ((this.getDieselused() == castOther.getDieselused()) || (this.getDieselused() != null && castOther.getDieselused() != null && this
						.getDieselused().equals(castOther.getDieselused())))
				&& ((this.getBalDiesel() == castOther.getBalDiesel()) || (this.getBalDiesel() != null && castOther.getBalDiesel() != null && this
						.getBalDiesel().equals(castOther.getBalDiesel())))
				&& ((this.getShift() == castOther.getShift()) || (this.getShift() != null && castOther.getShift() != null && this.getShift().equals(
						castOther.getShift())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		result = 37 * result + (getSwitchOn() == null ? 0 : this.getSwitchOn().hashCode());
		result = 37 * result + (getTempAt() == null ? 0 : this.getTempAt().hashCode());
		result = 37 * result + (getTemp() == null ? 0 : this.getTemp().hashCode());
		result = 37 * result + (getProdStartAt() == null ? 0 : this.getProdStartAt().hashCode());
		result = 37 * result + (getHoldUpFrom1() == null ? 0 : this.getHoldUpFrom1().hashCode());
		result = 37 * result + (getHoldUpTo1() == null ? 0 : this.getHoldUpTo1().hashCode());
		result = 37 * result + (getHoldUpReason1() == null ? 0 : this.getHoldUpReason1().hashCode());
		result = 37 * result + (getHoldupFrom2() == null ? 0 : this.getHoldupFrom2().hashCode());
		result = 37 * result + (getHoldUpTo2() == null ? 0 : this.getHoldUpTo2().hashCode());
		result = 37 * result + (getHoldUpReason2() == null ? 0 : this.getHoldUpReason2().hashCode());
		result = 37 * result + (getTotHrs() == null ? 0 : this.getTotHrs().hashCode());
		result = 37 * result + (getProdHrs() == null ? 0 : this.getProdHrs().hashCode());
		result = 37 * result + (getNonProdHrs() == null ? 0 : this.getNonProdHrs().hashCode());
		result = 37 * result + (getTotMin() == null ? 0 : this.getTotMin().hashCode());
		result = 37 * result + (getProdMin() == null ? 0 : this.getProdMin().hashCode());
		result = 37 * result + (getNonProdMin() == null ? 0 : this.getNonProdMin().hashCode());
		result = 37 * result + (getDieselused() == null ? 0 : this.getDieselused().hashCode());
		result = 37 * result + (getBalDiesel() == null ? 0 : this.getBalDiesel().hashCode());
		result = 37 * result + (getShift() == null ? 0 : this.getShift().hashCode());
		return result;
	}

}
