package com.sd.app.bean.production;

// Generated Nov 22, 2014 1:12:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ControlOrder generated by hbm2java
 */
public class ControlOrder implements java.io.Serializable {

	private Integer contIdNo;
	private String coCode;
	private Short controlNo;
	private Date date;
	private Integer pcode;
	private String orderNo;
	private Integer orderIdNo;
	private String icode;
	private String tough;
	private Float thick;
	private Short height;
	private Short width;
	private Short pcs;
	private Integer standItNo;
	private Boolean jobWork;
	private Boolean decorative;
	private Short bpcs;
	private String bend;
	private String particulars;
	private Integer controlBy;
	private Float prodPcs;
	private Short itNo;

	public ControlOrder() {
	}

	public ControlOrder(Integer contIdNo) {
		this.contIdNo = contIdNo;
	}

	public ControlOrder(Integer contIdNo, String coCode, Short controlNo, Date date, Integer pcode, String orderNo, Integer orderIdNo, String icode,
			String tough, Float thick, Short height, Short width, Short pcs, Integer standItNo, Boolean jobWork, Boolean decorative, Short bpcs,
			String bend, String particulars, Integer controlBy, Float prodPcs, Short itNo) {
		this.contIdNo = contIdNo;
		this.coCode = coCode;
		this.controlNo = controlNo;
		this.date = date;
		this.pcode = pcode;
		this.orderNo = orderNo;
		this.orderIdNo = orderIdNo;
		this.icode = icode;
		this.tough = tough;
		this.thick = thick;
		this.height = height;
		this.width = width;
		this.pcs = pcs;
		this.standItNo = standItNo;
		this.jobWork = jobWork;
		this.decorative = decorative;
		this.bpcs = bpcs;
		this.bend = bend;
		this.particulars = particulars;
		this.controlBy = controlBy;
		this.prodPcs = prodPcs;
		this.itNo = itNo;
	}

	public Integer getContIdNo() {
		return this.contIdNo;
	}

	public void setContIdNo(Integer contIdNo) {
		this.contIdNo = contIdNo;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Short getControlNo() {
		return this.controlNo;
	}

	public void setControlNo(Short controlNo) {
		this.controlNo = controlNo;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Integer getOrderIdNo() {
		return this.orderIdNo;
	}

	public void setOrderIdNo(Integer orderIdNo) {
		this.orderIdNo = orderIdNo;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public Short getHeight() {
		return this.height;
	}

	public void setHeight(Short height) {
		this.height = height;
	}

	public Short getWidth() {
		return this.width;
	}

	public void setWidth(Short width) {
		this.width = width;
	}

	public Short getPcs() {
		return this.pcs;
	}

	public void setPcs(Short pcs) {
		this.pcs = pcs;
	}

	public Integer getStandItNo() {
		return this.standItNo;
	}

	public void setStandItNo(Integer standItNo) {
		this.standItNo = standItNo;
	}

	public Boolean getJobWork() {
		return this.jobWork;
	}

	public void setJobWork(Boolean jobWork) {
		this.jobWork = jobWork;
	}

	public Boolean getDecorative() {
		return this.decorative;
	}

	public void setDecorative(Boolean decorative) {
		this.decorative = decorative;
	}

	public Short getBpcs() {
		return this.bpcs;
	}

	public void setBpcs(Short bpcs) {
		this.bpcs = bpcs;
	}

	public String getBend() {
		return this.bend;
	}

	public void setBend(String bend) {
		this.bend = bend;
	}

	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	public Integer getControlBy() {
		return this.controlBy;
	}

	public void setControlBy(Integer controlBy) {
		this.controlBy = controlBy;
	}

	public Float getProdPcs() {
		return this.prodPcs;
	}

	public void setProdPcs(Float prodPcs) {
		this.prodPcs = prodPcs;
	}

	public Short getItNo() {
		return this.itNo;
	}

	public void setItNo(Short itNo) {
		this.itNo = itNo;
	}

}
