package com.sd.app.bean.production;

// Generated Nov 22, 2014 1:12:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ProductionId generated by hbm2java
 */
public class ProductionId implements java.io.Serializable {

	private Date date;
	private Integer controlNo;
	private String coCode;
	private String orderNo;
	private Integer contIdNo;
	private Integer standItNo;
	private Float thick;
	private String icode;
	private String bend;
	private String tough;
	private Short width;
	private Short height;
	private Short pcs;
	private Boolean jobWork;
	private Boolean decorative;
	private Short itNo;

	public ProductionId() {
	}

	public ProductionId(Date date, Integer controlNo, String coCode, String orderNo, Integer contIdNo, Integer standItNo, Float thick, String icode,
			String bend, String tough, Short width, Short height, Short pcs, Boolean jobWork, Boolean decorative, Short itNo) {
		this.date = date;
		this.controlNo = controlNo;
		this.coCode = coCode;
		this.orderNo = orderNo;
		this.contIdNo = contIdNo;
		this.standItNo = standItNo;
		this.thick = thick;
		this.icode = icode;
		this.bend = bend;
		this.tough = tough;
		this.width = width;
		this.height = height;
		this.pcs = pcs;
		this.jobWork = jobWork;
		this.decorative = decorative;
		this.itNo = itNo;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getControlNo() {
		return this.controlNo;
	}

	public void setControlNo(Integer controlNo) {
		this.controlNo = controlNo;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Integer getContIdNo() {
		return this.contIdNo;
	}

	public void setContIdNo(Integer contIdNo) {
		this.contIdNo = contIdNo;
	}

	public Integer getStandItNo() {
		return this.standItNo;
	}

	public void setStandItNo(Integer standItNo) {
		this.standItNo = standItNo;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getBend() {
		return this.bend;
	}

	public void setBend(String bend) {
		this.bend = bend;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public Short getWidth() {
		return this.width;
	}

	public void setWidth(Short width) {
		this.width = width;
	}

	public Short getHeight() {
		return this.height;
	}

	public void setHeight(Short height) {
		this.height = height;
	}

	public Short getPcs() {
		return this.pcs;
	}

	public void setPcs(Short pcs) {
		this.pcs = pcs;
	}

	public Boolean getJobWork() {
		return this.jobWork;
	}

	public void setJobWork(Boolean jobWork) {
		this.jobWork = jobWork;
	}

	public Boolean getDecorative() {
		return this.decorative;
	}

	public void setDecorative(Boolean decorative) {
		this.decorative = decorative;
	}

	public Short getItNo() {
		return this.itNo;
	}

	public void setItNo(Short itNo) {
		this.itNo = itNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductionId))
			return false;
		ProductionId castOther = (ProductionId) other;

		return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(
				castOther.getDate())))
				&& ((this.getControlNo() == castOther.getControlNo()) || (this.getControlNo() != null && castOther.getControlNo() != null && this
						.getControlNo().equals(castOther.getControlNo())))
				&& ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode()
						.equals(castOther.getCoCode())))
				&& ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null && castOther.getOrderNo() != null && this
						.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getContIdNo() == castOther.getContIdNo()) || (this.getContIdNo() != null && castOther.getContIdNo() != null && this
						.getContIdNo().equals(castOther.getContIdNo())))
				&& ((this.getStandItNo() == castOther.getStandItNo()) || (this.getStandItNo() != null && castOther.getStandItNo() != null && this
						.getStandItNo().equals(castOther.getStandItNo())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getBend() == castOther.getBend()) || (this.getBend() != null && castOther.getBend() != null && this.getBend().equals(
						castOther.getBend())))
				&& ((this.getTough() == castOther.getTough()) || (this.getTough() != null && castOther.getTough() != null && this.getTough().equals(
						castOther.getTough())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getPcs() == castOther.getPcs()) || (this.getPcs() != null && castOther.getPcs() != null && this.getPcs().equals(
						castOther.getPcs())))
				&& ((this.getJobWork() == castOther.getJobWork()) || (this.getJobWork() != null && castOther.getJobWork() != null && this
						.getJobWork().equals(castOther.getJobWork())))
				&& ((this.getDecorative() == castOther.getDecorative()) || (this.getDecorative() != null && castOther.getDecorative() != null && this
						.getDecorative().equals(castOther.getDecorative())))
				&& ((this.getItNo() == castOther.getItNo()) || (this.getItNo() != null && castOther.getItNo() != null && this.getItNo().equals(
						castOther.getItNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getControlNo() == null ? 0 : this.getControlNo().hashCode());
		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getContIdNo() == null ? 0 : this.getContIdNo().hashCode());
		result = 37 * result + (getStandItNo() == null ? 0 : this.getStandItNo().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getBend() == null ? 0 : this.getBend().hashCode());
		result = 37 * result + (getTough() == null ? 0 : this.getTough().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getPcs() == null ? 0 : this.getPcs().hashCode());
		result = 37 * result + (getJobWork() == null ? 0 : this.getJobWork().hashCode());
		result = 37 * result + (getDecorative() == null ? 0 : this.getDecorative().hashCode());
		result = 37 * result + (getItNo() == null ? 0 : this.getItNo().hashCode());
		return result;
	}

}
