package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

	private CurrencyId id;

	public Currency() {
	}

	public Currency(CurrencyId id) {
		this.id = id;
	}

	public CurrencyId getId() {
		return this.id;
	}

	public void setId(CurrencyId id) {
		this.id = id;
	}

}
