package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * DefaultDirs generated by hbm2java
 */
public class DefaultDirs implements java.io.Serializable {

	private DefaultDirsId id;

	public DefaultDirs() {
	}

	public DefaultDirs(DefaultDirsId id) {
		this.id = id;
	}

	public DefaultDirsId getId() {
		return this.id;
	}

	public void setId(DefaultDirsId id) {
		this.id = id;
	}

}
