package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * ItemMasterId generated by hbm2java
 */
public class ItemMasterId implements java.io.Serializable {

	private Integer itemIdNo;
	private String icode;
	private String particulars;
	private String exCode;
	private Boolean glass;
	private String uom;
	private String tariff;
	private Integer groupIdNo;

	public ItemMasterId() {
	}

	public ItemMasterId(Integer itemIdNo, String icode, String particulars, String exCode, Boolean glass, String uom, String tariff, Integer groupIdNo) {
		this.itemIdNo = itemIdNo;
		this.icode = icode;
		this.particulars = particulars;
		this.exCode = exCode;
		this.glass = glass;
		this.uom = uom;
		this.tariff = tariff;
		this.groupIdNo = groupIdNo;
	}

	public Integer getItemIdNo() {
		return this.itemIdNo;
	}

	public void setItemIdNo(Integer itemIdNo) {
		this.itemIdNo = itemIdNo;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	public String getExCode() {
		return this.exCode;
	}

	public void setExCode(String exCode) {
		this.exCode = exCode;
	}

	public Boolean getGlass() {
		return this.glass;
	}

	public void setGlass(Boolean glass) {
		this.glass = glass;
	}

	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public String getTariff() {
		return this.tariff;
	}

	public void setTariff(String tariff) {
		this.tariff = tariff;
	}

	public Integer getGroupIdNo() {
		return this.groupIdNo;
	}

	public void setGroupIdNo(Integer groupIdNo) {
		this.groupIdNo = groupIdNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemMasterId))
			return false;
		ItemMasterId castOther = (ItemMasterId) other;

		return ((this.getItemIdNo() == castOther.getItemIdNo()) || (this.getItemIdNo() != null && castOther.getItemIdNo() != null && this
				.getItemIdNo().equals(castOther.getItemIdNo())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getParticulars() == castOther.getParticulars()) || (this.getParticulars() != null && castOther.getParticulars() != null && this
						.getParticulars().equals(castOther.getParticulars())))
				&& ((this.getExCode() == castOther.getExCode()) || (this.getExCode() != null && castOther.getExCode() != null && this.getExCode()
						.equals(castOther.getExCode())))
				&& ((this.getGlass() == castOther.getGlass()) || (this.getGlass() != null && castOther.getGlass() != null && this.getGlass().equals(
						castOther.getGlass())))
				&& ((this.getUom() == castOther.getUom()) || (this.getUom() != null && castOther.getUom() != null && this.getUom().equals(
						castOther.getUom())))
				&& ((this.getTariff() == castOther.getTariff()) || (this.getTariff() != null && castOther.getTariff() != null && this.getTariff()
						.equals(castOther.getTariff())))
				&& ((this.getGroupIdNo() == castOther.getGroupIdNo()) || (this.getGroupIdNo() != null && castOther.getGroupIdNo() != null && this
						.getGroupIdNo().equals(castOther.getGroupIdNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getItemIdNo() == null ? 0 : this.getItemIdNo().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getParticulars() == null ? 0 : this.getParticulars().hashCode());
		result = 37 * result + (getExCode() == null ? 0 : this.getExCode().hashCode());
		result = 37 * result + (getGlass() == null ? 0 : this.getGlass().hashCode());
		result = 37 * result + (getUom() == null ? 0 : this.getUom().hashCode());
		result = 37 * result + (getTariff() == null ? 0 : this.getTariff().hashCode());
		result = 37 * result + (getGroupIdNo() == null ? 0 : this.getGroupIdNo().hashCode());
		return result;
	}

}
