package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Masters generated by hbm2java
 */
public class Masters implements java.io.Serializable {

	private MastersId id;

	public Masters() {
	}

	public Masters(MastersId id) {
		this.id = id;
	}

	public MastersId getId() {
		return this.id;
	}

	public void setId(MastersId id) {
		this.id = id;
	}

}
