package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * StaxFormDue generated by hbm2java
 */
public class StaxFormDue implements java.io.Serializable {

	private StaxFormDueId id;

	public StaxFormDue() {
	}

	public StaxFormDue(StaxFormDueId id) {
		this.id = id;
	}

	public StaxFormDueId getId() {
		return this.id;
	}

	public void setId(StaxFormDueId id) {
		this.id = id;
	}

}
