package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * StaxForm generated by hbm2java
 */
public class StaxForm implements java.io.Serializable {

	private StaxFormId id;

	public StaxForm() {
	}

	public StaxForm(StaxFormId id) {
		this.id = id;
	}

	public StaxFormId getId() {
		return this.id;
	}

	public void setId(StaxFormId id) {
		this.id = id;
	}

}
