package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * TariffId generated by hbm2java
 */
public class TariffId implements java.io.Serializable {

	private Integer idNo;
	private String tariff;
	private Boolean decorative;
	private String name;

	public TariffId() {
	}

	public TariffId(Integer idNo, String tariff, Boolean decorative, String name) {
		this.idNo = idNo;
		this.tariff = tariff;
		this.decorative = decorative;
		this.name = name;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public String getTariff() {
		return this.tariff;
	}

	public void setTariff(String tariff) {
		this.tariff = tariff;
	}

	public Boolean getDecorative() {
		return this.decorative;
	}

	public void setDecorative(Boolean decorative) {
		this.decorative = decorative;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TariffId))
			return false;
		TariffId castOther = (TariffId) other;

		return ((this.getIdNo() == castOther.getIdNo()) || (this.getIdNo() != null && castOther.getIdNo() != null && this.getIdNo().equals(
				castOther.getIdNo())))
				&& ((this.getTariff() == castOther.getTariff()) || (this.getTariff() != null && castOther.getTariff() != null && this.getTariff()
						.equals(castOther.getTariff())))
				&& ((this.getDecorative() == castOther.getDecorative()) || (this.getDecorative() != null && castOther.getDecorative() != null && this
						.getDecorative().equals(castOther.getDecorative())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(
						castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdNo() == null ? 0 : this.getIdNo().hashCode());
		result = 37 * result + (getTariff() == null ? 0 : this.getTariff().hashCode());
		result = 37 * result + (getDecorative() == null ? 0 : this.getDecorative().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
