package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tariff generated by hbm2java
 */
public class Tariff implements java.io.Serializable {

	private TariffId id;

	public Tariff() {
	}

	public Tariff(TariffId id) {
		this.id = id;
	}

	public TariffId getId() {
		return this.id;
	}

	public void setId(TariffId id) {
		this.id = id;
	}

}
