package com.sd.app.bean.masters;

// Generated Nov 22, 2014 1:22:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Units generated by hbm2java
 */
public class Units implements java.io.Serializable {

	private String coCode;
	private Integer idNo;
	private String shortName;
	private String fullName;
	private String city;
	private String state;
	private String pin;
	private String country;
	private String phone;
	private String fax;
	private String email;
	private String cstno;
	private String webSite;
	private String upstno;
	private String eccno;
	private String exciseRegNo;
	private String range;
	private String division;
	private String unit;
	private String address;
	private String notificationNo;
	private String quotchar;
	private String orderChar;

	public Units() {
	}

	public Units(String coCode) {
		this.coCode = coCode;
	}

	public Units(String coCode, Integer idNo, String shortName, String fullName, String city, String state, String pin, String country, String phone,
			String fax, String email, String cstno, String webSite, String upstno, String eccno, String exciseRegNo, String range, String division,
			String unit, String address, String notificationNo, String quotchar, String orderChar) {
		this.coCode = coCode;
		this.idNo = idNo;
		this.shortName = shortName;
		this.fullName = fullName;
		this.city = city;
		this.state = state;
		this.pin = pin;
		this.country = country;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.cstno = cstno;
		this.webSite = webSite;
		this.upstno = upstno;
		this.eccno = eccno;
		this.exciseRegNo = exciseRegNo;
		this.range = range;
		this.division = division;
		this.unit = unit;
		this.address = address;
		this.notificationNo = notificationNo;
		this.quotchar = quotchar;
		this.orderChar = orderChar;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCstno() {
		return this.cstno;
	}

	public void setCstno(String cstno) {
		this.cstno = cstno;
	}

	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	public String getUpstno() {
		return this.upstno;
	}

	public void setUpstno(String upstno) {
		this.upstno = upstno;
	}

	public String getEccno() {
		return this.eccno;
	}

	public void setEccno(String eccno) {
		this.eccno = eccno;
	}

	public String getExciseRegNo() {
		return this.exciseRegNo;
	}

	public void setExciseRegNo(String exciseRegNo) {
		this.exciseRegNo = exciseRegNo;
	}

	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNotificationNo() {
		return this.notificationNo;
	}

	public void setNotificationNo(String notificationNo) {
		this.notificationNo = notificationNo;
	}

	public String getQuotchar() {
		return this.quotchar;
	}

	public void setQuotchar(String quotchar) {
		this.quotchar = quotchar;
	}

	public String getOrderChar() {
		return this.orderChar;
	}

	public void setOrderChar(String orderChar) {
		this.orderChar = orderChar;
	}

}
