package com.sd.app.bean.gatepass;

// Generated Nov 22, 2014 12:57:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * GateMaster generated by hbm2java
 */
public class GateMaster implements java.io.Serializable {

	private GateMasterId id;

	public GateMaster() {
	}

	public GateMaster(GateMasterId id) {
		this.id = id;
	}

	public GateMasterId getId() {
		return this.id;
	}

	public void setId(GateMasterId id) {
		this.id = id;
	}

}
