package com.sd.app.bean.gatepass;

// Generated Nov 22, 2014 12:57:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * GateSub generated by hbm2java
 */
public class GateSub implements java.io.Serializable {

	private GateSubId id;

	public GateSub() {
	}

	public GateSub(GateSubId id) {
		this.id = id;
	}

	public GateSubId getId() {
		return this.id;
	}

	public void setId(GateSubId id) {
		this.id = id;
	}

}
