package com.sd.app.bean.challan;

// Generated Nov 22, 2014 12:50:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExciseChallanId generated by hbm2java
 */
public class ExciseChallanId implements java.io.Serializable {

	private Integer idNo;
	private String coCode;
	private Integer challanNo;
	private Date challanDate;
	private Date time;
	private Integer pcode;
	private String transporter;
	private String vehicleNo;
	private String grNo;
	private Integer authBy;
	private Boolean glass;
	private Boolean printed;
	private Integer gpNo;
	private String tariff;
	private String prepBy;

	public ExciseChallanId() {
	}

	public ExciseChallanId(Integer idNo, String coCode, Integer challanNo, Date challanDate, Date time, Integer pcode, String transporter,
			String vehicleNo, String grNo, Integer authBy, Boolean glass, Boolean printed, Integer gpNo, String tariff, String prepBy) {
		this.idNo = idNo;
		this.coCode = coCode;
		this.challanNo = challanNo;
		this.challanDate = challanDate;
		this.time = time;
		this.pcode = pcode;
		this.transporter = transporter;
		this.vehicleNo = vehicleNo;
		this.grNo = grNo;
		this.authBy = authBy;
		this.glass = glass;
		this.printed = printed;
		this.gpNo = gpNo;
		this.tariff = tariff;
		this.prepBy = prepBy;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getChallanNo() {
		return this.challanNo;
	}

	public void setChallanNo(Integer challanNo) {
		this.challanNo = challanNo;
	}

	public Date getChallanDate() {
		return this.challanDate;
	}

	public void setChallanDate(Date challanDate) {
		this.challanDate = challanDate;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public String getTransporter() {
		return this.transporter;
	}

	public void setTransporter(String transporter) {
		this.transporter = transporter;
	}

	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public String getGrNo() {
		return this.grNo;
	}

	public void setGrNo(String grNo) {
		this.grNo = grNo;
	}

	public Integer getAuthBy() {
		return this.authBy;
	}

	public void setAuthBy(Integer authBy) {
		this.authBy = authBy;
	}

	public Boolean getGlass() {
		return this.glass;
	}

	public void setGlass(Boolean glass) {
		this.glass = glass;
	}

	public Boolean getPrinted() {
		return this.printed;
	}

	public void setPrinted(Boolean printed) {
		this.printed = printed;
	}

	public Integer getGpNo() {
		return this.gpNo;
	}

	public void setGpNo(Integer gpNo) {
		this.gpNo = gpNo;
	}

	public String getTariff() {
		return this.tariff;
	}

	public void setTariff(String tariff) {
		this.tariff = tariff;
	}

	public String getPrepBy() {
		return this.prepBy;
	}

	public void setPrepBy(String prepBy) {
		this.prepBy = prepBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExciseChallanId))
			return false;
		ExciseChallanId castOther = (ExciseChallanId) other;

		return ((this.getIdNo() == castOther.getIdNo()) || (this.getIdNo() != null && castOther.getIdNo() != null && this.getIdNo().equals(
				castOther.getIdNo())))
				&& ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode()
						.equals(castOther.getCoCode())))
				&& ((this.getChallanNo() == castOther.getChallanNo()) || (this.getChallanNo() != null && castOther.getChallanNo() != null && this
						.getChallanNo().equals(castOther.getChallanNo())))
				&& ((this.getChallanDate() == castOther.getChallanDate()) || (this.getChallanDate() != null && castOther.getChallanDate() != null && this
						.getChallanDate().equals(castOther.getChallanDate())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null && this.getTime().equals(
						castOther.getTime())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getTransporter() == castOther.getTransporter()) || (this.getTransporter() != null && castOther.getTransporter() != null && this
						.getTransporter().equals(castOther.getTransporter())))
				&& ((this.getVehicleNo() == castOther.getVehicleNo()) || (this.getVehicleNo() != null && castOther.getVehicleNo() != null && this
						.getVehicleNo().equals(castOther.getVehicleNo())))
				&& ((this.getGrNo() == castOther.getGrNo()) || (this.getGrNo() != null && castOther.getGrNo() != null && this.getGrNo().equals(
						castOther.getGrNo())))
				&& ((this.getAuthBy() == castOther.getAuthBy()) || (this.getAuthBy() != null && castOther.getAuthBy() != null && this.getAuthBy()
						.equals(castOther.getAuthBy())))
				&& ((this.getGlass() == castOther.getGlass()) || (this.getGlass() != null && castOther.getGlass() != null && this.getGlass().equals(
						castOther.getGlass())))
				&& ((this.getPrinted() == castOther.getPrinted()) || (this.getPrinted() != null && castOther.getPrinted() != null && this
						.getPrinted().equals(castOther.getPrinted())))
				&& ((this.getGpNo() == castOther.getGpNo()) || (this.getGpNo() != null && castOther.getGpNo() != null && this.getGpNo().equals(
						castOther.getGpNo())))
				&& ((this.getTariff() == castOther.getTariff()) || (this.getTariff() != null && castOther.getTariff() != null && this.getTariff()
						.equals(castOther.getTariff())))
				&& ((this.getPrepBy() == castOther.getPrepBy()) || (this.getPrepBy() != null && castOther.getPrepBy() != null && this.getPrepBy()
						.equals(castOther.getPrepBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdNo() == null ? 0 : this.getIdNo().hashCode());
		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getChallanNo() == null ? 0 : this.getChallanNo().hashCode());
		result = 37 * result + (getChallanDate() == null ? 0 : this.getChallanDate().hashCode());
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getTransporter() == null ? 0 : this.getTransporter().hashCode());
		result = 37 * result + (getVehicleNo() == null ? 0 : this.getVehicleNo().hashCode());
		result = 37 * result + (getGrNo() == null ? 0 : this.getGrNo().hashCode());
		result = 37 * result + (getAuthBy() == null ? 0 : this.getAuthBy().hashCode());
		result = 37 * result + (getGlass() == null ? 0 : this.getGlass().hashCode());
		result = 37 * result + (getPrinted() == null ? 0 : this.getPrinted().hashCode());
		result = 37 * result + (getGpNo() == null ? 0 : this.getGpNo().hashCode());
		result = 37 * result + (getTariff() == null ? 0 : this.getTariff().hashCode());
		result = 37 * result + (getPrepBy() == null ? 0 : this.getPrepBy().hashCode());
		return result;
	}

}
