package com.sd.app.bean.challan;

// Generated Nov 22, 2014 12:50:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExciseChallanDetails generated by hbm2java
 */
public class ExciseChallanDetails implements java.io.Serializable {

	private ExciseChallanDetailsId id;

	public ExciseChallanDetails() {
	}

	public ExciseChallanDetails(ExciseChallanDetailsId id) {
		this.id = id;
	}

	public ExciseChallanDetailsId getId() {
		return this.id;
	}

	public void setId(ExciseChallanDetailsId id) {
		this.id = id;
	}

}
