package com.sd.app.bean.challan;

// Generated Nov 22, 2014 12:50:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonReturnableChallan generated by hbm2java
 */
public class NonReturnableChallan implements java.io.Serializable {

	private NonReturnableChallanId id;

	public NonReturnableChallan() {
	}

	public NonReturnableChallan(NonReturnableChallanId id) {
		this.id = id;
	}

	public NonReturnableChallanId getId() {
		return this.id;
	}

	public void setId(NonReturnableChallanId id) {
		this.id = id;
	}

}
