package com.sd.app.bean.challan;

// Generated Nov 22, 2014 12:50:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReturnableRack generated by hbm2java
 */
public class ReturnableRack implements java.io.Serializable {

	private ReturnableRackId id;

	public ReturnableRack() {
	}

	public ReturnableRack(ReturnableRackId id) {
		this.id = id;
	}

	public ReturnableRackId getId() {
		return this.id;
	}

	public void setId(ReturnableRackId id) {
		this.id = id;
	}

}
