package com.sd.app.bean.challan;

// Generated Nov 22, 2014 12:50:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReturnableChallan generated by hbm2java
 */
public class ReturnableChallan implements java.io.Serializable {

	private ReturnableChallanId id;

	public ReturnableChallan() {
	}

	public ReturnableChallan(ReturnableChallanId id) {
		this.id = id;
	}

	public ReturnableChallanId getId() {
		return this.id;
	}

	public void setId(ReturnableChallanId id) {
		this.id = id;
	}

}
