package com.sd.app.bean.intimation;

// Generated Nov 22, 2014 12:59:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntimationId generated by hbm2java
 */
public class IntimationId implements java.io.Serializable {

	private String coCode;
	private Integer docNo;
	private Integer pcode;
	private String transporter;
	private String vehicleNo;
	private String grNo;
	private String material;
	private String uom;
	private Float qty;
	private String sizes;
	private String docType;
	private String notes;
	private String user;
	private String docDate;

	public IntimationId() {
	}

	public IntimationId(String coCode, Integer docNo, Integer pcode, String transporter, String vehicleNo, String grNo, String material, String uom,
			Float qty, String sizes, String docType, String notes, String user, String docDate) {
		this.coCode = coCode;
		this.docNo = docNo;
		this.pcode = pcode;
		this.transporter = transporter;
		this.vehicleNo = vehicleNo;
		this.grNo = grNo;
		this.material = material;
		this.uom = uom;
		this.qty = qty;
		this.sizes = sizes;
		this.docType = docType;
		this.notes = notes;
		this.user = user;
		this.docDate = docDate;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getDocNo() {
		return this.docNo;
	}

	public void setDocNo(Integer docNo) {
		this.docNo = docNo;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public String getTransporter() {
		return this.transporter;
	}

	public void setTransporter(String transporter) {
		this.transporter = transporter;
	}

	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public String getGrNo() {
		return this.grNo;
	}

	public void setGrNo(String grNo) {
		this.grNo = grNo;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public Float getQty() {
		return this.qty;
	}

	public void setQty(Float qty) {
		this.qty = qty;
	}

	public String getSizes() {
		return this.sizes;
	}

	public void setSizes(String sizes) {
		this.sizes = sizes;
	}

	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getDocDate() {
		return this.docDate;
	}

	public void setDocDate(String docDate) {
		this.docDate = docDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IntimationId))
			return false;
		IntimationId castOther = (IntimationId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getDocNo() == castOther.getDocNo()) || (this.getDocNo() != null && castOther.getDocNo() != null && this.getDocNo().equals(
						castOther.getDocNo())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getTransporter() == castOther.getTransporter()) || (this.getTransporter() != null && castOther.getTransporter() != null && this
						.getTransporter().equals(castOther.getTransporter())))
				&& ((this.getVehicleNo() == castOther.getVehicleNo()) || (this.getVehicleNo() != null && castOther.getVehicleNo() != null && this
						.getVehicleNo().equals(castOther.getVehicleNo())))
				&& ((this.getGrNo() == castOther.getGrNo()) || (this.getGrNo() != null && castOther.getGrNo() != null && this.getGrNo().equals(
						castOther.getGrNo())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null && castOther.getMaterial() != null && this
						.getMaterial().equals(castOther.getMaterial())))
				&& ((this.getUom() == castOther.getUom()) || (this.getUom() != null && castOther.getUom() != null && this.getUom().equals(
						castOther.getUom())))
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null && this.getQty().equals(
						castOther.getQty())))
				&& ((this.getSizes() == castOther.getSizes()) || (this.getSizes() != null && castOther.getSizes() != null && this.getSizes().equals(
						castOther.getSizes())))
				&& ((this.getDocType() == castOther.getDocType()) || (this.getDocType() != null && castOther.getDocType() != null && this
						.getDocType().equals(castOther.getDocType())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null && castOther.getNotes() != null && this.getNotes().equals(
						castOther.getNotes())))
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null && this.getUser().equals(
						castOther.getUser())))
				&& ((this.getDocDate() == castOther.getDocDate()) || (this.getDocDate() != null && castOther.getDocDate() != null && this
						.getDocDate().equals(castOther.getDocDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getDocNo() == null ? 0 : this.getDocNo().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getTransporter() == null ? 0 : this.getTransporter().hashCode());
		result = 37 * result + (getVehicleNo() == null ? 0 : this.getVehicleNo().hashCode());
		result = 37 * result + (getGrNo() == null ? 0 : this.getGrNo().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		result = 37 * result + (getUom() == null ? 0 : this.getUom().hashCode());
		result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
		result = 37 * result + (getSizes() == null ? 0 : this.getSizes().hashCode());
		result = 37 * result + (getDocType() == null ? 0 : this.getDocType().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		result = 37 * result + (getDocDate() == null ? 0 : this.getDocDate().hashCode());
		return result;
	}

}
