package com.sd.app.bean.debitenote;

// Generated Nov 22, 2014 12:51:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvDetails generated by hbm2java
 */
public class InvDetails implements java.io.Serializable {

	private InvDetailsId id;

	public InvDetails() {
	}

	public InvDetails(InvDetailsId id) {
		this.id = id;
	}

	public InvDetailsId getId() {
		return this.id;
	}

	public void setId(InvDetailsId id) {
		this.id = id;
	}

}
