package com.sd.app.bean.debitenote;

// Generated Nov 22, 2014 12:51:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * MonthlySales generated by hbm2java
 */
public class MonthlySales implements java.io.Serializable {

	private MonthlySalesId id;

	public MonthlySales() {
	}

	public MonthlySales(MonthlySalesId id) {
		this.id = id;
	}

	public MonthlySalesId getId() {
		return this.id;
	}

	public void setId(MonthlySalesId id) {
		this.id = id;
	}

}
