package com.sd.app.bean.lamproduction;

// Generated Nov 22, 2014 1:02:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * Lamination generated by hbm2java
 */
public class Lamination implements java.io.Serializable {

	private LaminationId id;

	public Lamination() {
	}

	public Lamination(LaminationId id) {
		this.id = id;
	}

	public LaminationId getId() {
		return this.id;
	}

	public void setId(LaminationId id) {
		this.id = id;
	}

}
