package com.sd.app.bean.lamproduction;

// Generated Nov 22, 2014 1:02:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TmpFileId generated by hbm2java
 */
public class TmpFileId implements java.io.Serializable {

	private Integer idNo;
	private Date entryDate;
	private String orderNo;
	private Short itNo;
	private Float thick;
	private String icode;
	private String bend;
	private String tough;
	private Float width;
	private Float height;
	private Float taper;
	private Short pcs;
	private String grinding;
	private Short frosting;
	private Short beveling;
	private Short printing;
	private Short oddShape;
	private Short holeNos;
	private Short cutOutNos;
	private String remarks;
	private String type;
	private Short breakage;
	private Float ordPcs;
	private Integer pcode;
	private Float sqMt;
	private Float retSqMt;
	private Float lossSqMt;
	private Boolean reWork;
	private String material;

	public TmpFileId() {
	}

	public TmpFileId(Integer idNo, Date entryDate, String orderNo, Short itNo, Float thick, String icode, String bend, String tough, Float width,
			Float height, Float taper, Short pcs, String grinding, Short frosting, Short beveling, Short printing, Short oddShape, Short holeNos,
			Short cutOutNos, String remarks, String type, Short breakage, Float ordPcs, Integer pcode, Float sqMt, Float retSqMt, Float lossSqMt,
			Boolean reWork, String material) {
		this.idNo = idNo;
		this.entryDate = entryDate;
		this.orderNo = orderNo;
		this.itNo = itNo;
		this.thick = thick;
		this.icode = icode;
		this.bend = bend;
		this.tough = tough;
		this.width = width;
		this.height = height;
		this.taper = taper;
		this.pcs = pcs;
		this.grinding = grinding;
		this.frosting = frosting;
		this.beveling = beveling;
		this.printing = printing;
		this.oddShape = oddShape;
		this.holeNos = holeNos;
		this.cutOutNos = cutOutNos;
		this.remarks = remarks;
		this.type = type;
		this.breakage = breakage;
		this.ordPcs = ordPcs;
		this.pcode = pcode;
		this.sqMt = sqMt;
		this.retSqMt = retSqMt;
		this.lossSqMt = lossSqMt;
		this.reWork = reWork;
		this.material = material;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Short getItNo() {
		return this.itNo;
	}

	public void setItNo(Short itNo) {
		this.itNo = itNo;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getBend() {
		return this.bend;
	}

	public void setBend(String bend) {
		this.bend = bend;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public Float getWidth() {
		return this.width;
	}

	public void setWidth(Float width) {
		this.width = width;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getTaper() {
		return this.taper;
	}

	public void setTaper(Float taper) {
		this.taper = taper;
	}

	public Short getPcs() {
		return this.pcs;
	}

	public void setPcs(Short pcs) {
		this.pcs = pcs;
	}

	public String getGrinding() {
		return this.grinding;
	}

	public void setGrinding(String grinding) {
		this.grinding = grinding;
	}

	public Short getFrosting() {
		return this.frosting;
	}

	public void setFrosting(Short frosting) {
		this.frosting = frosting;
	}

	public Short getBeveling() {
		return this.beveling;
	}

	public void setBeveling(Short beveling) {
		this.beveling = beveling;
	}

	public Short getPrinting() {
		return this.printing;
	}

	public void setPrinting(Short printing) {
		this.printing = printing;
	}

	public Short getOddShape() {
		return this.oddShape;
	}

	public void setOddShape(Short oddShape) {
		this.oddShape = oddShape;
	}

	public Short getHoleNos() {
		return this.holeNos;
	}

	public void setHoleNos(Short holeNos) {
		this.holeNos = holeNos;
	}

	public Short getCutOutNos() {
		return this.cutOutNos;
	}

	public void setCutOutNos(Short cutOutNos) {
		this.cutOutNos = cutOutNos;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Short getBreakage() {
		return this.breakage;
	}

	public void setBreakage(Short breakage) {
		this.breakage = breakage;
	}

	public Float getOrdPcs() {
		return this.ordPcs;
	}

	public void setOrdPcs(Float ordPcs) {
		this.ordPcs = ordPcs;
	}

	public Integer getPcode() {
		return this.pcode;
	}

	public void setPcode(Integer pcode) {
		this.pcode = pcode;
	}

	public Float getSqMt() {
		return this.sqMt;
	}

	public void setSqMt(Float sqMt) {
		this.sqMt = sqMt;
	}

	public Float getRetSqMt() {
		return this.retSqMt;
	}

	public void setRetSqMt(Float retSqMt) {
		this.retSqMt = retSqMt;
	}

	public Float getLossSqMt() {
		return this.lossSqMt;
	}

	public void setLossSqMt(Float lossSqMt) {
		this.lossSqMt = lossSqMt;
	}

	public Boolean getReWork() {
		return this.reWork;
	}

	public void setReWork(Boolean reWork) {
		this.reWork = reWork;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpFileId))
			return false;
		TmpFileId castOther = (TmpFileId) other;

		return ((this.getIdNo() == castOther.getIdNo()) || (this.getIdNo() != null && castOther.getIdNo() != null && this.getIdNo().equals(
				castOther.getIdNo())))
				&& ((this.getEntryDate() == castOther.getEntryDate()) || (this.getEntryDate() != null && castOther.getEntryDate() != null && this
						.getEntryDate().equals(castOther.getEntryDate())))
				&& ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null && castOther.getOrderNo() != null && this
						.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getItNo() == castOther.getItNo()) || (this.getItNo() != null && castOther.getItNo() != null && this.getItNo().equals(
						castOther.getItNo())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getBend() == castOther.getBend()) || (this.getBend() != null && castOther.getBend() != null && this.getBend().equals(
						castOther.getBend())))
				&& ((this.getTough() == castOther.getTough()) || (this.getTough() != null && castOther.getTough() != null && this.getTough().equals(
						castOther.getTough())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getTaper() == castOther.getTaper()) || (this.getTaper() != null && castOther.getTaper() != null && this.getTaper().equals(
						castOther.getTaper())))
				&& ((this.getPcs() == castOther.getPcs()) || (this.getPcs() != null && castOther.getPcs() != null && this.getPcs().equals(
						castOther.getPcs())))
				&& ((this.getGrinding() == castOther.getGrinding()) || (this.getGrinding() != null && castOther.getGrinding() != null && this
						.getGrinding().equals(castOther.getGrinding())))
				&& ((this.getFrosting() == castOther.getFrosting()) || (this.getFrosting() != null && castOther.getFrosting() != null && this
						.getFrosting().equals(castOther.getFrosting())))
				&& ((this.getBeveling() == castOther.getBeveling()) || (this.getBeveling() != null && castOther.getBeveling() != null && this
						.getBeveling().equals(castOther.getBeveling())))
				&& ((this.getPrinting() == castOther.getPrinting()) || (this.getPrinting() != null && castOther.getPrinting() != null && this
						.getPrinting().equals(castOther.getPrinting())))
				&& ((this.getOddShape() == castOther.getOddShape()) || (this.getOddShape() != null && castOther.getOddShape() != null && this
						.getOddShape().equals(castOther.getOddShape())))
				&& ((this.getHoleNos() == castOther.getHoleNos()) || (this.getHoleNos() != null && castOther.getHoleNos() != null && this
						.getHoleNos().equals(castOther.getHoleNos())))
				&& ((this.getCutOutNos() == castOther.getCutOutNos()) || (this.getCutOutNos() != null && castOther.getCutOutNos() != null && this
						.getCutOutNos().equals(castOther.getCutOutNos())))
				&& ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null && castOther.getRemarks() != null && this
						.getRemarks().equals(castOther.getRemarks())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this.getType().equals(
						castOther.getType())))
				&& ((this.getBreakage() == castOther.getBreakage()) || (this.getBreakage() != null && castOther.getBreakage() != null && this
						.getBreakage().equals(castOther.getBreakage())))
				&& ((this.getOrdPcs() == castOther.getOrdPcs()) || (this.getOrdPcs() != null && castOther.getOrdPcs() != null && this.getOrdPcs()
						.equals(castOther.getOrdPcs())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getSqMt() == castOther.getSqMt()) || (this.getSqMt() != null && castOther.getSqMt() != null && this.getSqMt().equals(
						castOther.getSqMt())))
				&& ((this.getRetSqMt() == castOther.getRetSqMt()) || (this.getRetSqMt() != null && castOther.getRetSqMt() != null && this
						.getRetSqMt().equals(castOther.getRetSqMt())))
				&& ((this.getLossSqMt() == castOther.getLossSqMt()) || (this.getLossSqMt() != null && castOther.getLossSqMt() != null && this
						.getLossSqMt().equals(castOther.getLossSqMt())))
				&& ((this.getReWork() == castOther.getReWork()) || (this.getReWork() != null && castOther.getReWork() != null && this.getReWork()
						.equals(castOther.getReWork())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null && castOther.getMaterial() != null && this
						.getMaterial().equals(castOther.getMaterial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdNo() == null ? 0 : this.getIdNo().hashCode());
		result = 37 * result + (getEntryDate() == null ? 0 : this.getEntryDate().hashCode());
		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getItNo() == null ? 0 : this.getItNo().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getBend() == null ? 0 : this.getBend().hashCode());
		result = 37 * result + (getTough() == null ? 0 : this.getTough().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getTaper() == null ? 0 : this.getTaper().hashCode());
		result = 37 * result + (getPcs() == null ? 0 : this.getPcs().hashCode());
		result = 37 * result + (getGrinding() == null ? 0 : this.getGrinding().hashCode());
		result = 37 * result + (getFrosting() == null ? 0 : this.getFrosting().hashCode());
		result = 37 * result + (getBeveling() == null ? 0 : this.getBeveling().hashCode());
		result = 37 * result + (getPrinting() == null ? 0 : this.getPrinting().hashCode());
		result = 37 * result + (getOddShape() == null ? 0 : this.getOddShape().hashCode());
		result = 37 * result + (getHoleNos() == null ? 0 : this.getHoleNos().hashCode());
		result = 37 * result + (getCutOutNos() == null ? 0 : this.getCutOutNos().hashCode());
		result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getBreakage() == null ? 0 : this.getBreakage().hashCode());
		result = 37 * result + (getOrdPcs() == null ? 0 : this.getOrdPcs().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getSqMt() == null ? 0 : this.getSqMt().hashCode());
		result = 37 * result + (getRetSqMt() == null ? 0 : this.getRetSqMt().hashCode());
		result = 37 * result + (getLossSqMt() == null ? 0 : this.getLossSqMt().hashCode());
		result = 37 * result + (getReWork() == null ? 0 : this.getReWork().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		return result;
	}

}
