package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * CheapterWiseSales generated by hbm2java
 */
public class CheapterWiseSales implements java.io.Serializable {

	private CheapterWiseSalesId id;

	public CheapterWiseSales() {
	}

	public CheapterWiseSales(CheapterWiseSalesId id) {
		this.id = id;
	}

	public CheapterWiseSalesId getId() {
		return this.id;
	}

	public void setId(CheapterWiseSalesId id) {
		this.id = id;
	}

}
