package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * CheapterWiseSalesId generated by hbm2java
 */
public class CheapterWiseSalesId implements java.io.Serializable {

	private String tariff;
	private Integer invNo;
	private Float thick;
	private String icode;
	private Double sqMs;
	private Double assValue;
	private Double ecess;
	private String coCode;
	private Boolean jobWork;
	private String description;
	private Double exciseDuty;

	public CheapterWiseSalesId() {
	}

	public CheapterWiseSalesId(String tariff, Integer invNo, Float thick, String icode, Double sqMs, Double assValue, Double ecess, String coCode,
			Boolean jobWork, String description, Double exciseDuty) {
		this.tariff = tariff;
		this.invNo = invNo;
		this.thick = thick;
		this.icode = icode;
		this.sqMs = sqMs;
		this.assValue = assValue;
		this.ecess = ecess;
		this.coCode = coCode;
		this.jobWork = jobWork;
		this.description = description;
		this.exciseDuty = exciseDuty;
	}

	public String getTariff() {
		return this.tariff;
	}

	public void setTariff(String tariff) {
		this.tariff = tariff;
	}

	public Integer getInvNo() {
		return this.invNo;
	}

	public void setInvNo(Integer invNo) {
		this.invNo = invNo;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public Double getSqMs() {
		return this.sqMs;
	}

	public void setSqMs(Double sqMs) {
		this.sqMs = sqMs;
	}

	public Double getAssValue() {
		return this.assValue;
	}

	public void setAssValue(Double assValue) {
		this.assValue = assValue;
	}

	public Double getEcess() {
		return this.ecess;
	}

	public void setEcess(Double ecess) {
		this.ecess = ecess;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Boolean getJobWork() {
		return this.jobWork;
	}

	public void setJobWork(Boolean jobWork) {
		this.jobWork = jobWork;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getExciseDuty() {
		return this.exciseDuty;
	}

	public void setExciseDuty(Double exciseDuty) {
		this.exciseDuty = exciseDuty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CheapterWiseSalesId))
			return false;
		CheapterWiseSalesId castOther = (CheapterWiseSalesId) other;

		return ((this.getTariff() == castOther.getTariff()) || (this.getTariff() != null && castOther.getTariff() != null && this.getTariff().equals(
				castOther.getTariff())))
				&& ((this.getInvNo() == castOther.getInvNo()) || (this.getInvNo() != null && castOther.getInvNo() != null && this.getInvNo().equals(
						castOther.getInvNo())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getSqMs() == castOther.getSqMs()) || (this.getSqMs() != null && castOther.getSqMs() != null && this.getSqMs().equals(
						castOther.getSqMs())))
				&& ((this.getAssValue() == castOther.getAssValue()) || (this.getAssValue() != null && castOther.getAssValue() != null && this
						.getAssValue().equals(castOther.getAssValue())))
				&& ((this.getEcess() == castOther.getEcess()) || (this.getEcess() != null && castOther.getEcess() != null && this.getEcess().equals(
						castOther.getEcess())))
				&& ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode()
						.equals(castOther.getCoCode())))
				&& ((this.getJobWork() == castOther.getJobWork()) || (this.getJobWork() != null && castOther.getJobWork() != null && this
						.getJobWork().equals(castOther.getJobWork())))
				&& ((this.getDescription() == castOther.getDescription()) || (this.getDescription() != null && castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getExciseDuty() == castOther.getExciseDuty()) || (this.getExciseDuty() != null && castOther.getExciseDuty() != null && this
						.getExciseDuty().equals(castOther.getExciseDuty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTariff() == null ? 0 : this.getTariff().hashCode());
		result = 37 * result + (getInvNo() == null ? 0 : this.getInvNo().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getSqMs() == null ? 0 : this.getSqMs().hashCode());
		result = 37 * result + (getAssValue() == null ? 0 : this.getAssValue().hashCode());
		result = 37 * result + (getEcess() == null ? 0 : this.getEcess().hashCode());
		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getJobWork() == null ? 0 : this.getJobWork().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getExciseDuty() == null ? 0 : this.getExciseDuty().hashCode());
		return result;
	}

}
