package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExciseInvoiceRegister generated by hbm2java
 */
public class ExciseInvoiceRegister implements java.io.Serializable {

	private ExciseInvoiceRegisterId id;

	public ExciseInvoiceRegister() {
	}

	public ExciseInvoiceRegister(ExciseInvoiceRegisterId id) {
		this.id = id;
	}

	public ExciseInvoiceRegisterId getId() {
		return this.id;
	}

	public void setId(ExciseInvoiceRegisterId id) {
		this.id = id;
	}

}
