package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExciseInvoiceDatewise generated by hbm2java
 */
public class ExciseInvoiceDatewise implements java.io.Serializable {

	private ExciseInvoiceDatewiseId id;
	private Float sqMt;
	private Double basicForExcise;
	private Float exciseAmount;
	private Float ecessOnDuty;
	private Float staxAmount;
	private Float freightAmount;
	private Float serviceTaxAmount;
	private Float ecessOnServiceTax;
	private Float insuranceAmount;
	private Float rawMaterialAmount;
	private Double billAmount;
	private Double billAmountExport;
	private Float handlingAmount;
	private Float totAmount;
	private Double vatamount;
	private String otherdetails3;

	public ExciseInvoiceDatewise() {
	}

	public ExciseInvoiceDatewise(ExciseInvoiceDatewiseId id) {
		this.id = id;
	}

	public ExciseInvoiceDatewise(ExciseInvoiceDatewiseId id, Float sqMt, Double basicForExcise, Float exciseAmount, Float ecessOnDuty,
			Float staxAmount, Float freightAmount, Float serviceTaxAmount, Float ecessOnServiceTax, Float insuranceAmount, Float rawMaterialAmount,
			Double billAmount, Double billAmountExport, Float handlingAmount, Float totAmount, Double vatamount, String otherdetails3) {
		this.id = id;
		this.sqMt = sqMt;
		this.basicForExcise = basicForExcise;
		this.exciseAmount = exciseAmount;
		this.ecessOnDuty = ecessOnDuty;
		this.staxAmount = staxAmount;
		this.freightAmount = freightAmount;
		this.serviceTaxAmount = serviceTaxAmount;
		this.ecessOnServiceTax = ecessOnServiceTax;
		this.insuranceAmount = insuranceAmount;
		this.rawMaterialAmount = rawMaterialAmount;
		this.billAmount = billAmount;
		this.billAmountExport = billAmountExport;
		this.handlingAmount = handlingAmount;
		this.totAmount = totAmount;
		this.vatamount = vatamount;
		this.otherdetails3 = otherdetails3;
	}

	public ExciseInvoiceDatewiseId getId() {
		return this.id;
	}

	public void setId(ExciseInvoiceDatewiseId id) {
		this.id = id;
	}

	public Float getSqMt() {
		return this.sqMt;
	}

	public void setSqMt(Float sqMt) {
		this.sqMt = sqMt;
	}

	public Double getBasicForExcise() {
		return this.basicForExcise;
	}

	public void setBasicForExcise(Double basicForExcise) {
		this.basicForExcise = basicForExcise;
	}

	public Float getExciseAmount() {
		return this.exciseAmount;
	}

	public void setExciseAmount(Float exciseAmount) {
		this.exciseAmount = exciseAmount;
	}

	public Float getEcessOnDuty() {
		return this.ecessOnDuty;
	}

	public void setEcessOnDuty(Float ecessOnDuty) {
		this.ecessOnDuty = ecessOnDuty;
	}

	public Float getStaxAmount() {
		return this.staxAmount;
	}

	public void setStaxAmount(Float staxAmount) {
		this.staxAmount = staxAmount;
	}

	public Float getFreightAmount() {
		return this.freightAmount;
	}

	public void setFreightAmount(Float freightAmount) {
		this.freightAmount = freightAmount;
	}

	public Float getServiceTaxAmount() {
		return this.serviceTaxAmount;
	}

	public void setServiceTaxAmount(Float serviceTaxAmount) {
		this.serviceTaxAmount = serviceTaxAmount;
	}

	public Float getEcessOnServiceTax() {
		return this.ecessOnServiceTax;
	}

	public void setEcessOnServiceTax(Float ecessOnServiceTax) {
		this.ecessOnServiceTax = ecessOnServiceTax;
	}

	public Float getInsuranceAmount() {
		return this.insuranceAmount;
	}

	public void setInsuranceAmount(Float insuranceAmount) {
		this.insuranceAmount = insuranceAmount;
	}

	public Float getRawMaterialAmount() {
		return this.rawMaterialAmount;
	}

	public void setRawMaterialAmount(Float rawMaterialAmount) {
		this.rawMaterialAmount = rawMaterialAmount;
	}

	public Double getBillAmount() {
		return this.billAmount;
	}

	public void setBillAmount(Double billAmount) {
		this.billAmount = billAmount;
	}

	public Double getBillAmountExport() {
		return this.billAmountExport;
	}

	public void setBillAmountExport(Double billAmountExport) {
		this.billAmountExport = billAmountExport;
	}

	public Float getHandlingAmount() {
		return this.handlingAmount;
	}

	public void setHandlingAmount(Float handlingAmount) {
		this.handlingAmount = handlingAmount;
	}

	public Float getTotAmount() {
		return this.totAmount;
	}

	public void setTotAmount(Float totAmount) {
		this.totAmount = totAmount;
	}

	public Double getVatamount() {
		return this.vatamount;
	}

	public void setVatamount(Double vatamount) {
		this.vatamount = vatamount;
	}

	public String getOtherdetails3() {
		return this.otherdetails3;
	}

	public void setOtherdetails3(String otherdetails3) {
		this.otherdetails3 = otherdetails3;
	}

}
