package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExciseInvoiceGtotal generated by hbm2java
 */
public class ExciseInvoiceGtotal implements java.io.Serializable {

	private ExciseInvoiceGtotalId id;

	public ExciseInvoiceGtotal() {
	}

	public ExciseInvoiceGtotal(ExciseInvoiceGtotalId id) {
		this.id = id;
	}

	public ExciseInvoiceGtotalId getId() {
		return this.id;
	}

	public void setId(ExciseInvoiceGtotalId id) {
		this.id = id;
	}

}
