package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExcRawMaterial generated by hbm2java
 */
public class ExcRawMaterial implements java.io.Serializable {

	private ExcRawMaterialId id;

	public ExcRawMaterial() {
	}

	public ExcRawMaterial(ExcRawMaterialId id) {
		this.id = id;
	}

	public ExcRawMaterialId getId() {
		return this.id;
	}

	public void setId(ExcRawMaterialId id) {
		this.id = id;
	}

}
