package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExcRawMaterialId generated by hbm2java
 */
public class ExcRawMaterialId implements java.io.Serializable {

	private String coCode;
	private Date sdate;
	private Date edate;
	private Float thick;
	private String icode;
	private String particulars;
	private Integer billSheets;
	private Integer short_;
	private Integer breakage;
	private Integer sheets;
	private Double recSqms;
	private Integer issueSheets;
	private Double issueSqMs;

	public ExcRawMaterialId() {
	}

	public ExcRawMaterialId(String coCode, Date sdate, Date edate, Float thick, String icode, String particulars, Integer billSheets, Integer short_,
			Integer breakage, Integer sheets, Double recSqms, Integer issueSheets, Double issueSqMs) {
		this.coCode = coCode;
		this.sdate = sdate;
		this.edate = edate;
		this.thick = thick;
		this.icode = icode;
		this.particulars = particulars;
		this.billSheets = billSheets;
		this.short_ = short_;
		this.breakage = breakage;
		this.sheets = sheets;
		this.recSqms = recSqms;
		this.issueSheets = issueSheets;
		this.issueSqMs = issueSqMs;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Date getSdate() {
		return this.sdate;
	}

	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	public Date getEdate() {
		return this.edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	public Integer getBillSheets() {
		return this.billSheets;
	}

	public void setBillSheets(Integer billSheets) {
		this.billSheets = billSheets;
	}

	public Integer getShort_() {
		return this.short_;
	}

	public void setShort_(Integer short_) {
		this.short_ = short_;
	}

	public Integer getBreakage() {
		return this.breakage;
	}

	public void setBreakage(Integer breakage) {
		this.breakage = breakage;
	}

	public Integer getSheets() {
		return this.sheets;
	}

	public void setSheets(Integer sheets) {
		this.sheets = sheets;
	}

	public Double getRecSqms() {
		return this.recSqms;
	}

	public void setRecSqms(Double recSqms) {
		this.recSqms = recSqms;
	}

	public Integer getIssueSheets() {
		return this.issueSheets;
	}

	public void setIssueSheets(Integer issueSheets) {
		this.issueSheets = issueSheets;
	}

	public Double getIssueSqMs() {
		return this.issueSqMs;
	}

	public void setIssueSqMs(Double issueSqMs) {
		this.issueSqMs = issueSqMs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExcRawMaterialId))
			return false;
		ExcRawMaterialId castOther = (ExcRawMaterialId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getSdate() == castOther.getSdate()) || (this.getSdate() != null && castOther.getSdate() != null && this.getSdate().equals(
						castOther.getSdate())))
				&& ((this.getEdate() == castOther.getEdate()) || (this.getEdate() != null && castOther.getEdate() != null && this.getEdate().equals(
						castOther.getEdate())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getParticulars() == castOther.getParticulars()) || (this.getParticulars() != null && castOther.getParticulars() != null && this
						.getParticulars().equals(castOther.getParticulars())))
				&& ((this.getBillSheets() == castOther.getBillSheets()) || (this.getBillSheets() != null && castOther.getBillSheets() != null && this
						.getBillSheets().equals(castOther.getBillSheets())))
				&& ((this.getShort_() == castOther.getShort_()) || (this.getShort_() != null && castOther.getShort_() != null && this.getShort_()
						.equals(castOther.getShort_())))
				&& ((this.getBreakage() == castOther.getBreakage()) || (this.getBreakage() != null && castOther.getBreakage() != null && this
						.getBreakage().equals(castOther.getBreakage())))
				&& ((this.getSheets() == castOther.getSheets()) || (this.getSheets() != null && castOther.getSheets() != null && this.getSheets()
						.equals(castOther.getSheets())))
				&& ((this.getRecSqms() == castOther.getRecSqms()) || (this.getRecSqms() != null && castOther.getRecSqms() != null && this
						.getRecSqms().equals(castOther.getRecSqms())))
				&& ((this.getIssueSheets() == castOther.getIssueSheets()) || (this.getIssueSheets() != null && castOther.getIssueSheets() != null && this
						.getIssueSheets().equals(castOther.getIssueSheets())))
				&& ((this.getIssueSqMs() == castOther.getIssueSqMs()) || (this.getIssueSqMs() != null && castOther.getIssueSqMs() != null && this
						.getIssueSqMs().equals(castOther.getIssueSqMs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getSdate() == null ? 0 : this.getSdate().hashCode());
		result = 37 * result + (getEdate() == null ? 0 : this.getEdate().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getParticulars() == null ? 0 : this.getParticulars().hashCode());
		result = 37 * result + (getBillSheets() == null ? 0 : this.getBillSheets().hashCode());
		result = 37 * result + (getShort_() == null ? 0 : this.getShort_().hashCode());
		result = 37 * result + (getBreakage() == null ? 0 : this.getBreakage().hashCode());
		result = 37 * result + (getSheets() == null ? 0 : this.getSheets().hashCode());
		result = 37 * result + (getRecSqms() == null ? 0 : this.getRecSqms().hashCode());
		result = 37 * result + (getIssueSheets() == null ? 0 : this.getIssueSheets().hashCode());
		result = 37 * result + (getIssueSqMs() == null ? 0 : this.getIssueSqMs().hashCode());
		return result;
	}

}
