package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FreightHamaliId generated by hbm2java
 */
public class FreightHamaliId implements java.io.Serializable {

	private Date sdate;
	private Date edate;
	private Float totFreight;
	private Float cashFreight;
	private Float chqFreight;
	private Float cashHamali;
	private Float chqHamali;
	private String frgType;
	private String weight;
	private Float invNo;
	private String invType;
	private String name;
	private String freight;
	private Float pcode;
	private String vehNo;
	private String unit;
	private String transporter;

	public FreightHamaliId() {
	}

	public FreightHamaliId(Date sdate, Date edate, Float totFreight, Float cashFreight, Float chqFreight, Float cashHamali, Float chqHamali,
			String frgType, String weight, Float invNo, String invType, String name, String freight, Float pcode, String vehNo, String unit,
			String transporter) {
		this.sdate = sdate;
		this.edate = edate;
		this.totFreight = totFreight;
		this.cashFreight = cashFreight;
		this.chqFreight = chqFreight;
		this.cashHamali = cashHamali;
		this.chqHamali = chqHamali;
		this.frgType = frgType;
		this.weight = weight;
		this.invNo = invNo;
		this.invType = invType;
		this.name = name;
		this.freight = freight;
		this.pcode = pcode;
		this.vehNo = vehNo;
		this.unit = unit;
		this.transporter = transporter;
	}

	public Date getSdate() {
		return this.sdate;
	}

	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	public Date getEdate() {
		return this.edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	public Float getTotFreight() {
		return this.totFreight;
	}

	public void setTotFreight(Float totFreight) {
		this.totFreight = totFreight;
	}

	public Float getCashFreight() {
		return this.cashFreight;
	}

	public void setCashFreight(Float cashFreight) {
		this.cashFreight = cashFreight;
	}

	public Float getChqFreight() {
		return this.chqFreight;
	}

	public void setChqFreight(Float chqFreight) {
		this.chqFreight = chqFreight;
	}

	public Float getCashHamali() {
		return this.cashHamali;
	}

	public void setCashHamali(Float cashHamali) {
		this.cashHamali = cashHamali;
	}

	public Float getChqHamali() {
		return this.chqHamali;
	}

	public void setChqHamali(Float chqHamali) {
		this.chqHamali = chqHamali;
	}

	public String getFrgType() {
		return this.frgType;
	}

	public void setFrgType(String frgType) {
		this.frgType = frgType;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public Float getInvNo() {
		return this.invNo;
	}

	public void setInvNo(Float invNo) {
		this.invNo = invNo;
	}

	public String getInvType() {
		return this.invType;
	}

	public void setInvType(String invType) {
		this.invType = invType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFreight() {
		return this.freight;
	}

	public void setFreight(String freight) {
		this.freight = freight;
	}

	public Float getPcode() {
		return this.pcode;
	}

	public void setPcode(Float pcode) {
		this.pcode = pcode;
	}

	public String getVehNo() {
		return this.vehNo;
	}

	public void setVehNo(String vehNo) {
		this.vehNo = vehNo;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getTransporter() {
		return this.transporter;
	}

	public void setTransporter(String transporter) {
		this.transporter = transporter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FreightHamaliId))
			return false;
		FreightHamaliId castOther = (FreightHamaliId) other;

		return ((this.getSdate() == castOther.getSdate()) || (this.getSdate() != null && castOther.getSdate() != null && this.getSdate().equals(
				castOther.getSdate())))
				&& ((this.getEdate() == castOther.getEdate()) || (this.getEdate() != null && castOther.getEdate() != null && this.getEdate().equals(
						castOther.getEdate())))
				&& ((this.getTotFreight() == castOther.getTotFreight()) || (this.getTotFreight() != null && castOther.getTotFreight() != null && this
						.getTotFreight().equals(castOther.getTotFreight())))
				&& ((this.getCashFreight() == castOther.getCashFreight()) || (this.getCashFreight() != null && castOther.getCashFreight() != null && this
						.getCashFreight().equals(castOther.getCashFreight())))
				&& ((this.getChqFreight() == castOther.getChqFreight()) || (this.getChqFreight() != null && castOther.getChqFreight() != null && this
						.getChqFreight().equals(castOther.getChqFreight())))
				&& ((this.getCashHamali() == castOther.getCashHamali()) || (this.getCashHamali() != null && castOther.getCashHamali() != null && this
						.getCashHamali().equals(castOther.getCashHamali())))
				&& ((this.getChqHamali() == castOther.getChqHamali()) || (this.getChqHamali() != null && castOther.getChqHamali() != null && this
						.getChqHamali().equals(castOther.getChqHamali())))
				&& ((this.getFrgType() == castOther.getFrgType()) || (this.getFrgType() != null && castOther.getFrgType() != null && this
						.getFrgType().equals(castOther.getFrgType())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null && castOther.getWeight() != null && this.getWeight()
						.equals(castOther.getWeight())))
				&& ((this.getInvNo() == castOther.getInvNo()) || (this.getInvNo() != null && castOther.getInvNo() != null && this.getInvNo().equals(
						castOther.getInvNo())))
				&& ((this.getInvType() == castOther.getInvType()) || (this.getInvType() != null && castOther.getInvType() != null && this
						.getInvType().equals(castOther.getInvType())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(
						castOther.getName())))
				&& ((this.getFreight() == castOther.getFreight()) || (this.getFreight() != null && castOther.getFreight() != null && this
						.getFreight().equals(castOther.getFreight())))
				&& ((this.getPcode() == castOther.getPcode()) || (this.getPcode() != null && castOther.getPcode() != null && this.getPcode().equals(
						castOther.getPcode())))
				&& ((this.getVehNo() == castOther.getVehNo()) || (this.getVehNo() != null && castOther.getVehNo() != null && this.getVehNo().equals(
						castOther.getVehNo())))
				&& ((this.getUnit() == castOther.getUnit()) || (this.getUnit() != null && castOther.getUnit() != null && this.getUnit().equals(
						castOther.getUnit())))
				&& ((this.getTransporter() == castOther.getTransporter()) || (this.getTransporter() != null && castOther.getTransporter() != null && this
						.getTransporter().equals(castOther.getTransporter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSdate() == null ? 0 : this.getSdate().hashCode());
		result = 37 * result + (getEdate() == null ? 0 : this.getEdate().hashCode());
		result = 37 * result + (getTotFreight() == null ? 0 : this.getTotFreight().hashCode());
		result = 37 * result + (getCashFreight() == null ? 0 : this.getCashFreight().hashCode());
		result = 37 * result + (getChqFreight() == null ? 0 : this.getChqFreight().hashCode());
		result = 37 * result + (getCashHamali() == null ? 0 : this.getCashHamali().hashCode());
		result = 37 * result + (getChqHamali() == null ? 0 : this.getChqHamali().hashCode());
		result = 37 * result + (getFrgType() == null ? 0 : this.getFrgType().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		result = 37 * result + (getInvNo() == null ? 0 : this.getInvNo().hashCode());
		result = 37 * result + (getInvType() == null ? 0 : this.getInvType().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getFreight() == null ? 0 : this.getFreight().hashCode());
		result = 37 * result + (getPcode() == null ? 0 : this.getPcode().hashCode());
		result = 37 * result + (getVehNo() == null ? 0 : this.getVehNo().hashCode());
		result = 37 * result + (getUnit() == null ? 0 : this.getUnit().hashCode());
		result = 37 * result + (getTransporter() == null ? 0 : this.getTransporter().hashCode());
		return result;
	}

}
