package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * MsysCompactError generated by hbm2java
 */
public class MsysCompactError implements java.io.Serializable {

	private MsysCompactErrorId id;

	public MsysCompactError() {
	}

	public MsysCompactError(MsysCompactErrorId id) {
		this.id = id;
	}

	public MsysCompactErrorId getId() {
		return this.id;
	}

	public void setId(MsysCompactErrorId id) {
		this.id = id;
	}

}
