package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * OffCutReceipts generated by hbm2java
 */
public class OffCutReceipts implements java.io.Serializable {

	private OffCutReceiptsId id;

	public OffCutReceipts() {
	}

	public OffCutReceipts(OffCutReceiptsId id) {
		this.id = id;
	}

	public OffCutReceiptsId getId() {
		return this.id;
	}

	public void setId(OffCutReceiptsId id) {
		this.id = id;
	}

}
