package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private OrderId id;

	public Order() {
	}

	public Order(OrderId id) {
		this.id = id;
	}

	public OrderId getId() {
		return this.id;
	}

	public void setId(OrderId id) {
		this.id = id;
	}

}
