package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * PartiesRate generated by hbm2java
 */
public class PartiesRate implements java.io.Serializable {

	private PartiesRateId id;

	public PartiesRate() {
	}

	public PartiesRate(PartiesRateId id) {
		this.id = id;
	}

	public PartiesRateId getId() {
		return this.id;
	}

	public void setId(PartiesRateId id) {
		this.id = id;
	}

}
