package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * PendingCommercial generated by hbm2java
 */
public class PendingCommercial implements java.io.Serializable {

	private PendingCommercialId id;

	public PendingCommercial() {
	}

	public PendingCommercial(PendingCommercialId id) {
		this.id = id;
	}

	public PendingCommercialId getId() {
		return this.id;
	}

	public void setId(PendingCommercialId id) {
		this.id = id;
	}

}
