package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PrintOrderStatusId generated by hbm2java
 */
public class PrintOrderStatusId implements java.io.Serializable {

	private String orderNo;
	private String coCode;
	private Float thick;
	private String packing;
	private Date reviDate;
	private String quick;
	private String action;
	private Short bpcs;
	private String acStatus;
	private String material;
	private String party;
	private String controlBy;
	private Integer cutting;
	private Integer grinding;
	private Integer temparing;
	private Integer insulating;
	private Date orderDate;
	private Short pcs;
	private Short ready;
	private Float sqMt;
	private String remarks;
	private String application;
	private String hold;
	private String orderStatus;
	private Float srNo;
	private String dealBy;
	private Date planDate;
	private String reviDateDetails;
	private String remarks1;
	private Float bevlPcs;
	private Float frostPcs;
	private Float printPcs;

	public PrintOrderStatusId() {
	}

	public PrintOrderStatusId(String orderNo, String coCode, Float thick, String packing, Date reviDate, String quick, String action, Short bpcs,
			String acStatus, String material, String party, String controlBy, Integer cutting, Integer grinding, Integer temparing,
			Integer insulating, Date orderDate, Short pcs, Short ready, Float sqMt, String remarks, String application, String hold,
			String orderStatus, Float srNo, String dealBy, Date planDate, String reviDateDetails, String remarks1, Float bevlPcs, Float frostPcs,
			Float printPcs) {
		this.orderNo = orderNo;
		this.coCode = coCode;
		this.thick = thick;
		this.packing = packing;
		this.reviDate = reviDate;
		this.quick = quick;
		this.action = action;
		this.bpcs = bpcs;
		this.acStatus = acStatus;
		this.material = material;
		this.party = party;
		this.controlBy = controlBy;
		this.cutting = cutting;
		this.grinding = grinding;
		this.temparing = temparing;
		this.insulating = insulating;
		this.orderDate = orderDate;
		this.pcs = pcs;
		this.ready = ready;
		this.sqMt = sqMt;
		this.remarks = remarks;
		this.application = application;
		this.hold = hold;
		this.orderStatus = orderStatus;
		this.srNo = srNo;
		this.dealBy = dealBy;
		this.planDate = planDate;
		this.reviDateDetails = reviDateDetails;
		this.remarks1 = remarks1;
		this.bevlPcs = bevlPcs;
		this.frostPcs = frostPcs;
		this.printPcs = printPcs;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getPacking() {
		return this.packing;
	}

	public void setPacking(String packing) {
		this.packing = packing;
	}

	public Date getReviDate() {
		return this.reviDate;
	}

	public void setReviDate(Date reviDate) {
		this.reviDate = reviDate;
	}

	public String getQuick() {
		return this.quick;
	}

	public void setQuick(String quick) {
		this.quick = quick;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Short getBpcs() {
		return this.bpcs;
	}

	public void setBpcs(Short bpcs) {
		this.bpcs = bpcs;
	}

	public String getAcStatus() {
		return this.acStatus;
	}

	public void setAcStatus(String acStatus) {
		this.acStatus = acStatus;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public String getParty() {
		return this.party;
	}

	public void setParty(String party) {
		this.party = party;
	}

	public String getControlBy() {
		return this.controlBy;
	}

	public void setControlBy(String controlBy) {
		this.controlBy = controlBy;
	}

	public Integer getCutting() {
		return this.cutting;
	}

	public void setCutting(Integer cutting) {
		this.cutting = cutting;
	}

	public Integer getGrinding() {
		return this.grinding;
	}

	public void setGrinding(Integer grinding) {
		this.grinding = grinding;
	}

	public Integer getTemparing() {
		return this.temparing;
	}

	public void setTemparing(Integer temparing) {
		this.temparing = temparing;
	}

	public Integer getInsulating() {
		return this.insulating;
	}

	public void setInsulating(Integer insulating) {
		this.insulating = insulating;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Short getPcs() {
		return this.pcs;
	}

	public void setPcs(Short pcs) {
		this.pcs = pcs;
	}

	public Short getReady() {
		return this.ready;
	}

	public void setReady(Short ready) {
		this.ready = ready;
	}

	public Float getSqMt() {
		return this.sqMt;
	}

	public void setSqMt(Float sqMt) {
		this.sqMt = sqMt;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

	public String getHold() {
		return this.hold;
	}

	public void setHold(String hold) {
		this.hold = hold;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Float getSrNo() {
		return this.srNo;
	}

	public void setSrNo(Float srNo) {
		this.srNo = srNo;
	}

	public String getDealBy() {
		return this.dealBy;
	}

	public void setDealBy(String dealBy) {
		this.dealBy = dealBy;
	}

	public Date getPlanDate() {
		return this.planDate;
	}

	public void setPlanDate(Date planDate) {
		this.planDate = planDate;
	}

	public String getReviDateDetails() {
		return this.reviDateDetails;
	}

	public void setReviDateDetails(String reviDateDetails) {
		this.reviDateDetails = reviDateDetails;
	}

	public String getRemarks1() {
		return this.remarks1;
	}

	public void setRemarks1(String remarks1) {
		this.remarks1 = remarks1;
	}

	public Float getBevlPcs() {
		return this.bevlPcs;
	}

	public void setBevlPcs(Float bevlPcs) {
		this.bevlPcs = bevlPcs;
	}

	public Float getFrostPcs() {
		return this.frostPcs;
	}

	public void setFrostPcs(Float frostPcs) {
		this.frostPcs = frostPcs;
	}

	public Float getPrintPcs() {
		return this.printPcs;
	}

	public void setPrintPcs(Float printPcs) {
		this.printPcs = printPcs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrintOrderStatusId))
			return false;
		PrintOrderStatusId castOther = (PrintOrderStatusId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null && castOther.getOrderNo() != null && this.getOrderNo()
				.equals(castOther.getOrderNo())))
				&& ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode()
						.equals(castOther.getCoCode())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getPacking() == castOther.getPacking()) || (this.getPacking() != null && castOther.getPacking() != null && this
						.getPacking().equals(castOther.getPacking())))
				&& ((this.getReviDate() == castOther.getReviDate()) || (this.getReviDate() != null && castOther.getReviDate() != null && this
						.getReviDate().equals(castOther.getReviDate())))
				&& ((this.getQuick() == castOther.getQuick()) || (this.getQuick() != null && castOther.getQuick() != null && this.getQuick().equals(
						castOther.getQuick())))
				&& ((this.getAction() == castOther.getAction()) || (this.getAction() != null && castOther.getAction() != null && this.getAction()
						.equals(castOther.getAction())))
				&& ((this.getBpcs() == castOther.getBpcs()) || (this.getBpcs() != null && castOther.getBpcs() != null && this.getBpcs().equals(
						castOther.getBpcs())))
				&& ((this.getAcStatus() == castOther.getAcStatus()) || (this.getAcStatus() != null && castOther.getAcStatus() != null && this
						.getAcStatus().equals(castOther.getAcStatus())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null && castOther.getMaterial() != null && this
						.getMaterial().equals(castOther.getMaterial())))
				&& ((this.getParty() == castOther.getParty()) || (this.getParty() != null && castOther.getParty() != null && this.getParty().equals(
						castOther.getParty())))
				&& ((this.getControlBy() == castOther.getControlBy()) || (this.getControlBy() != null && castOther.getControlBy() != null && this
						.getControlBy().equals(castOther.getControlBy())))
				&& ((this.getCutting() == castOther.getCutting()) || (this.getCutting() != null && castOther.getCutting() != null && this
						.getCutting().equals(castOther.getCutting())))
				&& ((this.getGrinding() == castOther.getGrinding()) || (this.getGrinding() != null && castOther.getGrinding() != null && this
						.getGrinding().equals(castOther.getGrinding())))
				&& ((this.getTemparing() == castOther.getTemparing()) || (this.getTemparing() != null && castOther.getTemparing() != null && this
						.getTemparing().equals(castOther.getTemparing())))
				&& ((this.getInsulating() == castOther.getInsulating()) || (this.getInsulating() != null && castOther.getInsulating() != null && this
						.getInsulating().equals(castOther.getInsulating())))
				&& ((this.getOrderDate() == castOther.getOrderDate()) || (this.getOrderDate() != null && castOther.getOrderDate() != null && this
						.getOrderDate().equals(castOther.getOrderDate())))
				&& ((this.getPcs() == castOther.getPcs()) || (this.getPcs() != null && castOther.getPcs() != null && this.getPcs().equals(
						castOther.getPcs())))
				&& ((this.getReady() == castOther.getReady()) || (this.getReady() != null && castOther.getReady() != null && this.getReady().equals(
						castOther.getReady())))
				&& ((this.getSqMt() == castOther.getSqMt()) || (this.getSqMt() != null && castOther.getSqMt() != null && this.getSqMt().equals(
						castOther.getSqMt())))
				&& ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null && castOther.getRemarks() != null && this
						.getRemarks().equals(castOther.getRemarks())))
				&& ((this.getApplication() == castOther.getApplication()) || (this.getApplication() != null && castOther.getApplication() != null && this
						.getApplication().equals(castOther.getApplication())))
				&& ((this.getHold() == castOther.getHold()) || (this.getHold() != null && castOther.getHold() != null && this.getHold().equals(
						castOther.getHold())))
				&& ((this.getOrderStatus() == castOther.getOrderStatus()) || (this.getOrderStatus() != null && castOther.getOrderStatus() != null && this
						.getOrderStatus().equals(castOther.getOrderStatus())))
				&& ((this.getSrNo() == castOther.getSrNo()) || (this.getSrNo() != null && castOther.getSrNo() != null && this.getSrNo().equals(
						castOther.getSrNo())))
				&& ((this.getDealBy() == castOther.getDealBy()) || (this.getDealBy() != null && castOther.getDealBy() != null && this.getDealBy()
						.equals(castOther.getDealBy())))
				&& ((this.getPlanDate() == castOther.getPlanDate()) || (this.getPlanDate() != null && castOther.getPlanDate() != null && this
						.getPlanDate().equals(castOther.getPlanDate())))
				&& ((this.getReviDateDetails() == castOther.getReviDateDetails()) || (this.getReviDateDetails() != null
						&& castOther.getReviDateDetails() != null && this.getReviDateDetails().equals(castOther.getReviDateDetails())))
				&& ((this.getRemarks1() == castOther.getRemarks1()) || (this.getRemarks1() != null && castOther.getRemarks1() != null && this
						.getRemarks1().equals(castOther.getRemarks1())))
				&& ((this.getBevlPcs() == castOther.getBevlPcs()) || (this.getBevlPcs() != null && castOther.getBevlPcs() != null && this
						.getBevlPcs().equals(castOther.getBevlPcs())))
				&& ((this.getFrostPcs() == castOther.getFrostPcs()) || (this.getFrostPcs() != null && castOther.getFrostPcs() != null && this
						.getFrostPcs().equals(castOther.getFrostPcs())))
				&& ((this.getPrintPcs() == castOther.getPrintPcs()) || (this.getPrintPcs() != null && castOther.getPrintPcs() != null && this
						.getPrintPcs().equals(castOther.getPrintPcs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getPacking() == null ? 0 : this.getPacking().hashCode());
		result = 37 * result + (getReviDate() == null ? 0 : this.getReviDate().hashCode());
		result = 37 * result + (getQuick() == null ? 0 : this.getQuick().hashCode());
		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getBpcs() == null ? 0 : this.getBpcs().hashCode());
		result = 37 * result + (getAcStatus() == null ? 0 : this.getAcStatus().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		result = 37 * result + (getParty() == null ? 0 : this.getParty().hashCode());
		result = 37 * result + (getControlBy() == null ? 0 : this.getControlBy().hashCode());
		result = 37 * result + (getCutting() == null ? 0 : this.getCutting().hashCode());
		result = 37 * result + (getGrinding() == null ? 0 : this.getGrinding().hashCode());
		result = 37 * result + (getTemparing() == null ? 0 : this.getTemparing().hashCode());
		result = 37 * result + (getInsulating() == null ? 0 : this.getInsulating().hashCode());
		result = 37 * result + (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());
		result = 37 * result + (getPcs() == null ? 0 : this.getPcs().hashCode());
		result = 37 * result + (getReady() == null ? 0 : this.getReady().hashCode());
		result = 37 * result + (getSqMt() == null ? 0 : this.getSqMt().hashCode());
		result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
		result = 37 * result + (getApplication() == null ? 0 : this.getApplication().hashCode());
		result = 37 * result + (getHold() == null ? 0 : this.getHold().hashCode());
		result = 37 * result + (getOrderStatus() == null ? 0 : this.getOrderStatus().hashCode());
		result = 37 * result + (getSrNo() == null ? 0 : this.getSrNo().hashCode());
		result = 37 * result + (getDealBy() == null ? 0 : this.getDealBy().hashCode());
		result = 37 * result + (getPlanDate() == null ? 0 : this.getPlanDate().hashCode());
		result = 37 * result + (getReviDateDetails() == null ? 0 : this.getReviDateDetails().hashCode());
		result = 37 * result + (getRemarks1() == null ? 0 : this.getRemarks1().hashCode());
		result = 37 * result + (getBevlPcs() == null ? 0 : this.getBevlPcs().hashCode());
		result = 37 * result + (getFrostPcs() == null ? 0 : this.getFrostPcs().hashCode());
		result = 37 * result + (getPrintPcs() == null ? 0 : this.getPrintPcs().hashCode());
		return result;
	}

}
