package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrintGatePass generated by hbm2java
 */
public class PrintGatePass implements java.io.Serializable {

	private PrintGatePassId id;

	public PrintGatePass() {
	}

	public PrintGatePass(PrintGatePassId id) {
		this.id = id;
	}

	public PrintGatePassId getId() {
		return this.id;
	}

	public void setId(PrintGatePassId id) {
		this.id = id;
	}

}
