package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ProformaregisterId generated by hbm2java
 */
public class ProformaregisterId implements java.io.Serializable {

	private String orderNo;
	private String party;
	private String material;
	private Double qty;
	private Double sqMtr;
	private String dealBy;
	private Date orderDate;
	private Date plandate;
	private Date reviDate;
	private String remarks;
	private Double amount;
	private Double useridno;
	private String paymentterms;
	private String staxForm;

	public ProformaregisterId() {
	}

	public ProformaregisterId(String orderNo, String party, String material, Double qty, Double sqMtr, String dealBy, Date orderDate, Date plandate,
			Date reviDate, String remarks, Double amount, Double useridno, String paymentterms, String staxForm) {
		this.orderNo = orderNo;
		this.party = party;
		this.material = material;
		this.qty = qty;
		this.sqMtr = sqMtr;
		this.dealBy = dealBy;
		this.orderDate = orderDate;
		this.plandate = plandate;
		this.reviDate = reviDate;
		this.remarks = remarks;
		this.amount = amount;
		this.useridno = useridno;
		this.paymentterms = paymentterms;
		this.staxForm = staxForm;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getParty() {
		return this.party;
	}

	public void setParty(String party) {
		this.party = party;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public Double getSqMtr() {
		return this.sqMtr;
	}

	public void setSqMtr(Double sqMtr) {
		this.sqMtr = sqMtr;
	}

	public String getDealBy() {
		return this.dealBy;
	}

	public void setDealBy(String dealBy) {
		this.dealBy = dealBy;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public Date getPlandate() {
		return this.plandate;
	}

	public void setPlandate(Date plandate) {
		this.plandate = plandate;
	}

	public Date getReviDate() {
		return this.reviDate;
	}

	public void setReviDate(Date reviDate) {
		this.reviDate = reviDate;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Double getUseridno() {
		return this.useridno;
	}

	public void setUseridno(Double useridno) {
		this.useridno = useridno;
	}

	public String getPaymentterms() {
		return this.paymentterms;
	}

	public void setPaymentterms(String paymentterms) {
		this.paymentterms = paymentterms;
	}

	public String getStaxForm() {
		return this.staxForm;
	}

	public void setStaxForm(String staxForm) {
		this.staxForm = staxForm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProformaregisterId))
			return false;
		ProformaregisterId castOther = (ProformaregisterId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null && castOther.getOrderNo() != null && this.getOrderNo()
				.equals(castOther.getOrderNo())))
				&& ((this.getParty() == castOther.getParty()) || (this.getParty() != null && castOther.getParty() != null && this.getParty().equals(
						castOther.getParty())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null && castOther.getMaterial() != null && this
						.getMaterial().equals(castOther.getMaterial())))
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null && this.getQty().equals(
						castOther.getQty())))
				&& ((this.getSqMtr() == castOther.getSqMtr()) || (this.getSqMtr() != null && castOther.getSqMtr() != null && this.getSqMtr().equals(
						castOther.getSqMtr())))
				&& ((this.getDealBy() == castOther.getDealBy()) || (this.getDealBy() != null && castOther.getDealBy() != null && this.getDealBy()
						.equals(castOther.getDealBy())))
				&& ((this.getOrderDate() == castOther.getOrderDate()) || (this.getOrderDate() != null && castOther.getOrderDate() != null && this
						.getOrderDate().equals(castOther.getOrderDate())))
				&& ((this.getPlandate() == castOther.getPlandate()) || (this.getPlandate() != null && castOther.getPlandate() != null && this
						.getPlandate().equals(castOther.getPlandate())))
				&& ((this.getReviDate() == castOther.getReviDate()) || (this.getReviDate() != null && castOther.getReviDate() != null && this
						.getReviDate().equals(castOther.getReviDate())))
				&& ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null && castOther.getRemarks() != null && this
						.getRemarks().equals(castOther.getRemarks())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null && castOther.getAmount() != null && this.getAmount()
						.equals(castOther.getAmount())))
				&& ((this.getUseridno() == castOther.getUseridno()) || (this.getUseridno() != null && castOther.getUseridno() != null && this
						.getUseridno().equals(castOther.getUseridno())))
				&& ((this.getPaymentterms() == castOther.getPaymentterms()) || (this.getPaymentterms() != null && castOther.getPaymentterms() != null && this
						.getPaymentterms().equals(castOther.getPaymentterms())))
				&& ((this.getStaxForm() == castOther.getStaxForm()) || (this.getStaxForm() != null && castOther.getStaxForm() != null && this
						.getStaxForm().equals(castOther.getStaxForm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getParty() == null ? 0 : this.getParty().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
		result = 37 * result + (getSqMtr() == null ? 0 : this.getSqMtr().hashCode());
		result = 37 * result + (getDealBy() == null ? 0 : this.getDealBy().hashCode());
		result = 37 * result + (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());
		result = 37 * result + (getPlandate() == null ? 0 : this.getPlandate().hashCode());
		result = 37 * result + (getReviDate() == null ? 0 : this.getReviDate().hashCode());
		result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getUseridno() == null ? 0 : this.getUseridno().hashCode());
		result = 37 * result + (getPaymentterms() == null ? 0 : this.getPaymentterms().hashCode());
		result = 37 * result + (getStaxForm() == null ? 0 : this.getStaxForm().hashCode());
		return result;
	}

}
