package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * RawIssueSummary generated by hbm2java
 */
public class RawIssueSummary implements java.io.Serializable {

	private RawIssueSummaryId id;

	public RawIssueSummary() {
	}

	public RawIssueSummary(RawIssueSummaryId id) {
		this.id = id;
	}

	public RawIssueSummaryId getId() {
		return this.id;
	}

	public void setId(RawIssueSummaryId id) {
		this.id = id;
	}

}
