package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rg23aistock generated by hbm2java
 */
public class Rg23aistock implements java.io.Serializable {

	private Rg23aistockId id;

	public Rg23aistock() {
	}

	public Rg23aistock(Rg23aistockId id) {
		this.id = id;
	}

	public Rg23aistockId getId() {
		return this.id;
	}

	public void setId(Rg23aistockId id) {
		this.id = id;
	}

}
