package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Rg23airegisterId generated by hbm2java
 */
public class Rg23airegisterId implements java.io.Serializable {

	private String coCode;
	private Date date;
	private Float thick;
	private String icode;
	private String particulars;
	private Double opSqMs;
	private Integer rvno;
	private String billNo;
	private Date billDate;
	private String party;
	private String range;
	private Integer issueNo;
	private Double issueSqMs;
	private Double closingSqMs;
	private Date sdate;
	private Date edate;
	private Double recSqms;
	private Short type;

	public Rg23airegisterId() {
	}

	public Rg23airegisterId(String coCode, Date date, Float thick, String icode, String particulars, Double opSqMs, Integer rvno, String billNo,
			Date billDate, String party, String range, Integer issueNo, Double issueSqMs, Double closingSqMs, Date sdate, Date edate, Double recSqms,
			Short type) {
		this.coCode = coCode;
		this.date = date;
		this.thick = thick;
		this.icode = icode;
		this.particulars = particulars;
		this.opSqMs = opSqMs;
		this.rvno = rvno;
		this.billNo = billNo;
		this.billDate = billDate;
		this.party = party;
		this.range = range;
		this.issueNo = issueNo;
		this.issueSqMs = issueSqMs;
		this.closingSqMs = closingSqMs;
		this.sdate = sdate;
		this.edate = edate;
		this.recSqms = recSqms;
		this.type = type;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	public Double getOpSqMs() {
		return this.opSqMs;
	}

	public void setOpSqMs(Double opSqMs) {
		this.opSqMs = opSqMs;
	}

	public Integer getRvno() {
		return this.rvno;
	}

	public void setRvno(Integer rvno) {
		this.rvno = rvno;
	}

	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	public String getParty() {
		return this.party;
	}

	public void setParty(String party) {
		this.party = party;
	}

	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

	public Integer getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(Integer issueNo) {
		this.issueNo = issueNo;
	}

	public Double getIssueSqMs() {
		return this.issueSqMs;
	}

	public void setIssueSqMs(Double issueSqMs) {
		this.issueSqMs = issueSqMs;
	}

	public Double getClosingSqMs() {
		return this.closingSqMs;
	}

	public void setClosingSqMs(Double closingSqMs) {
		this.closingSqMs = closingSqMs;
	}

	public Date getSdate() {
		return this.sdate;
	}

	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	public Date getEdate() {
		return this.edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	public Double getRecSqms() {
		return this.recSqms;
	}

	public void setRecSqms(Double recSqms) {
		this.recSqms = recSqms;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Rg23airegisterId))
			return false;
		Rg23airegisterId castOther = (Rg23airegisterId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(
						castOther.getDate())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getParticulars() == castOther.getParticulars()) || (this.getParticulars() != null && castOther.getParticulars() != null && this
						.getParticulars().equals(castOther.getParticulars())))
				&& ((this.getOpSqMs() == castOther.getOpSqMs()) || (this.getOpSqMs() != null && castOther.getOpSqMs() != null && this.getOpSqMs()
						.equals(castOther.getOpSqMs())))
				&& ((this.getRvno() == castOther.getRvno()) || (this.getRvno() != null && castOther.getRvno() != null && this.getRvno().equals(
						castOther.getRvno())))
				&& ((this.getBillNo() == castOther.getBillNo()) || (this.getBillNo() != null && castOther.getBillNo() != null && this.getBillNo()
						.equals(castOther.getBillNo())))
				&& ((this.getBillDate() == castOther.getBillDate()) || (this.getBillDate() != null && castOther.getBillDate() != null && this
						.getBillDate().equals(castOther.getBillDate())))
				&& ((this.getParty() == castOther.getParty()) || (this.getParty() != null && castOther.getParty() != null && this.getParty().equals(
						castOther.getParty())))
				&& ((this.getRange() == castOther.getRange()) || (this.getRange() != null && castOther.getRange() != null && this.getRange().equals(
						castOther.getRange())))
				&& ((this.getIssueNo() == castOther.getIssueNo()) || (this.getIssueNo() != null && castOther.getIssueNo() != null && this
						.getIssueNo().equals(castOther.getIssueNo())))
				&& ((this.getIssueSqMs() == castOther.getIssueSqMs()) || (this.getIssueSqMs() != null && castOther.getIssueSqMs() != null && this
						.getIssueSqMs().equals(castOther.getIssueSqMs())))
				&& ((this.getClosingSqMs() == castOther.getClosingSqMs()) || (this.getClosingSqMs() != null && castOther.getClosingSqMs() != null && this
						.getClosingSqMs().equals(castOther.getClosingSqMs())))
				&& ((this.getSdate() == castOther.getSdate()) || (this.getSdate() != null && castOther.getSdate() != null && this.getSdate().equals(
						castOther.getSdate())))
				&& ((this.getEdate() == castOther.getEdate()) || (this.getEdate() != null && castOther.getEdate() != null && this.getEdate().equals(
						castOther.getEdate())))
				&& ((this.getRecSqms() == castOther.getRecSqms()) || (this.getRecSqms() != null && castOther.getRecSqms() != null && this
						.getRecSqms().equals(castOther.getRecSqms())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this.getType().equals(
						castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getParticulars() == null ? 0 : this.getParticulars().hashCode());
		result = 37 * result + (getOpSqMs() == null ? 0 : this.getOpSqMs().hashCode());
		result = 37 * result + (getRvno() == null ? 0 : this.getRvno().hashCode());
		result = 37 * result + (getBillNo() == null ? 0 : this.getBillNo().hashCode());
		result = 37 * result + (getBillDate() == null ? 0 : this.getBillDate().hashCode());
		result = 37 * result + (getParty() == null ? 0 : this.getParty().hashCode());
		result = 37 * result + (getRange() == null ? 0 : this.getRange().hashCode());
		result = 37 * result + (getIssueNo() == null ? 0 : this.getIssueNo().hashCode());
		result = 37 * result + (getIssueSqMs() == null ? 0 : this.getIssueSqMs().hashCode());
		result = 37 * result + (getClosingSqMs() == null ? 0 : this.getClosingSqMs().hashCode());
		result = 37 * result + (getSdate() == null ? 0 : this.getSdate().hashCode());
		result = 37 * result + (getEdate() == null ? 0 : this.getEdate().hashCode());
		result = 37 * result + (getRecSqms() == null ? 0 : this.getRecSqms().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
