package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * StaxSummary generated by hbm2java
 */
public class StaxSummary implements java.io.Serializable {

	private StaxSummaryId id;

	public StaxSummary() {
	}

	public StaxSummary(StaxSummaryId id) {
		this.id = id;
	}

	public StaxSummaryId getId() {
		return this.id;
	}

	public void setId(StaxSummaryId id) {
		this.id = id;
	}

}
