package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * StaxitemWiseSumId generated by hbm2java
 */
public class StaxitemWiseSumId implements java.io.Serializable {

	private String unit;
	private Date form;
	private Date to;
	private String staxForm;
	private Float staxPer;
	private Double staxAmt;
	private Double staxBasic;
	private String tariff;
	private String particulars;
	private Boolean sale;

	public StaxitemWiseSumId() {
	}

	public StaxitemWiseSumId(String unit, Date form, Date to, String staxForm, Float staxPer, Double staxAmt, Double staxBasic, String tariff,
			String particulars, Boolean sale) {
		this.unit = unit;
		this.form = form;
		this.to = to;
		this.staxForm = staxForm;
		this.staxPer = staxPer;
		this.staxAmt = staxAmt;
		this.staxBasic = staxBasic;
		this.tariff = tariff;
		this.particulars = particulars;
		this.sale = sale;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Date getForm() {
		return this.form;
	}

	public void setForm(Date form) {
		this.form = form;
	}

	public Date getTo() {
		return this.to;
	}

	public void setTo(Date to) {
		this.to = to;
	}

	public String getStaxForm() {
		return this.staxForm;
	}

	public void setStaxForm(String staxForm) {
		this.staxForm = staxForm;
	}

	public Float getStaxPer() {
		return this.staxPer;
	}

	public void setStaxPer(Float staxPer) {
		this.staxPer = staxPer;
	}

	public Double getStaxAmt() {
		return this.staxAmt;
	}

	public void setStaxAmt(Double staxAmt) {
		this.staxAmt = staxAmt;
	}

	public Double getStaxBasic() {
		return this.staxBasic;
	}

	public void setStaxBasic(Double staxBasic) {
		this.staxBasic = staxBasic;
	}

	public String getTariff() {
		return this.tariff;
	}

	public void setTariff(String tariff) {
		this.tariff = tariff;
	}

	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	public Boolean getSale() {
		return this.sale;
	}

	public void setSale(Boolean sale) {
		this.sale = sale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StaxitemWiseSumId))
			return false;
		StaxitemWiseSumId castOther = (StaxitemWiseSumId) other;

		return ((this.getUnit() == castOther.getUnit()) || (this.getUnit() != null && castOther.getUnit() != null && this.getUnit().equals(
				castOther.getUnit())))
				&& ((this.getForm() == castOther.getForm()) || (this.getForm() != null && castOther.getForm() != null && this.getForm().equals(
						castOther.getForm())))
				&& ((this.getTo() == castOther.getTo()) || (this.getTo() != null && castOther.getTo() != null && this.getTo().equals(
						castOther.getTo())))
				&& ((this.getStaxForm() == castOther.getStaxForm()) || (this.getStaxForm() != null && castOther.getStaxForm() != null && this
						.getStaxForm().equals(castOther.getStaxForm())))
				&& ((this.getStaxPer() == castOther.getStaxPer()) || (this.getStaxPer() != null && castOther.getStaxPer() != null && this
						.getStaxPer().equals(castOther.getStaxPer())))
				&& ((this.getStaxAmt() == castOther.getStaxAmt()) || (this.getStaxAmt() != null && castOther.getStaxAmt() != null && this
						.getStaxAmt().equals(castOther.getStaxAmt())))
				&& ((this.getStaxBasic() == castOther.getStaxBasic()) || (this.getStaxBasic() != null && castOther.getStaxBasic() != null && this
						.getStaxBasic().equals(castOther.getStaxBasic())))
				&& ((this.getTariff() == castOther.getTariff()) || (this.getTariff() != null && castOther.getTariff() != null && this.getTariff()
						.equals(castOther.getTariff())))
				&& ((this.getParticulars() == castOther.getParticulars()) || (this.getParticulars() != null && castOther.getParticulars() != null && this
						.getParticulars().equals(castOther.getParticulars())))
				&& ((this.getSale() == castOther.getSale()) || (this.getSale() != null && castOther.getSale() != null && this.getSale().equals(
						castOther.getSale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUnit() == null ? 0 : this.getUnit().hashCode());
		result = 37 * result + (getForm() == null ? 0 : this.getForm().hashCode());
		result = 37 * result + (getTo() == null ? 0 : this.getTo().hashCode());
		result = 37 * result + (getStaxForm() == null ? 0 : this.getStaxForm().hashCode());
		result = 37 * result + (getStaxPer() == null ? 0 : this.getStaxPer().hashCode());
		result = 37 * result + (getStaxAmt() == null ? 0 : this.getStaxAmt().hashCode());
		result = 37 * result + (getStaxBasic() == null ? 0 : this.getStaxBasic().hashCode());
		result = 37 * result + (getTariff() == null ? 0 : this.getTariff().hashCode());
		result = 37 * result + (getParticulars() == null ? 0 : this.getParticulars().hashCode());
		result = 37 * result + (getSale() == null ? 0 : this.getSale().hashCode());
		return result;
	}

}
