package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * StickersId generated by hbm2java
 */
public class StickersId implements java.io.Serializable {

	private String orderNo;
	private Integer itNo;
	private Short width;
	private Short height;
	private Short taper;
	private Short pcs;
	private Short copy;
	private String remarks;
	private String party;
	private String material;

	public StickersId() {
	}

	public StickersId(String orderNo, Integer itNo, Short width, Short height, Short taper, Short pcs, Short copy, String remarks, String party,
			String material) {
		this.orderNo = orderNo;
		this.itNo = itNo;
		this.width = width;
		this.height = height;
		this.taper = taper;
		this.pcs = pcs;
		this.copy = copy;
		this.remarks = remarks;
		this.party = party;
		this.material = material;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Integer getItNo() {
		return this.itNo;
	}

	public void setItNo(Integer itNo) {
		this.itNo = itNo;
	}

	public Short getWidth() {
		return this.width;
	}

	public void setWidth(Short width) {
		this.width = width;
	}

	public Short getHeight() {
		return this.height;
	}

	public void setHeight(Short height) {
		this.height = height;
	}

	public Short getTaper() {
		return this.taper;
	}

	public void setTaper(Short taper) {
		this.taper = taper;
	}

	public Short getPcs() {
		return this.pcs;
	}

	public void setPcs(Short pcs) {
		this.pcs = pcs;
	}

	public Short getCopy() {
		return this.copy;
	}

	public void setCopy(Short copy) {
		this.copy = copy;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getParty() {
		return this.party;
	}

	public void setParty(String party) {
		this.party = party;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StickersId))
			return false;
		StickersId castOther = (StickersId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this.getOrderNo() != null && castOther.getOrderNo() != null && this.getOrderNo()
				.equals(castOther.getOrderNo())))
				&& ((this.getItNo() == castOther.getItNo()) || (this.getItNo() != null && castOther.getItNo() != null && this.getItNo().equals(
						castOther.getItNo())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(
						castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight()
						.equals(castOther.getHeight())))
				&& ((this.getTaper() == castOther.getTaper()) || (this.getTaper() != null && castOther.getTaper() != null && this.getTaper().equals(
						castOther.getTaper())))
				&& ((this.getPcs() == castOther.getPcs()) || (this.getPcs() != null && castOther.getPcs() != null && this.getPcs().equals(
						castOther.getPcs())))
				&& ((this.getCopy() == castOther.getCopy()) || (this.getCopy() != null && castOther.getCopy() != null && this.getCopy().equals(
						castOther.getCopy())))
				&& ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null && castOther.getRemarks() != null && this
						.getRemarks().equals(castOther.getRemarks())))
				&& ((this.getParty() == castOther.getParty()) || (this.getParty() != null && castOther.getParty() != null && this.getParty().equals(
						castOther.getParty())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null && castOther.getMaterial() != null && this
						.getMaterial().equals(castOther.getMaterial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result + (getItNo() == null ? 0 : this.getItNo().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getTaper() == null ? 0 : this.getTaper().hashCode());
		result = 37 * result + (getPcs() == null ? 0 : this.getPcs().hashCode());
		result = 37 * result + (getCopy() == null ? 0 : this.getCopy().hashCode());
		result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
		result = 37 * result + (getParty() == null ? 0 : this.getParty().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		return result;
	}

}
