package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpInvDetails generated by hbm2java
 */
public class TmpInvDetails implements java.io.Serializable {

	private TmpInvDetailsId id;

	public TmpInvDetails() {
	}

	public TmpInvDetails(TmpInvDetailsId id) {
		this.id = id;
	}

	public TmpInvDetailsId getId() {
		return this.id;
	}

	public void setId(TmpInvDetailsId id) {
		this.id = id;
	}

}
