package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpPlamDetailsId generated by hbm2java
 */
public class TmpPlamDetailsId implements java.io.Serializable {

	private String coCode;
	private Integer invNo;
	private String product;
	private Float thick;
	private String icode;
	private String bend;
	private String tough;
	private String class_;
	private String type;
	private Short glId;
	private Integer userId;
	private String invType;
	private Short userIdNo;
	private String grinding;
	private Short frosting;
	private Short beveling;
	private Short printing;
	private Short oddShape;
	private Short holeType1;
	private Short holeNos1;
	private Short holeDia1;
	private Short holeType2;
	private Short holeNos2;
	private Short holeDia2;
	private Short cutoutType1;
	private Short cutoutNos1;
	private Short cutoutType2;
	private Short cutoutNos2;
	private String edgeType;
	private Float bevlWidth;
	private String description;
	private Integer idNo;
	private String uniqueId;

	public TmpPlamDetailsId() {
	}

	public TmpPlamDetailsId(String coCode, Integer invNo, String product, Float thick, String icode, String bend, String tough, String class_,
			String type, Short glId, Integer userId, String invType, Short userIdNo, String grinding, Short frosting, Short beveling, Short printing,
			Short oddShape, Short holeType1, Short holeNos1, Short holeDia1, Short holeType2, Short holeNos2, Short holeDia2, Short cutoutType1,
			Short cutoutNos1, Short cutoutType2, Short cutoutNos2, String edgeType, Float bevlWidth, String description, Integer idNo, String uniqueId) {
		this.coCode = coCode;
		this.invNo = invNo;
		this.product = product;
		this.thick = thick;
		this.icode = icode;
		this.bend = bend;
		this.tough = tough;
		this.class_ = class_;
		this.type = type;
		this.glId = glId;
		this.userId = userId;
		this.invType = invType;
		this.userIdNo = userIdNo;
		this.grinding = grinding;
		this.frosting = frosting;
		this.beveling = beveling;
		this.printing = printing;
		this.oddShape = oddShape;
		this.holeType1 = holeType1;
		this.holeNos1 = holeNos1;
		this.holeDia1 = holeDia1;
		this.holeType2 = holeType2;
		this.holeNos2 = holeNos2;
		this.holeDia2 = holeDia2;
		this.cutoutType1 = cutoutType1;
		this.cutoutNos1 = cutoutNos1;
		this.cutoutType2 = cutoutType2;
		this.cutoutNos2 = cutoutNos2;
		this.edgeType = edgeType;
		this.bevlWidth = bevlWidth;
		this.description = description;
		this.idNo = idNo;
		this.uniqueId = uniqueId;
	}

	public String getCoCode() {
		return this.coCode;
	}

	public void setCoCode(String coCode) {
		this.coCode = coCode;
	}

	public Integer getInvNo() {
		return this.invNo;
	}

	public void setInvNo(Integer invNo) {
		this.invNo = invNo;
	}

	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	public Float getThick() {
		return this.thick;
	}

	public void setThick(Float thick) {
		this.thick = thick;
	}

	public String getIcode() {
		return this.icode;
	}

	public void setIcode(String icode) {
		this.icode = icode;
	}

	public String getBend() {
		return this.bend;
	}

	public void setBend(String bend) {
		this.bend = bend;
	}

	public String getTough() {
		return this.tough;
	}

	public void setTough(String tough) {
		this.tough = tough;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Short getGlId() {
		return this.glId;
	}

	public void setGlId(Short glId) {
		this.glId = glId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getInvType() {
		return this.invType;
	}

	public void setInvType(String invType) {
		this.invType = invType;
	}

	public Short getUserIdNo() {
		return this.userIdNo;
	}

	public void setUserIdNo(Short userIdNo) {
		this.userIdNo = userIdNo;
	}

	public String getGrinding() {
		return this.grinding;
	}

	public void setGrinding(String grinding) {
		this.grinding = grinding;
	}

	public Short getFrosting() {
		return this.frosting;
	}

	public void setFrosting(Short frosting) {
		this.frosting = frosting;
	}

	public Short getBeveling() {
		return this.beveling;
	}

	public void setBeveling(Short beveling) {
		this.beveling = beveling;
	}

	public Short getPrinting() {
		return this.printing;
	}

	public void setPrinting(Short printing) {
		this.printing = printing;
	}

	public Short getOddShape() {
		return this.oddShape;
	}

	public void setOddShape(Short oddShape) {
		this.oddShape = oddShape;
	}

	public Short getHoleType1() {
		return this.holeType1;
	}

	public void setHoleType1(Short holeType1) {
		this.holeType1 = holeType1;
	}

	public Short getHoleNos1() {
		return this.holeNos1;
	}

	public void setHoleNos1(Short holeNos1) {
		this.holeNos1 = holeNos1;
	}

	public Short getHoleDia1() {
		return this.holeDia1;
	}

	public void setHoleDia1(Short holeDia1) {
		this.holeDia1 = holeDia1;
	}

	public Short getHoleType2() {
		return this.holeType2;
	}

	public void setHoleType2(Short holeType2) {
		this.holeType2 = holeType2;
	}

	public Short getHoleNos2() {
		return this.holeNos2;
	}

	public void setHoleNos2(Short holeNos2) {
		this.holeNos2 = holeNos2;
	}

	public Short getHoleDia2() {
		return this.holeDia2;
	}

	public void setHoleDia2(Short holeDia2) {
		this.holeDia2 = holeDia2;
	}

	public Short getCutoutType1() {
		return this.cutoutType1;
	}

	public void setCutoutType1(Short cutoutType1) {
		this.cutoutType1 = cutoutType1;
	}

	public Short getCutoutNos1() {
		return this.cutoutNos1;
	}

	public void setCutoutNos1(Short cutoutNos1) {
		this.cutoutNos1 = cutoutNos1;
	}

	public Short getCutoutType2() {
		return this.cutoutType2;
	}

	public void setCutoutType2(Short cutoutType2) {
		this.cutoutType2 = cutoutType2;
	}

	public Short getCutoutNos2() {
		return this.cutoutNos2;
	}

	public void setCutoutNos2(Short cutoutNos2) {
		this.cutoutNos2 = cutoutNos2;
	}

	public String getEdgeType() {
		return this.edgeType;
	}

	public void setEdgeType(String edgeType) {
		this.edgeType = edgeType;
	}

	public Float getBevlWidth() {
		return this.bevlWidth;
	}

	public void setBevlWidth(Float bevlWidth) {
		this.bevlWidth = bevlWidth;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getIdNo() {
		return this.idNo;
	}

	public void setIdNo(Integer idNo) {
		this.idNo = idNo;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpPlamDetailsId))
			return false;
		TmpPlamDetailsId castOther = (TmpPlamDetailsId) other;

		return ((this.getCoCode() == castOther.getCoCode()) || (this.getCoCode() != null && castOther.getCoCode() != null && this.getCoCode().equals(
				castOther.getCoCode())))
				&& ((this.getInvNo() == castOther.getInvNo()) || (this.getInvNo() != null && castOther.getInvNo() != null && this.getInvNo().equals(
						castOther.getInvNo())))
				&& ((this.getProduct() == castOther.getProduct()) || (this.getProduct() != null && castOther.getProduct() != null && this
						.getProduct().equals(castOther.getProduct())))
				&& ((this.getThick() == castOther.getThick()) || (this.getThick() != null && castOther.getThick() != null && this.getThick().equals(
						castOther.getThick())))
				&& ((this.getIcode() == castOther.getIcode()) || (this.getIcode() != null && castOther.getIcode() != null && this.getIcode().equals(
						castOther.getIcode())))
				&& ((this.getBend() == castOther.getBend()) || (this.getBend() != null && castOther.getBend() != null && this.getBend().equals(
						castOther.getBend())))
				&& ((this.getTough() == castOther.getTough()) || (this.getTough() != null && castOther.getTough() != null && this.getTough().equals(
						castOther.getTough())))
				&& ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null && castOther.getClass_() != null && this.getClass_()
						.equals(castOther.getClass_())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this.getType().equals(
						castOther.getType())))
				&& ((this.getGlId() == castOther.getGlId()) || (this.getGlId() != null && castOther.getGlId() != null && this.getGlId().equals(
						castOther.getGlId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null && castOther.getUserId() != null && this.getUserId()
						.equals(castOther.getUserId())))
				&& ((this.getInvType() == castOther.getInvType()) || (this.getInvType() != null && castOther.getInvType() != null && this
						.getInvType().equals(castOther.getInvType())))
				&& ((this.getUserIdNo() == castOther.getUserIdNo()) || (this.getUserIdNo() != null && castOther.getUserIdNo() != null && this
						.getUserIdNo().equals(castOther.getUserIdNo())))
				&& ((this.getGrinding() == castOther.getGrinding()) || (this.getGrinding() != null && castOther.getGrinding() != null && this
						.getGrinding().equals(castOther.getGrinding())))
				&& ((this.getFrosting() == castOther.getFrosting()) || (this.getFrosting() != null && castOther.getFrosting() != null && this
						.getFrosting().equals(castOther.getFrosting())))
				&& ((this.getBeveling() == castOther.getBeveling()) || (this.getBeveling() != null && castOther.getBeveling() != null && this
						.getBeveling().equals(castOther.getBeveling())))
				&& ((this.getPrinting() == castOther.getPrinting()) || (this.getPrinting() != null && castOther.getPrinting() != null && this
						.getPrinting().equals(castOther.getPrinting())))
				&& ((this.getOddShape() == castOther.getOddShape()) || (this.getOddShape() != null && castOther.getOddShape() != null && this
						.getOddShape().equals(castOther.getOddShape())))
				&& ((this.getHoleType1() == castOther.getHoleType1()) || (this.getHoleType1() != null && castOther.getHoleType1() != null && this
						.getHoleType1().equals(castOther.getHoleType1())))
				&& ((this.getHoleNos1() == castOther.getHoleNos1()) || (this.getHoleNos1() != null && castOther.getHoleNos1() != null && this
						.getHoleNos1().equals(castOther.getHoleNos1())))
				&& ((this.getHoleDia1() == castOther.getHoleDia1()) || (this.getHoleDia1() != null && castOther.getHoleDia1() != null && this
						.getHoleDia1().equals(castOther.getHoleDia1())))
				&& ((this.getHoleType2() == castOther.getHoleType2()) || (this.getHoleType2() != null && castOther.getHoleType2() != null && this
						.getHoleType2().equals(castOther.getHoleType2())))
				&& ((this.getHoleNos2() == castOther.getHoleNos2()) || (this.getHoleNos2() != null && castOther.getHoleNos2() != null && this
						.getHoleNos2().equals(castOther.getHoleNos2())))
				&& ((this.getHoleDia2() == castOther.getHoleDia2()) || (this.getHoleDia2() != null && castOther.getHoleDia2() != null && this
						.getHoleDia2().equals(castOther.getHoleDia2())))
				&& ((this.getCutoutType1() == castOther.getCutoutType1()) || (this.getCutoutType1() != null && castOther.getCutoutType1() != null && this
						.getCutoutType1().equals(castOther.getCutoutType1())))
				&& ((this.getCutoutNos1() == castOther.getCutoutNos1()) || (this.getCutoutNos1() != null && castOther.getCutoutNos1() != null && this
						.getCutoutNos1().equals(castOther.getCutoutNos1())))
				&& ((this.getCutoutType2() == castOther.getCutoutType2()) || (this.getCutoutType2() != null && castOther.getCutoutType2() != null && this
						.getCutoutType2().equals(castOther.getCutoutType2())))
				&& ((this.getCutoutNos2() == castOther.getCutoutNos2()) || (this.getCutoutNos2() != null && castOther.getCutoutNos2() != null && this
						.getCutoutNos2().equals(castOther.getCutoutNos2())))
				&& ((this.getEdgeType() == castOther.getEdgeType()) || (this.getEdgeType() != null && castOther.getEdgeType() != null && this
						.getEdgeType().equals(castOther.getEdgeType())))
				&& ((this.getBevlWidth() == castOther.getBevlWidth()) || (this.getBevlWidth() != null && castOther.getBevlWidth() != null && this
						.getBevlWidth().equals(castOther.getBevlWidth())))
				&& ((this.getDescription() == castOther.getDescription()) || (this.getDescription() != null && castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getIdNo() == castOther.getIdNo()) || (this.getIdNo() != null && castOther.getIdNo() != null && this.getIdNo().equals(
						castOther.getIdNo())))
				&& ((this.getUniqueId() == castOther.getUniqueId()) || (this.getUniqueId() != null && castOther.getUniqueId() != null && this
						.getUniqueId().equals(castOther.getUniqueId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoCode() == null ? 0 : this.getCoCode().hashCode());
		result = 37 * result + (getInvNo() == null ? 0 : this.getInvNo().hashCode());
		result = 37 * result + (getProduct() == null ? 0 : this.getProduct().hashCode());
		result = 37 * result + (getThick() == null ? 0 : this.getThick().hashCode());
		result = 37 * result + (getIcode() == null ? 0 : this.getIcode().hashCode());
		result = 37 * result + (getBend() == null ? 0 : this.getBend().hashCode());
		result = 37 * result + (getTough() == null ? 0 : this.getTough().hashCode());
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getGlId() == null ? 0 : this.getGlId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getInvType() == null ? 0 : this.getInvType().hashCode());
		result = 37 * result + (getUserIdNo() == null ? 0 : this.getUserIdNo().hashCode());
		result = 37 * result + (getGrinding() == null ? 0 : this.getGrinding().hashCode());
		result = 37 * result + (getFrosting() == null ? 0 : this.getFrosting().hashCode());
		result = 37 * result + (getBeveling() == null ? 0 : this.getBeveling().hashCode());
		result = 37 * result + (getPrinting() == null ? 0 : this.getPrinting().hashCode());
		result = 37 * result + (getOddShape() == null ? 0 : this.getOddShape().hashCode());
		result = 37 * result + (getHoleType1() == null ? 0 : this.getHoleType1().hashCode());
		result = 37 * result + (getHoleNos1() == null ? 0 : this.getHoleNos1().hashCode());
		result = 37 * result + (getHoleDia1() == null ? 0 : this.getHoleDia1().hashCode());
		result = 37 * result + (getHoleType2() == null ? 0 : this.getHoleType2().hashCode());
		result = 37 * result + (getHoleNos2() == null ? 0 : this.getHoleNos2().hashCode());
		result = 37 * result + (getHoleDia2() == null ? 0 : this.getHoleDia2().hashCode());
		result = 37 * result + (getCutoutType1() == null ? 0 : this.getCutoutType1().hashCode());
		result = 37 * result + (getCutoutNos1() == null ? 0 : this.getCutoutNos1().hashCode());
		result = 37 * result + (getCutoutType2() == null ? 0 : this.getCutoutType2().hashCode());
		result = 37 * result + (getCutoutNos2() == null ? 0 : this.getCutoutNos2().hashCode());
		result = 37 * result + (getEdgeType() == null ? 0 : this.getEdgeType().hashCode());
		result = 37 * result + (getBevlWidth() == null ? 0 : this.getBevlWidth().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getIdNo() == null ? 0 : this.getIdNo().hashCode());
		result = 37 * result + (getUniqueId() == null ? 0 : this.getUniqueId().hashCode());
		return result;
	}

}
