package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpPlamDetails generated by hbm2java
 */
public class TmpPlamDetails implements java.io.Serializable {

	private TmpPlamDetailsId id;

	public TmpPlamDetails() {
	}

	public TmpPlamDetails(TmpPlamDetailsId id) {
		this.id = id;
	}

	public TmpPlamDetailsId getId() {
		return this.id;
	}

	public void setId(TmpPlamDetailsId id) {
		this.id = id;
	}

}
