package com.sd.app.bean.reportdata;

// Generated Nov 22, 2014 1:17:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmpSticker generated by hbm2java
 */
public class TmpSticker implements java.io.Serializable {

	private TmpStickerId id;

	public TmpSticker() {
	}

	public TmpSticker(TmpStickerId id) {
		this.id = id;
	}

	public TmpStickerId getId() {
		return this.id;
	}

	public void setId(TmpStickerId id) {
		this.id = id;
	}

}
