package com.sd.app.bean.insurance;

// Generated Nov 22, 2014 12:58:31 PM by Hibernate Tools 3.4.0.CR1

/**
 * Insurance generated by hbm2java
 */
public class Insurance implements java.io.Serializable {

	private InsuranceId id;

	public Insurance() {
	}

	public Insurance(InsuranceId id) {
		this.id = id;
	}

	public InsuranceId getId() {
		return this.id;
	}

	public void setId(InsuranceId id) {
		this.id = id;
	}

}
