package com.sd.app.bean.insurance;

// Generated Nov 22, 2014 12:58:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InsurancePoliciesId generated by hbm2java
 */
public class InsurancePoliciesId implements java.io.Serializable {

	private String policyNo;
	private String type;
	private Date date;
	private Float addPer;
	private String company;
	private String address1;
	private String address2;
	private String address3;
	private String city;
	private String pin;
	private String heading;
	private String body;
	private String terms;
	private Double balAmount;
	private Double policyAmount;
	private Short policy;
	private String gscName;
	private String gscAddress;
	private String gscPhone;
	private String gscFax;
	private String gscEmail;
	private String gscWebSite;

	public InsurancePoliciesId() {
	}

	public InsurancePoliciesId(String policyNo, String type, Date date, Float addPer, String company, String address1, String address2,
			String address3, String city, String pin, String heading, String body, String terms, Double balAmount, Double policyAmount, Short policy,
			String gscName, String gscAddress, String gscPhone, String gscFax, String gscEmail, String gscWebSite) {
		this.policyNo = policyNo;
		this.type = type;
		this.date = date;
		this.addPer = addPer;
		this.company = company;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.city = city;
		this.pin = pin;
		this.heading = heading;
		this.body = body;
		this.terms = terms;
		this.balAmount = balAmount;
		this.policyAmount = policyAmount;
		this.policy = policy;
		this.gscName = gscName;
		this.gscAddress = gscAddress;
		this.gscPhone = gscPhone;
		this.gscFax = gscFax;
		this.gscEmail = gscEmail;
		this.gscWebSite = gscWebSite;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Float getAddPer() {
		return this.addPer;
	}

	public void setAddPer(Float addPer) {
		this.addPer = addPer;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getTerms() {
		return this.terms;
	}

	public void setTerms(String terms) {
		this.terms = terms;
	}

	public Double getBalAmount() {
		return this.balAmount;
	}

	public void setBalAmount(Double balAmount) {
		this.balAmount = balAmount;
	}

	public Double getPolicyAmount() {
		return this.policyAmount;
	}

	public void setPolicyAmount(Double policyAmount) {
		this.policyAmount = policyAmount;
	}

	public Short getPolicy() {
		return this.policy;
	}

	public void setPolicy(Short policy) {
		this.policy = policy;
	}

	public String getGscName() {
		return this.gscName;
	}

	public void setGscName(String gscName) {
		this.gscName = gscName;
	}

	public String getGscAddress() {
		return this.gscAddress;
	}

	public void setGscAddress(String gscAddress) {
		this.gscAddress = gscAddress;
	}

	public String getGscPhone() {
		return this.gscPhone;
	}

	public void setGscPhone(String gscPhone) {
		this.gscPhone = gscPhone;
	}

	public String getGscFax() {
		return this.gscFax;
	}

	public void setGscFax(String gscFax) {
		this.gscFax = gscFax;
	}

	public String getGscEmail() {
		return this.gscEmail;
	}

	public void setGscEmail(String gscEmail) {
		this.gscEmail = gscEmail;
	}

	public String getGscWebSite() {
		return this.gscWebSite;
	}

	public void setGscWebSite(String gscWebSite) {
		this.gscWebSite = gscWebSite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InsurancePoliciesId))
			return false;
		InsurancePoliciesId castOther = (InsurancePoliciesId) other;

		return ((this.getPolicyNo() == castOther.getPolicyNo()) || (this.getPolicyNo() != null && castOther.getPolicyNo() != null && this
				.getPolicyNo().equals(castOther.getPolicyNo())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this.getType().equals(
						castOther.getType())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(
						castOther.getDate())))
				&& ((this.getAddPer() == castOther.getAddPer()) || (this.getAddPer() != null && castOther.getAddPer() != null && this.getAddPer()
						.equals(castOther.getAddPer())))
				&& ((this.getCompany() == castOther.getCompany()) || (this.getCompany() != null && castOther.getCompany() != null && this
						.getCompany().equals(castOther.getCompany())))
				&& ((this.getAddress1() == castOther.getAddress1()) || (this.getAddress1() != null && castOther.getAddress1() != null && this
						.getAddress1().equals(castOther.getAddress1())))
				&& ((this.getAddress2() == castOther.getAddress2()) || (this.getAddress2() != null && castOther.getAddress2() != null && this
						.getAddress2().equals(castOther.getAddress2())))
				&& ((this.getAddress3() == castOther.getAddress3()) || (this.getAddress3() != null && castOther.getAddress3() != null && this
						.getAddress3().equals(castOther.getAddress3())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null && this.getCity().equals(
						castOther.getCity())))
				&& ((this.getPin() == castOther.getPin()) || (this.getPin() != null && castOther.getPin() != null && this.getPin().equals(
						castOther.getPin())))
				&& ((this.getHeading() == castOther.getHeading()) || (this.getHeading() != null && castOther.getHeading() != null && this
						.getHeading().equals(castOther.getHeading())))
				&& ((this.getBody() == castOther.getBody()) || (this.getBody() != null && castOther.getBody() != null && this.getBody().equals(
						castOther.getBody())))
				&& ((this.getTerms() == castOther.getTerms()) || (this.getTerms() != null && castOther.getTerms() != null && this.getTerms().equals(
						castOther.getTerms())))
				&& ((this.getBalAmount() == castOther.getBalAmount()) || (this.getBalAmount() != null && castOther.getBalAmount() != null && this
						.getBalAmount().equals(castOther.getBalAmount())))
				&& ((this.getPolicyAmount() == castOther.getPolicyAmount()) || (this.getPolicyAmount() != null && castOther.getPolicyAmount() != null && this
						.getPolicyAmount().equals(castOther.getPolicyAmount())))
				&& ((this.getPolicy() == castOther.getPolicy()) || (this.getPolicy() != null && castOther.getPolicy() != null && this.getPolicy()
						.equals(castOther.getPolicy())))
				&& ((this.getGscName() == castOther.getGscName()) || (this.getGscName() != null && castOther.getGscName() != null && this
						.getGscName().equals(castOther.getGscName())))
				&& ((this.getGscAddress() == castOther.getGscAddress()) || (this.getGscAddress() != null && castOther.getGscAddress() != null && this
						.getGscAddress().equals(castOther.getGscAddress())))
				&& ((this.getGscPhone() == castOther.getGscPhone()) || (this.getGscPhone() != null && castOther.getGscPhone() != null && this
						.getGscPhone().equals(castOther.getGscPhone())))
				&& ((this.getGscFax() == castOther.getGscFax()) || (this.getGscFax() != null && castOther.getGscFax() != null && this.getGscFax()
						.equals(castOther.getGscFax())))
				&& ((this.getGscEmail() == castOther.getGscEmail()) || (this.getGscEmail() != null && castOther.getGscEmail() != null && this
						.getGscEmail().equals(castOther.getGscEmail())))
				&& ((this.getGscWebSite() == castOther.getGscWebSite()) || (this.getGscWebSite() != null && castOther.getGscWebSite() != null && this
						.getGscWebSite().equals(castOther.getGscWebSite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPolicyNo() == null ? 0 : this.getPolicyNo().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getAddPer() == null ? 0 : this.getAddPer().hashCode());
		result = 37 * result + (getCompany() == null ? 0 : this.getCompany().hashCode());
		result = 37 * result + (getAddress1() == null ? 0 : this.getAddress1().hashCode());
		result = 37 * result + (getAddress2() == null ? 0 : this.getAddress2().hashCode());
		result = 37 * result + (getAddress3() == null ? 0 : this.getAddress3().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getPin() == null ? 0 : this.getPin().hashCode());
		result = 37 * result + (getHeading() == null ? 0 : this.getHeading().hashCode());
		result = 37 * result + (getBody() == null ? 0 : this.getBody().hashCode());
		result = 37 * result + (getTerms() == null ? 0 : this.getTerms().hashCode());
		result = 37 * result + (getBalAmount() == null ? 0 : this.getBalAmount().hashCode());
		result = 37 * result + (getPolicyAmount() == null ? 0 : this.getPolicyAmount().hashCode());
		result = 37 * result + (getPolicy() == null ? 0 : this.getPolicy().hashCode());
		result = 37 * result + (getGscName() == null ? 0 : this.getGscName().hashCode());
		result = 37 * result + (getGscAddress() == null ? 0 : this.getGscAddress().hashCode());
		result = 37 * result + (getGscPhone() == null ? 0 : this.getGscPhone().hashCode());
		result = 37 * result + (getGscFax() == null ? 0 : this.getGscFax().hashCode());
		result = 37 * result + (getGscEmail() == null ? 0 : this.getGscEmail().hashCode());
		result = 37 * result + (getGscWebSite() == null ? 0 : this.getGscWebSite().hashCode());
		return result;
	}

}
