package com.sd.app.bean.packingplan;

// Generated Nov 22, 2014 1:11:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * CrateSize generated by hbm2java
 */
public class CrateSize implements java.io.Serializable {

	private CrateSizeId id;

	public CrateSize() {
	}

	public CrateSize(CrateSizeId id) {
		this.id = id;
	}

	public CrateSizeId getId() {
		return this.id;
	}

	public void setId(CrateSizeId id) {
		this.id = id;
	}

}
