package com.sd.app.bean.packingplan;

// Generated Nov 22, 2014 1:11:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * PackingPlan generated by hbm2java
 */
public class PackingPlan implements java.io.Serializable {

	private PackingPlanId id;

	public PackingPlan() {
	}

	public PackingPlan(PackingPlanId id) {
		this.id = id;
	}

	public PackingPlanId getId() {
		return this.id;
	}

	public void setId(PackingPlanId id) {
		this.id = id;
	}

}
